<?xml version="1.0" encoding="UTF-8"?>
<!-- @generated mapFile="xslt/buildErrorMsg1.map" md5sum="8f010d5089f14163fa5911c875e08092" version="7.6.100" -->
<!--
*****************************************************************************
*   This file has been generated by the IBM XML Mapping Editor.
*
*   Mapping file:		buildErrorMsg1.map
*   Map declaration(s):	buildErrorMsg1
*   Input file(s):		smo://smo/name%3Dwsdl-primary/correlationContext%3D%257Bhttp%253A%252F%252FNCL_CruiseUserAuthentication_Module%257DApp_context/message%3D%257Bhttp%253A%252F%252FNCL_CruiseUserAuthentication_Module%252FDB_Lookup%257DexecuteNclseaNcl_Wesb_User_LookupBGRequestMsg/xpath%3D%252F/smo.xsd
*   Output file(s):		smo://smo/name%3Dwsdl-primary/correlationContext%3D%257Bhttp%253A%252F%252FNCL_CruiseUserAuthentication_Module%257DApp_context/message%3D%257Bhttp%253A%252F%252FNCL_WESB_Shared_Library%252FNCL_CruiseUserAuthentication_Interface%257DPerform_NCL_CruiseUserAuthenticationResponseMsg/xpath%3D%252F/smo.xsd
*   XSLT import(s):   	buildSuccess1.xsl
*
*   Note: Do not modify the contents of this file as it is overwritten
*         each time the mapping model is updated.
*****************************************************************************
-->
<xsl:stylesheet
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xalan="http://xml.apache.org/xslt"
    xmlns:str="http://exslt.org/strings"
    xmlns:set="http://exslt.org/sets"
    xmlns:math="http://exslt.org/math"
    xmlns:fn="http://www.w3.org/2005/xpath-functions"
    xmlns:regexp="http://exslt.org/regular-expressions"
    xmlns:dyn="http://exslt.org/dynamic"
    xmlns:dp="http://www.datapower.com/extensions"
    xmlns:exsl="http://exslt.org/common"
    xmlns:date="http://exslt.org/dates-and-times"
    xmlns:in="http://NCL_CruiseUserAuthentication_Module/DB_Lookup"
    xmlns:in2="wsdl.http://NCL_CruiseUserAuthentication_Module/DB_Lookup"
    xmlns:in3="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/nclseancl_wesb_user_lookup"
    xmlns:in4="http://www.ibm.com/xmlns/prod/websphere/bo/6.0.0"
    xmlns:in5="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/nclseancl_wesb_user_lookupbg"
    xmlns:out="http://NCL_WESB_Shared_Library/NCL_CruiseUserAuthentication_Interface"
    xmlns:io="http://www.w3.org/2003/05/soap-envelope"
    xmlns:io3="http://www.ibm.com/xmlns/prod/websphere/mq/sca/6.0.0"
    xmlns:io2="http://www.ibm.com/websphere/sibx/smo/v6.0.1"
    xmlns:out2="wsdl.http://NCL_WESB_Shared_Library/NCL_CruiseUserAuthentication_Interface"
    xmlns:io4="http://schemas.xmlsoap.org/ws/2004/08/addressing"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:io6="http://www.ibm.com/xmlns/prod/websphere/http/sca/6.1.0"
    xmlns:io5="http://nclapi/schemas"
    xmlns:io7="http://NCL_CruiseUserAuthentication_Module"
    xmlns:xs4xs="http://www.w3.org/2001/XMLSchema"
    xmlns:io8="http://www.w3.org/2005/08/addressing"
    xmlns:map="http://NCL_CruiseUserAuthentication_Module/xslt/buildErrorMsg1"
    xmlns:msl="http://www.ibm.com/xmlmap"
    exclude-result-prefixes="in in2 in3 in4 in5 str set math fn regexp dyn dp exsl date map xalan msl"
    version="1.0">

  <!-- imports  -->
  <xsl:import href="buildSuccess1.xsl"/>
  <xsl:output method="xml" encoding="UTF-8" indent="no"/>

  <!-- root wrapper template  -->
  <xsl:template match="/">
    <xsl:choose>
      <xsl:when test="msl:datamap">
        <msl:datamap>
          <xsl:element name="dataObject">
            <xsl:attribute name="xsi:type">
              <xsl:value-of select="'io2:ServiceMessageObject'"/>
            </xsl:attribute>
            <xsl:call-template name="map:buildErrorMsg12">
              <xsl:with-param name="smo" select="msl:datamap/dataObject[1]"/>
            </xsl:call-template>
          </xsl:element>
        </msl:datamap>
      </xsl:when>
      <xsl:otherwise>
        <xsl:apply-templates select="io2:smo" mode="map:buildErrorMsg1"/>
      </xsl:otherwise>
    </xsl:choose>
  </xsl:template>

  <!-- This rule represents an element mapping: "io2:smo" to "io2:smo".  -->
  <xsl:template match="io2:smo"  mode="map:buildErrorMsg1">
    <io2:smo>
      <context>
        <correlation>
          <xsl:attribute name="xsi:type">
            <xsl:value-of select="'io7:App_context'"/>
          </xsl:attribute>
          <!-- a structural mapping: "context/correlation/io5:NCL_CruiseUserAuthenticationRQ"(<Anonymous>) to "io5:NCL_CruiseUserAuthenticationRQ"(<Anonymous>) -->
          <xsl:if test="context/correlation/io5:NCL_CruiseUserAuthenticationRQ">
            <xsl:copy-of select="context/correlation/io5:NCL_CruiseUserAuthenticationRQ"/>
          </xsl:if>
          <!-- a simple data mapping: "context/correlation/LogID"(string) to "LogID"(string) -->
          <xsl:if test="context/correlation/LogID">
            <xsl:element name="LogID">
              <xsl:value-of select="context/correlation/LogID"/>
            </xsl:element>
          </xsl:if>
          <!-- a simple data mapping: "context/correlation/InuptLength"(string) to "InuptLength"(string) -->
          <xsl:if test="context/correlation/InuptLength">
            <xsl:element name="InuptLength">
              <xsl:value-of select="context/correlation/InuptLength"/>
            </xsl:element>
          </xsl:if>
          <!-- a simple data mapping: "context/correlation/OutputLength"(string) to "OutputLength"(string) -->
          <xsl:if test="context/correlation/OutputLength">
            <xsl:element name="OutputLength">
              <xsl:value-of select="context/correlation/OutputLength"/>
            </xsl:element>
          </xsl:if>
        </correlation>
      </context>
      <xsl:element name="body">
        <xsl:attribute name="xsi:type">
          <xsl:value-of select="'out2:Perform_NCL_CruiseUserAuthenticationResponseMsg'"/>
        </xsl:attribute>
        <xsl:element name="out:Perform_NCL_CruiseUserAuthenticationResponse">
          <xsl:element name="io5:NCL_CruiseUserAuthenticationRS">
            <!-- a simple data mapping: "context/correlation/io5:NCL_CruiseUserAuthenticationRQ/@TransactionIdentifier"(StringLength1to32) to "TransactionIdentifier"(StringLength1to32) -->
            <xsl:if test="context/correlation/io5:NCL_CruiseUserAuthenticationRQ/@TransactionIdentifier">
              <xsl:attribute name="TransactionIdentifier">
                <xsl:value-of select="context/correlation/io5:NCL_CruiseUserAuthenticationRQ/@TransactionIdentifier"/>
              </xsl:attribute>
            </xsl:if>
            <!-- a structural mapping: "context/correlation/LogID"(string) to "io5:Success"(SuccessType) -->
            <xsl:if test="context/correlation/LogID">
              <xsl:element name="io5:Success">
                <!-- variables for custom code -->
                <xsl:variable name="LogID" select="context/correlation/LogID"/>
                <xsl:call-template name="LogIDToSuccess">
                  <xsl:with-param name="LogID" select="$LogID"/>
                </xsl:call-template>
              </xsl:element>
            </xsl:if>
            <xsl:element name="io5:Warnings">
              <xsl:element name="io5:Warning">
                <!-- a simple mapping with no associated source:  to "Code"(OTA_CodeType) -->
                <xsl:attribute name="Code">
                  <xsl:value-of select="'9915'"/>
                </xsl:attribute>
                <!-- a simple mapping with no associated source:  to "ShortText"(StringLength1to64) -->
                <xsl:attribute name="ShortText">
                  <xsl:value-of select="'Encrypt/Decrypt length mismatch'"/>
                </xsl:attribute>
              </xsl:element>
            </xsl:element>
          </xsl:element>
        </xsl:element>
      </xsl:element>
    </io2:smo>
  </xsl:template>

  <!-- This rule represents a type mapping: "io2:smo" to "io2:smo".  -->
  <xsl:template name="map:buildErrorMsg12">
    <xsl:param name="smo"/>
    <context>
      <correlation>
        <xsl:attribute name="xsi:type">
          <xsl:value-of select="'io7:App_context'"/>
        </xsl:attribute>
        <!-- a structural mapping: "$smo/context/correlation/io5:NCL_CruiseUserAuthenticationRQ"(<Anonymous>) to "io5:NCL_CruiseUserAuthenticationRQ"(<Anonymous>) -->
        <xsl:if test="$smo/context/correlation/io5:NCL_CruiseUserAuthenticationRQ">
          <xsl:copy-of select="$smo/context/correlation/io5:NCL_CruiseUserAuthenticationRQ"/>
        </xsl:if>
        <!-- a simple data mapping: "$smo/context/correlation/LogID"(string) to "LogID"(string) -->
        <xsl:if test="$smo/context/correlation/LogID">
          <xsl:element name="LogID">
            <xsl:value-of select="$smo/context/correlation/LogID"/>
          </xsl:element>
        </xsl:if>
        <!-- a simple data mapping: "$smo/context/correlation/InuptLength"(string) to "InuptLength"(string) -->
        <xsl:if test="$smo/context/correlation/InuptLength">
          <xsl:element name="InuptLength">
            <xsl:value-of select="$smo/context/correlation/InuptLength"/>
          </xsl:element>
        </xsl:if>
        <!-- a simple data mapping: "$smo/context/correlation/OutputLength"(string) to "OutputLength"(string) -->
        <xsl:if test="$smo/context/correlation/OutputLength">
          <xsl:element name="OutputLength">
            <xsl:value-of select="$smo/context/correlation/OutputLength"/>
          </xsl:element>
        </xsl:if>
      </correlation>
    </context>
    <xsl:element name="body">
      <xsl:attribute name="xsi:type">
        <xsl:value-of select="'out2:Perform_NCL_CruiseUserAuthenticationResponseMsg'"/>
      </xsl:attribute>
      <xsl:element name="out:Perform_NCL_CruiseUserAuthenticationResponse">
        <xsl:element name="io5:NCL_CruiseUserAuthenticationRS">
          <!-- a simple data mapping: "$smo/context/correlation/io5:NCL_CruiseUserAuthenticationRQ/@TransactionIdentifier"(StringLength1to32) to "TransactionIdentifier"(StringLength1to32) -->
          <xsl:if test="$smo/context/correlation/io5:NCL_CruiseUserAuthenticationRQ/@TransactionIdentifier">
            <xsl:attribute name="TransactionIdentifier">
              <xsl:value-of select="$smo/context/correlation/io5:NCL_CruiseUserAuthenticationRQ/@TransactionIdentifier"/>
            </xsl:attribute>
          </xsl:if>
          <!-- a structural mapping: "$smo/context/correlation/LogID"(string) to "io5:Success"(SuccessType) -->
          <xsl:if test="$smo/context/correlation/LogID">
            <xsl:element name="io5:Success">
              <!-- variables for custom code -->
              <xsl:variable name="LogID" select="$smo/context/correlation/LogID"/>
              <xsl:call-template name="LogIDToSuccess">
                <xsl:with-param name="LogID" select="$LogID"/>
              </xsl:call-template>
            </xsl:element>
          </xsl:if>
          <xsl:element name="io5:Warnings">
            <xsl:element name="io5:Warning">
              <!-- a simple mapping with no associated source:  to "Code"(OTA_CodeType) -->
              <xsl:attribute name="Code">
                <xsl:value-of select="'9915'"/>
              </xsl:attribute>
              <!-- a simple mapping with no associated source:  to "ShortText"(StringLength1to64) -->
              <xsl:attribute name="ShortText">
                <xsl:value-of select="'Encrypt/Decrypt length mismatch'"/>
              </xsl:attribute>
            </xsl:element>
          </xsl:element>
        </xsl:element>
      </xsl:element>
    </xsl:element>
  </xsl:template>

  <!-- *****************    Utility Templates    ******************  -->
  <!-- copy the namespace declarations from the source to the target -->
  <xsl:template name="copyNamespaceDeclarations">
    <xsl:param name="root"/>
    <xsl:for-each select="$root/namespace::*[not(name() = '')]">
      <xsl:copy/>
    </xsl:for-each>
  </xsl:template>
</xsl:stylesheet>
