<?xml version="1.0" encoding="UTF-8"?>
<!-- @generated mapFile="xslt/XSLT_BuildResponse.map" md5sum="938eba1b260e997359e5d12813be12ce" version="7.6.100" -->
<!--
*****************************************************************************
*   This file has been generated by the IBM XML Mapping Editor.
*
*   Mapping file:		XSLT_BuildResponse.map
*   Map declaration(s):	XSLT_BuildResponse
*   Input file(s):		smo://smo/name%3Dwsdl-primary/correlationContext%3D%257Bhttp%253A%252F%252FNCL_LATITUDES_CLIENT_POINTS_TRG_Module%257DAppContext/message%3D%257Bhttp%253A%252F%252FNCL_LATITUDES_CLIENT_POINTS_TRG_Module%252FJDBCImport%257DexecuteNclseaNcl_Lat_Insert_TrgResponseMsg/xpath%3D%252F/smo.xsd
*   Output file(s):		smo://smo/name%3Dwsdl-primary/correlationContext%3D%257Bhttp%253A%252F%252FNCL_LATITUDES_CLIENT_POINTS_TRG_Module%257DAppContext/message%3D%257Bhttp%253A%252F%252FNCL_WESB_Shared_Library%252FNCL_LATITUDES_CLIENT_POINTS_TRG_Interface%257DPerform_NCL_LATITUDES_CLIENT_POINTS_TRGResponseMsg/xpath%3D%252F/smo.xsd
*   XSLT import(s):   	XSLT_BuildSuccess.xsl
*
*   Note: Do not modify the contents of this file as it is overwritten
*         each time the mapping model is updated.
*****************************************************************************
-->
<xsl:stylesheet
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xalan="http://xml.apache.org/xslt"
    xmlns:str="http://exslt.org/strings"
    xmlns:set="http://exslt.org/sets"
    xmlns:math="http://exslt.org/math"
    xmlns:fn="http://www.w3.org/2005/xpath-functions"
    xmlns:regexp="http://exslt.org/regular-expressions"
    xmlns:dyn="http://exslt.org/dynamic"
    xmlns:dp="http://www.datapower.com/extensions"
    xmlns:exsl="http://exslt.org/common"
    xmlns:date="http://exslt.org/dates-and-times"
    xmlns:in="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/nclseancl_lat_insert_trg"
    xmlns:in2="http://NCL_LATITUDES_CLIENT_POINTS_TRG_Module/JDBCImport"
    xmlns:in3="http://com/ibm/j2ca/fault"
    xmlns:in4="wsdl.http://NCL_LATITUDES_CLIENT_POINTS_TRG_Module/JDBCImport"
    xmlns:in5="http://com/ibm/j2ca/fault/afcfault"
    xmlns:io="http://www.w3.org/2003/05/soap-envelope"
    xmlns:io3="http://www.ibm.com/xmlns/prod/websphere/mq/sca/6.0.0"
    xmlns:io2="http://www.ibm.com/websphere/sibx/smo/v6.0.1"
    xmlns:out="http://NCL_WESB_Shared_Library/NCL_LATITUDES_CLIENT_POINTS_TRG_Interface"
    xmlns:io4="http://schemas.xmlsoap.org/ws/2004/08/addressing"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:io5="http://www.ibm.com/xmlns/prod/websphere/http/sca/6.1.0"
    xmlns:io6="http://NCL_LATITUDES_CLIENT_POINTS_TRG_Module"
    xmlns:xs4xs="http://www.w3.org/2001/XMLSchema"
    xmlns:io7="http://www.w3.org/2005/08/addressing"
    xmlns:out2="wsdl.http://NCL_WESB_Shared_Library/NCL_LATITUDES_CLIENT_POINTS_TRG_Interface"
    xmlns:map="http://NCL_LATITUDES_CLIENT_POINTS_TRG_Module/xslt/XSLT_BuildResponse"
    xmlns:msl="http://www.ibm.com/xmlmap"
    exclude-result-prefixes="in in2 in3 in4 in5 str set math fn regexp dyn dp exsl date map xalan msl"
    version="1.0">

  <!-- imports  -->
  <xsl:import href="XSLT_BuildSuccess.xsl"/>
  <xsl:output method="xml" encoding="UTF-8" indent="no"/>

  <!-- root wrapper template  -->
  <xsl:template match="/">
    <xsl:choose>
      <xsl:when test="msl:datamap">
        <msl:datamap>
          <xsl:element name="dataObject">
            <xsl:attribute name="xsi:type">
              <xsl:value-of select="'io2:ServiceMessageObject'"/>
            </xsl:attribute>
            <xsl:call-template name="map:XSLT_BuildResponse2">
              <xsl:with-param name="smo" select="msl:datamap/dataObject[1]"/>
            </xsl:call-template>
          </xsl:element>
        </msl:datamap>
      </xsl:when>
      <xsl:otherwise>
        <xsl:apply-templates select="io2:smo" mode="map:XSLT_BuildResponse"/>
      </xsl:otherwise>
    </xsl:choose>
  </xsl:template>

  <!-- This rule represents an element mapping: "io2:smo" to "io2:smo".  -->
  <xsl:template match="io2:smo"  mode="map:XSLT_BuildResponse">
    <io2:smo>
      <context>
        <correlation>
          <xsl:attribute name="xsi:type">
            <xsl:value-of select="'io6:AppContext'"/>
          </xsl:attribute>
          <!-- a simple data mapping: "context/correlation/LogId"(string) to "LogId"(string) -->
          <xsl:if test="context/correlation/LogId">
            <xsl:element name="LogId">
              <xsl:value-of select="context/correlation/LogId"/>
            </xsl:element>
          </xsl:if>
          <!-- a structural mapping: "context/correlation/NCL_LATITUDES_CLIENT_POINTS_TRG_REQ"(<Anonymous>) to "NCL_LATITUDES_CLIENT_POINTS_TRG_REQ"(<Anonymous>) -->
          <xsl:if test="context/correlation/NCL_LATITUDES_CLIENT_POINTS_TRG_REQ">
            <xsl:copy-of select="context/correlation/NCL_LATITUDES_CLIENT_POINTS_TRG_REQ"/>
          </xsl:if>
          <xsl:element name="NCL_LATITUDES_CLIENT_POINTS_TRG_RESP">
            <!-- a simple data mapping: "context/correlation/NCL_LATITUDES_CLIENT_POINTS_TRG_REQ/TRANSACTION_ID"(string) to "SUCCESS"(string) -->
            <xsl:element name="SUCCESS">
              <!-- variables for custom code -->
              <xsl:variable name="TRANSACTION_ID" select="context/correlation/NCL_LATITUDES_CLIENT_POINTS_TRG_REQ/TRANSACTION_ID"/>
              <xsl:call-template name="TRANSACTION_IDToSUCCESS">
                <xsl:with-param name="TRANSACTION_ID" select="$TRANSACTION_ID"/>
              </xsl:call-template>
            </xsl:element>
            <!-- a simple data mapping: "body/in2:executeNclseaNcl_Lat_Insert_TrgResponse/in2:executeNclseaNcl_Lat_Insert_TrgOutput/p_errorcode"(string) to "ERROR_CODE"(string) -->
            <xsl:if test="body/in2:executeNclseaNcl_Lat_Insert_TrgResponse/in2:executeNclseaNcl_Lat_Insert_TrgOutput/p_errorcode">
              <xsl:element name="ERROR_CODE">
                <xsl:value-of select="body/in2:executeNclseaNcl_Lat_Insert_TrgResponse/in2:executeNclseaNcl_Lat_Insert_TrgOutput/p_errorcode"/>
              </xsl:element>
            </xsl:if>
          </xsl:element>
        </correlation>
      </context>
    </io2:smo>
  </xsl:template>

  <!-- This rule represents a type mapping: "io2:smo" to "io2:smo".  -->
  <xsl:template name="map:XSLT_BuildResponse2">
    <xsl:param name="smo"/>
    <context>
      <correlation>
        <xsl:attribute name="xsi:type">
          <xsl:value-of select="'io6:AppContext'"/>
        </xsl:attribute>
        <!-- a simple data mapping: "$smo/context/correlation/LogId"(string) to "LogId"(string) -->
        <xsl:if test="$smo/context/correlation/LogId">
          <xsl:element name="LogId">
            <xsl:value-of select="$smo/context/correlation/LogId"/>
          </xsl:element>
        </xsl:if>
        <!-- a structural mapping: "$smo/context/correlation/NCL_LATITUDES_CLIENT_POINTS_TRG_REQ"(<Anonymous>) to "NCL_LATITUDES_CLIENT_POINTS_TRG_REQ"(<Anonymous>) -->
        <xsl:if test="$smo/context/correlation/NCL_LATITUDES_CLIENT_POINTS_TRG_REQ">
          <xsl:copy-of select="$smo/context/correlation/NCL_LATITUDES_CLIENT_POINTS_TRG_REQ"/>
        </xsl:if>
        <xsl:element name="NCL_LATITUDES_CLIENT_POINTS_TRG_RESP">
          <!-- a simple data mapping: "$smo/context/correlation/NCL_LATITUDES_CLIENT_POINTS_TRG_REQ/TRANSACTION_ID"(string) to "SUCCESS"(string) -->
          <xsl:element name="SUCCESS">
            <!-- variables for custom code -->
            <xsl:variable name="TRANSACTION_ID" select="$smo/context/correlation/NCL_LATITUDES_CLIENT_POINTS_TRG_REQ/TRANSACTION_ID"/>
            <xsl:call-template name="TRANSACTION_IDToSUCCESS">
              <xsl:with-param name="TRANSACTION_ID" select="$TRANSACTION_ID"/>
            </xsl:call-template>
          </xsl:element>
          <!-- a simple data mapping: "$smo/body/in2:executeNclseaNcl_Lat_Insert_TrgResponse/in2:executeNclseaNcl_Lat_Insert_TrgOutput/p_errorcode"(string) to "ERROR_CODE"(string) -->
          <xsl:if test="$smo/body/in2:executeNclseaNcl_Lat_Insert_TrgResponse/in2:executeNclseaNcl_Lat_Insert_TrgOutput/p_errorcode">
            <xsl:element name="ERROR_CODE">
              <xsl:value-of select="$smo/body/in2:executeNclseaNcl_Lat_Insert_TrgResponse/in2:executeNclseaNcl_Lat_Insert_TrgOutput/p_errorcode"/>
            </xsl:element>
          </xsl:if>
        </xsl:element>
      </correlation>
    </context>
  </xsl:template>

  <!-- *****************    Utility Templates    ******************  -->
  <!-- copy the namespace declarations from the source to the target -->
  <xsl:template name="copyNamespaceDeclarations">
    <xsl:param name="root"/>
    <xsl:for-each select="$root/namespace::*[not(name() = '')]">
      <xsl:copy/>
    </xsl:for-each>
  </xsl:template>
</xsl:stylesheet>
