<?xml version="1.0" encoding="UTF-8"?>
<!-- @generated mapFile="xslt/XSLTransformation3_req_1.map" md5sum="a24bca6de82669fa47963ea4abff59da" version="7.6.100" -->
<!--
*****************************************************************************
*   This file has been generated by the IBM XML Mapping Editor.
*
*   Mapping file:		XSLTransformation3_req_1.map
*   Map declaration(s):	XSLTransformation3_req_1
*   Input file(s):		smo://smo/name%3Dwsdl-primary/correlationContext%3D%257Bhttp%253A%252F%252FNCL_CruiseCreateAgency_Module%257DApp_context/message%3D%257Bhttp%253A%252F%252FNCL_CruiseCreateAgency_Module%252FDB_Lookup%257DexecuteNclseaNcl_Wesb_Upd_Agc_Conpref_InfoBGResponseMsg/xpath%3D%252F/smo.xsd
*   Output file(s):		smo://smo/name%3Dwsdl-primary/correlationContext%3D%257Bhttp%253A%252F%252FNCL_CruiseCreateAgency_Module%257DApp_context/message%3D%257Bhttp%253A%252F%252FNCL_WESB_Shared_Library%252FNCL_CruiseCreateAgency_Interface%257DPerform_NCL_CruiseCreateAgencyResponseMsg/xpath%3D%252F/smo.xsd
*   XSLT import(s):   	XSLTransformation3_req_1_custom.xsl
*
*   Note: Do not modify the contents of this file as it is overwritten
*         each time the mapping model is updated.
*****************************************************************************
-->
<xsl:stylesheet
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xalan="http://xml.apache.org/xslt"
    xmlns:str="http://exslt.org/strings"
    xmlns:set="http://exslt.org/sets"
    xmlns:math="http://exslt.org/math"
    xmlns:fn="http://www.w3.org/2005/xpath-functions"
    xmlns:regexp="http://exslt.org/regular-expressions"
    xmlns:dyn="http://exslt.org/dynamic"
    xmlns:dp="http://www.datapower.com/extensions"
    xmlns:exsl="http://exslt.org/common"
    xmlns:date="http://exslt.org/dates-and-times"
    xmlns:in2="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/nclseancl_wesb_update_agency_info"
    xmlns:in="http://NCL_CruiseCreateAgency_Module/DB_Lookup"
    xmlns:in3="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/nclseancl_wesb_update_agency_infobg"
    xmlns:in4="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/nclseancl_wesb_upd_agency_phone_info"
    xmlns:in5="wsdl.http://NCL_CruiseCreateAgency_Module/DB_Lookup"
    xmlns:in6="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/nclseancl_wesb_upd_agency_phone_infobg"
    xmlns:in7="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/nclseancl_wesb_upd_agency_email_info"
    xmlns:in8="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/nclseancl_wesb_upd_agency_email_infobg"
    xmlns:in9="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/nclseancl_wesb_upd_agency_addr_info"
    xmlns:in10="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/nclseancl_wesb_upd_agency_addr_infobg"
    xmlns:in11="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/nclseancl_wesb_create_agency"
    xmlns:in12="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/nclseancl_wesb_upd_agc_conpref_info"
    xmlns:in13="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/nclseancl_wesb_create_agencybg"
    xmlns:in15="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/nclseancl_wesb_upd_agc_conpref_infobg"
    xmlns:in14="http://www.ibm.com/xmlns/prod/websphere/bo/6.0.0"
    xmlns:io="http://www.w3.org/2003/05/soap-envelope"
    xmlns:io3="http://www.ibm.com/xmlns/prod/websphere/mq/sca/6.0.0"
    xmlns:io2="http://www.ibm.com/websphere/sibx/smo/v6.0.1"
    xmlns:out="wsdl.http://NCL_WESB_Shared_Library/NCL_CruiseCreateAgency_Interface"
    xmlns:io4="http://schemas.xmlsoap.org/ws/2004/08/addressing"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:io6="http://www.ibm.com/xmlns/prod/websphere/http/sca/6.1.0"
    xmlns:io5="http://nclapi/schemas"
    xmlns:io7="http://NCL_CruiseCreateAgency_Module"
    xmlns:xs4xs="http://www.w3.org/2001/XMLSchema"
    xmlns:io8="http://www.w3.org/2005/08/addressing"
    xmlns:out2="http://NCL_WESB_Shared_Library/NCL_CruiseCreateAgency_Interface"
    xmlns:map="http://NCL_CruiseCreateAgency_Module/xslt/XSLTransformation3_req_1"
    xmlns:msl="http://www.ibm.com/xmlmap"
    exclude-result-prefixes="in2 in in3 in4 in5 in6 in7 in8 in9 in10 in11 in12 in13 in15 in14 str set math fn regexp dyn dp exsl date map xalan msl"
    version="1.0">

  <!-- imports  -->
  <xsl:import href="XSLTransformation3_req_1_custom.xsl"/>
  <xsl:output method="xml" encoding="UTF-8" indent="no"/>

  <!-- root wrapper template  -->
  <xsl:template match="/">
    <xsl:choose>
      <xsl:when test="msl:datamap">
        <msl:datamap>
          <xsl:element name="dataObject">
            <xsl:attribute name="xsi:type">
              <xsl:value-of select="'io2:ServiceMessageObject'"/>
            </xsl:attribute>
            <xsl:call-template name="map:XSLTransformation3_req_12">
              <xsl:with-param name="smo" select="msl:datamap/dataObject[1]"/>
            </xsl:call-template>
          </xsl:element>
        </msl:datamap>
      </xsl:when>
      <xsl:otherwise>
        <xsl:apply-templates select="io2:smo" mode="map:XSLTransformation3_req_1"/>
      </xsl:otherwise>
    </xsl:choose>
  </xsl:template>

  <!-- This rule represents an element mapping: "io2:smo" to "io2:smo".  -->
  <xsl:template match="io2:smo"  mode="map:XSLTransformation3_req_1">
    <io2:smo>
      <context>
        <correlation>
          <xsl:attribute name="xsi:type">
            <xsl:value-of select="'io7:App_context'"/>
          </xsl:attribute>
          <!-- a structural mapping: "context/correlation/io5:NCL_CruiseCreateAgencyRQ"(<Anonymous>) to "io5:NCL_CruiseCreateAgencyRQ"(<Anonymous>) -->
          <xsl:if test="context/correlation/io5:NCL_CruiseCreateAgencyRQ">
            <xsl:copy-of select="context/correlation/io5:NCL_CruiseCreateAgencyRQ"/>
          </xsl:if>
          <!-- a simple data mapping: "context/correlation/LogID"(string) to "LogID"(string) -->
          <xsl:if test="context/correlation/LogID">
            <xsl:element name="LogID">
              <xsl:value-of select="context/correlation/LogID"/>
            </xsl:element>
          </xsl:if>
        </correlation>
      </context>
      <xsl:element name="body">
        <xsl:attribute name="xsi:type">
          <xsl:value-of select="'out:Perform_NCL_CruiseCreateAgencyResponseMsg'"/>
        </xsl:attribute>
        <xsl:element name="out2:Perform_NCL_CruiseCreateAgencyResponse">
          <xsl:element name="io5:NCL_CruiseCreateAgencyRS">
            <!-- a simple data mapping: "context/correlation/io5:NCL_CruiseCreateAgencyRQ/@TransactionIdentifier"(StringLength1to32) to "TransactionIdentifier"(StringLength1to32) -->
            <xsl:if test="context/correlation/io5:NCL_CruiseCreateAgencyRQ/@TransactionIdentifier">
              <xsl:attribute name="TransactionIdentifier">
                <xsl:value-of select="context/correlation/io5:NCL_CruiseCreateAgencyRQ/@TransactionIdentifier"/>
              </xsl:attribute>
            </xsl:if>
            <!-- a structural mapping with no associated source:  to "io5:Success"(SuccessType) -->
            <xsl:element name="io5:Success">
              <xsl:call-template name="ToSuccess"/>
            </xsl:element>
            <xsl:element name="io5:Warnings">
              <xsl:element name="io5:Warning">
                <!-- a simple data mapping: "body/in:executeNclseaNcl_Wesb_Upd_Agc_Conpref_InfoBGResponse/in:executeNclseaNcl_Wesb_Upd_Agc_Conpref_InfoBGOutput/NclseaNcl_Wesb_Upd_Agc_Conpref_Info/p_errorcode"(string) to "Code"(OTA_CodeType) -->
                <xsl:if test="body/in:executeNclseaNcl_Wesb_Upd_Agc_Conpref_InfoBGResponse/in:executeNclseaNcl_Wesb_Upd_Agc_Conpref_InfoBGOutput/NclseaNcl_Wesb_Upd_Agc_Conpref_Info/p_errorcode">
                  <xsl:attribute name="Code">
                    <xsl:value-of select="body/in:executeNclseaNcl_Wesb_Upd_Agc_Conpref_InfoBGResponse/in:executeNclseaNcl_Wesb_Upd_Agc_Conpref_InfoBGOutput/NclseaNcl_Wesb_Upd_Agc_Conpref_Info/p_errorcode"/>
                  </xsl:attribute>
                </xsl:if>
                <!-- a simple data mapping: "body/in:executeNclseaNcl_Wesb_Upd_Agc_Conpref_InfoBGResponse/in:executeNclseaNcl_Wesb_Upd_Agc_Conpref_InfoBGOutput/NclseaNcl_Wesb_Upd_Agc_Conpref_Info/p_errormsg"(string) to "ShortText"(StringLength1to64) -->
                <xsl:if test="body/in:executeNclseaNcl_Wesb_Upd_Agc_Conpref_InfoBGResponse/in:executeNclseaNcl_Wesb_Upd_Agc_Conpref_InfoBGOutput/NclseaNcl_Wesb_Upd_Agc_Conpref_Info/p_errormsg">
                  <xsl:attribute name="ShortText">
                    <xsl:value-of select="body/in:executeNclseaNcl_Wesb_Upd_Agc_Conpref_InfoBGResponse/in:executeNclseaNcl_Wesb_Upd_Agc_Conpref_InfoBGOutput/NclseaNcl_Wesb_Upd_Agc_Conpref_Info/p_errormsg"/>
                  </xsl:attribute>
                </xsl:if>
              </xsl:element>
            </xsl:element>
          </xsl:element>
        </xsl:element>
      </xsl:element>
    </io2:smo>
  </xsl:template>

  <!-- This rule represents a type mapping: "io2:smo" to "io2:smo".  -->
  <xsl:template name="map:XSLTransformation3_req_12">
    <xsl:param name="smo"/>
    <context>
      <correlation>
        <xsl:attribute name="xsi:type">
          <xsl:value-of select="'io7:App_context'"/>
        </xsl:attribute>
        <!-- a structural mapping: "$smo/context/correlation/io5:NCL_CruiseCreateAgencyRQ"(<Anonymous>) to "io5:NCL_CruiseCreateAgencyRQ"(<Anonymous>) -->
        <xsl:if test="$smo/context/correlation/io5:NCL_CruiseCreateAgencyRQ">
          <xsl:copy-of select="$smo/context/correlation/io5:NCL_CruiseCreateAgencyRQ"/>
        </xsl:if>
        <!-- a simple data mapping: "$smo/context/correlation/LogID"(string) to "LogID"(string) -->
        <xsl:if test="$smo/context/correlation/LogID">
          <xsl:element name="LogID">
            <xsl:value-of select="$smo/context/correlation/LogID"/>
          </xsl:element>
        </xsl:if>
      </correlation>
    </context>
    <xsl:element name="body">
      <xsl:attribute name="xsi:type">
        <xsl:value-of select="'out:Perform_NCL_CruiseCreateAgencyResponseMsg'"/>
      </xsl:attribute>
      <xsl:element name="out2:Perform_NCL_CruiseCreateAgencyResponse">
        <xsl:element name="io5:NCL_CruiseCreateAgencyRS">
          <!-- a simple data mapping: "$smo/context/correlation/io5:NCL_CruiseCreateAgencyRQ/@TransactionIdentifier"(StringLength1to32) to "TransactionIdentifier"(StringLength1to32) -->
          <xsl:if test="$smo/context/correlation/io5:NCL_CruiseCreateAgencyRQ/@TransactionIdentifier">
            <xsl:attribute name="TransactionIdentifier">
              <xsl:value-of select="$smo/context/correlation/io5:NCL_CruiseCreateAgencyRQ/@TransactionIdentifier"/>
            </xsl:attribute>
          </xsl:if>
          <!-- a structural mapping with no associated source:  to "io5:Success"(SuccessType) -->
          <xsl:element name="io5:Success">
            <xsl:call-template name="ToSuccess"/>
          </xsl:element>
          <xsl:element name="io5:Warnings">
            <xsl:element name="io5:Warning">
              <!-- a simple data mapping: "$smo/body/in:executeNclseaNcl_Wesb_Upd_Agc_Conpref_InfoBGResponse/in:executeNclseaNcl_Wesb_Upd_Agc_Conpref_InfoBGOutput/NclseaNcl_Wesb_Upd_Agc_Conpref_Info/p_errorcode"(string) to "Code"(OTA_CodeType) -->
              <xsl:if test="$smo/body/in:executeNclseaNcl_Wesb_Upd_Agc_Conpref_InfoBGResponse/in:executeNclseaNcl_Wesb_Upd_Agc_Conpref_InfoBGOutput/NclseaNcl_Wesb_Upd_Agc_Conpref_Info/p_errorcode">
                <xsl:attribute name="Code">
                  <xsl:value-of select="$smo/body/in:executeNclseaNcl_Wesb_Upd_Agc_Conpref_InfoBGResponse/in:executeNclseaNcl_Wesb_Upd_Agc_Conpref_InfoBGOutput/NclseaNcl_Wesb_Upd_Agc_Conpref_Info/p_errorcode"/>
                </xsl:attribute>
              </xsl:if>
              <!-- a simple data mapping: "$smo/body/in:executeNclseaNcl_Wesb_Upd_Agc_Conpref_InfoBGResponse/in:executeNclseaNcl_Wesb_Upd_Agc_Conpref_InfoBGOutput/NclseaNcl_Wesb_Upd_Agc_Conpref_Info/p_errormsg"(string) to "ShortText"(StringLength1to64) -->
              <xsl:if test="$smo/body/in:executeNclseaNcl_Wesb_Upd_Agc_Conpref_InfoBGResponse/in:executeNclseaNcl_Wesb_Upd_Agc_Conpref_InfoBGOutput/NclseaNcl_Wesb_Upd_Agc_Conpref_Info/p_errormsg">
                <xsl:attribute name="ShortText">
                  <xsl:value-of select="$smo/body/in:executeNclseaNcl_Wesb_Upd_Agc_Conpref_InfoBGResponse/in:executeNclseaNcl_Wesb_Upd_Agc_Conpref_InfoBGOutput/NclseaNcl_Wesb_Upd_Agc_Conpref_Info/p_errormsg"/>
                </xsl:attribute>
              </xsl:if>
            </xsl:element>
          </xsl:element>
        </xsl:element>
      </xsl:element>
    </xsl:element>
  </xsl:template>

  <!-- *****************    Utility Templates    ******************  -->
  <!-- copy the namespace declarations from the source to the target -->
  <xsl:template name="copyNamespaceDeclarations">
    <xsl:param name="root"/>
    <xsl:for-each select="$root/namespace::*[not(name() = '')]">
      <xsl:copy/>
    </xsl:for-each>
  </xsl:template>
</xsl:stylesheet>
