<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions name="NCL_CruiseCreateAgency_InterfaceExport1_NCL_CruiseCreateAgency_InterfaceHttp_Service" targetNamespace="http://NCL_WESB_Shared_Library/NCL_CruiseCreateAgency_Interface/Binding" xmlns:Port_0="http://NCL_WESB_Shared_Library/NCL_CruiseCreateAgency_Interface" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:this="http://NCL_WESB_Shared_Library/NCL_CruiseCreateAgency_Interface/Binding" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:import location="NCL_CruiseCreateAgency_Interface.wsdl" namespace="http://NCL_WESB_Shared_Library/NCL_CruiseCreateAgency_Interface"/>
  <wsdl:binding name="NCL_CruiseCreateAgency_InterfaceExport1_NCL_CruiseCreateAgency_InterfaceHttpBinding" type="Port_0:NCL_CruiseCreateAgency_Interface">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="Perform_NCL_CruiseCreateAgency">
      <soap:operation soapAction=""/>
      <wsdl:input name="Perform_NCL_CruiseCreateAgencyRequest">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="Perform_NCL_CruiseCreateAgencyResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="NCL_CruiseCreateAgency_InterfaceExport1_NCL_CruiseCreateAgency_InterfaceHttpService">
    <wsdl:port binding="this:NCL_CruiseCreateAgency_InterfaceExport1_NCL_CruiseCreateAgency_InterfaceHttpBinding" name="NCL_CruiseCreateAgency_InterfaceExport1_NCL_CruiseCreateAgency_InterfaceHttpPort">
      <soap:address location="http://localhost:9080/NCL_CruiseCreateAgency_ModuleWeb/sca/NCL_CruiseCreateAgency_InterfaceExport1"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>