<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions name="NCL_CruiseGroupContract_Interface" targetNamespace="http://NCL_WESB_Shared_Library/NCL_CruiseGroupContract_Interface" xmlns:bons1="http://nclapi/schemas" xmlns:tns="http://NCL_WESB_Shared_Library/NCL_CruiseGroupContract_Interface" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <wsdl:types>
    <xsd:schema targetNamespace="http://NCL_WESB_Shared_Library/NCL_CruiseGroupContract_Interface">
      <xsd:import namespace="http://nclapi/schemas" schemaLocation="NCL_CruiseGroupContractRS.xsd"/>
      <xsd:import namespace="http://nclapi/schemas" schemaLocation="NCL_CruiseGroupContractRQ.xsd"/>
      <xsd:element name="Perform_NCL_CruiseGroupContract">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element ref="bons1:NCL_CruiseGroupContractRQ"/>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
      <xsd:element name="Perform_NCL_CruiseGroupContractResponse">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element ref="bons1:NCL_CruiseGroupContractRS"/>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
    </xsd:schema>
  </wsdl:types>
    <wsdl:message name="Perform_NCL_CruiseGroupContractRequestMsg">
    <wsdl:part element="tns:Perform_NCL_CruiseGroupContract" name="Perform_NCL_CruiseGroupContractParameters"/>
  </wsdl:message>
    <wsdl:message name="Perform_NCL_CruiseGroupContractResponseMsg">
    <wsdl:part element="tns:Perform_NCL_CruiseGroupContractResponse" name="Perform_NCL_CruiseGroupContractResult"/>
  </wsdl:message>
    <wsdl:portType name="NCL_CruiseGroupContract_Interface">
    <wsdl:operation name="Perform_NCL_CruiseGroupContract">
      <wsdl:input message="tns:Perform_NCL_CruiseGroupContractRequestMsg" name="Perform_NCL_CruiseGroupContractRequest"/>
      <wsdl:output message="tns:Perform_NCL_CruiseGroupContractResponseMsg" name="Perform_NCL_CruiseGroupContractResponse"/>
    </wsdl:operation>
  </wsdl:portType>
</wsdl:definitions>