<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions name="NCL_CruiseLinkReservation_Interface" targetNamespace="http://NCL_WESB_Shared_Library/NCL_CruiseLinkReservation_Interface" xmlns:bons1="http://nclapi/schemas" xmlns:tns="http://NCL_WESB_Shared_Library/NCL_CruiseLinkReservation_Interface" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <wsdl:types>
    <xsd:schema targetNamespace="http://NCL_WESB_Shared_Library/NCL_CruiseLinkReservation_Interface">
      <xsd:import namespace="http://nclapi/schemas" schemaLocation="NCL_CruiseLinkReservationRS.xsd"/>
      <xsd:import namespace="http://nclapi/schemas" schemaLocation="NCL_CruiseLinkReservationRQ.xsd"/>
      <xsd:element name="Perform_NCL_CruiseLinkReservation">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element ref="bons1:NCL_CruiseLinkReservationRQ"/>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
      <xsd:element name="Perform_NCL_CruiseLinkReservationResponse">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element ref="bons1:NCL_CruiseLinkReservationRS"/>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
    </xsd:schema>
  </wsdl:types>
    <wsdl:message name="Perform_NCL_CruiseLinkReservationRequestMsg">
    <wsdl:part element="tns:Perform_NCL_CruiseLinkReservation" name="Perform_NCL_CruiseLinkReservationParameters"/>
  </wsdl:message>
    <wsdl:message name="Perform_NCL_CruiseLinkReservationResponseMsg">
    <wsdl:part element="tns:Perform_NCL_CruiseLinkReservationResponse" name="Perform_NCL_CruiseLinkReservationResult"/>
  </wsdl:message>
    <wsdl:portType name="NCL_CruiseLinkReservation_Interface">
    <wsdl:operation name="Perform_NCL_CruiseLinkReservation">
      <wsdl:input message="tns:Perform_NCL_CruiseLinkReservationRequestMsg" name="Perform_NCL_CruiseLinkReservationRequest"/>
      <wsdl:output message="tns:Perform_NCL_CruiseLinkReservationResponseMsg" name="Perform_NCL_CruiseLinkReservationResponse"/>
    </wsdl:operation>
  </wsdl:portType>
</wsdl:definitions>