<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions name="NCL_CruiseGroupAccountingWorkup_Interface" targetNamespace="http://NCL_WESB_Shared_Library/NCL_CruiseGroupAccountingWorkup_Interface" xmlns:bons1="http://nclapi/schemas" xmlns:tns="http://NCL_WESB_Shared_Library/NCL_CruiseGroupAccountingWorkup_Interface" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <wsdl:types>
    <xsd:schema targetNamespace="http://NCL_WESB_Shared_Library/NCL_CruiseGroupAccountingWorkup_Interface">
      <xsd:import namespace="http://nclapi/schemas" schemaLocation="NCL_CruiseGroupAccountingWorkupRS.xsd"/>
      <xsd:import namespace="http://nclapi/schemas" schemaLocation="NCL_CruiseGroupAccountingWorkupRQ.xsd"/>
      <xsd:element name="Perform_NCL_CruiseGroupAccountingWorkup">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element ref="bons1:NCL_CruiseGroupAccountingWorkupRQ"/>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
      <xsd:element name="Perform_NCL_CruiseGroupAccountingWorkupResponse">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element ref="bons1:NCL_CruiseGroupAccountingWorkupRS"/>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
    </xsd:schema>
  </wsdl:types>
    <wsdl:message name="Perform_NCL_CruiseGroupAccountingWorkupRequestMsg">
    <wsdl:part element="tns:Perform_NCL_CruiseGroupAccountingWorkup" name="Perform_NCL_CruiseGroupAccountingWorkupParameters"/>
  </wsdl:message>
    <wsdl:message name="Perform_NCL_CruiseGroupAccountingWorkupResponseMsg">
    <wsdl:part element="tns:Perform_NCL_CruiseGroupAccountingWorkupResponse" name="Perform_NCL_CruiseGroupAccountingWorkupResult"/>
  </wsdl:message>
    <wsdl:portType name="NCL_CruiseGroupAccountingWorkup_Interface">
    <wsdl:operation name="Perform_NCL_CruiseGroupAccountingWorkup">
      <wsdl:input message="tns:Perform_NCL_CruiseGroupAccountingWorkupRequestMsg" name="Perform_NCL_CruiseGroupAccountingWorkupRequest"/>
      <wsdl:output message="tns:Perform_NCL_CruiseGroupAccountingWorkupResponseMsg" name="Perform_NCL_CruiseGroupAccountingWorkupResponse"/>
    </wsdl:operation>
  </wsdl:portType>
</wsdl:definitions>