<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions name="NCL_CruiseRetrieveClient_Interface" targetNamespace="http://NCL_WESB_Shared_Library/NCL_CruiseRetrieveClient_Interface" xmlns:bons1="http://nclapi/schemas" xmlns:tns="http://NCL_WESB_Shared_Library/NCL_CruiseRetrieveClient_Interface" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <wsdl:types>
    <xsd:schema targetNamespace="http://NCL_WESB_Shared_Library/NCL_CruiseRetrieveClient_Interface">
      <xsd:import namespace="http://nclapi/schemas" schemaLocation="NCL_CruiseRetrieveClientRS.xsd"/>
      <xsd:import namespace="http://nclapi/schemas" schemaLocation="NCL_CruiseRetrieveClientRQ.xsd"/>
      <xsd:element name="Perform_NCL_CruiseRetrieveClient">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element ref="bons1:NCL_CruiseRetrieveClientRQ"/>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
      <xsd:element name="Perform_NCL_CruiseRetrieveClientResponse">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element ref="bons1:NCL_CruiseRetrieveClientRS"/>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
    </xsd:schema>
  </wsdl:types>
    <wsdl:message name="Perform_NCL_CruiseRetrieveClientRequestMsg">
    <wsdl:part element="tns:Perform_NCL_CruiseRetrieveClient" name="Perform_NCL_CruiseRetrieveClientParameters"/>
  </wsdl:message>
    <wsdl:message name="Perform_NCL_CruiseRetrieveClientResponseMsg">
    <wsdl:part element="tns:Perform_NCL_CruiseRetrieveClientResponse" name="Perform_NCL_CruiseRetrieveClientResult"/>
  </wsdl:message>
    <wsdl:portType name="NCL_CruiseRetrieveClient_Interface">
    <wsdl:operation name="Perform_NCL_CruiseRetrieveClient">
      <wsdl:input message="tns:Perform_NCL_CruiseRetrieveClientRequestMsg" name="Perform_NCL_CruiseRetrieveClientRequest"/>
      <wsdl:output message="tns:Perform_NCL_CruiseRetrieveClientResponseMsg" name="Perform_NCL_CruiseRetrieveClientResponse"/>
    </wsdl:operation>
  </wsdl:portType>
</wsdl:definitions>