<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions name="NCL_LATITUDES_CLIENT_POINTS_TRG_InterfaceExport1_NCL_LATITUDES_CLIENT_POINTS_TRG_InterfaceHttp_Service" targetNamespace="http://NCL_WESB_Shared_Library/NCL_LATITUDES_CLIENT_POINTS_TRG_Interface/Binding" xmlns:Port_0="http://NCL_WESB_Shared_Library/NCL_LATITUDES_CLIENT_POINTS_TRG_Interface" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:this="http://NCL_WESB_Shared_Library/NCL_LATITUDES_CLIENT_POINTS_TRG_Interface/Binding" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:import location="NCL_LATITUDES_CLIENT_POINTS_TRG_Interface.wsdl" namespace="http://NCL_WESB_Shared_Library/NCL_LATITUDES_CLIENT_POINTS_TRG_Interface"/>
  <wsdl:binding name="NCL_LATITUDES_CLIENT_POINTS_TRG_InterfaceExport1_NCL_LATITUDES_CLIENT_POINTS_TRG_InterfaceHttpBinding" type="Port_0:NCL_LATITUDES_CLIENT_POINTS_TRG_Interface">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="Perform_NCL_LATITUDES_CLIENT_POINTS_TRG">
      <soap:operation soapAction=""/>
      <wsdl:input name="Perform_NCL_LATITUDES_CLIENT_POINTS_TRGRequest">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="Perform_NCL_LATITUDES_CLIENT_POINTS_TRGResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="NCL_LATITUDES_CLIENT_POINTS_TRG_InterfaceExport1_NCL_LATITUDES_CLIENT_POINTS_TRG_InterfaceHttpService">
    <wsdl:port binding="this:NCL_LATITUDES_CLIENT_POINTS_TRG_InterfaceExport1_NCL_LATITUDES_CLIENT_POINTS_TRG_InterfaceHttpBinding" name="NCL_LATITUDES_CLIENT_POINTS_TRG_InterfaceExport1_NCL_LATITUDES_CLIENT_POINTS_TRG_InterfaceHttpPort">
      <soap:address location="http://localhost:9080/NCL_LATITUDES_CLIENT_POINTS_TRG_ModuleWeb/sca/NCL_LATITUDES_CLIENT_POINTS_TRG_InterfaceExport1"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>