<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions name="NCL_CruiseUserAuthentication_Interface" targetNamespace="http://NCL_WESB_Shared_Library/NCL_CruiseUserAuthentication_Interface" xmlns:bons1="http://nclapi/schemas" xmlns:tns="http://NCL_WESB_Shared_Library/NCL_CruiseUserAuthentication_Interface" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <wsdl:types>
    <xsd:schema targetNamespace="http://NCL_WESB_Shared_Library/NCL_CruiseUserAuthentication_Interface">
      <xsd:import namespace="http://nclapi/schemas" schemaLocation="NCL_CruiseUserAuthenticationRS.xsd"/>
      <xsd:import namespace="http://nclapi/schemas" schemaLocation="NCL_CruiseUserAuthenticationRQ.xsd"/>
      <xsd:element name="Perform_NCL_CruiseUserAuthentication">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element ref="bons1:NCL_CruiseUserAuthenticationRQ"/>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
      <xsd:element name="Perform_NCL_CruiseUserAuthenticationResponse">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element ref="bons1:NCL_CruiseUserAuthenticationRS"/>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
    </xsd:schema>
  </wsdl:types>
    <wsdl:message name="Perform_NCL_CruiseUserAuthenticationRequestMsg">
    <wsdl:part element="tns:Perform_NCL_CruiseUserAuthentication" name="Perform_NCL_CruiseUserAuthenticationParameters"/>
  </wsdl:message>
    <wsdl:message name="Perform_NCL_CruiseUserAuthenticationResponseMsg">
    <wsdl:part element="tns:Perform_NCL_CruiseUserAuthenticationResponse" name="Perform_NCL_CruiseUserAuthenticationResult"/>
  </wsdl:message>
    <wsdl:portType name="NCL_CruiseUserAuthentication_Interface">
    <wsdl:operation name="Perform_NCL_CruiseUserAuthentication">
      <wsdl:input message="tns:Perform_NCL_CruiseUserAuthenticationRequestMsg" name="Perform_NCL_CruiseUserAuthenticationRequest"/>
      <wsdl:output message="tns:Perform_NCL_CruiseUserAuthenticationResponseMsg" name="Perform_NCL_CruiseUserAuthenticationResponse"/>
    </wsdl:operation>
  </wsdl:portType>
</wsdl:definitions>