<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions name="NCL_CruiseRetrieveAgent_InterfaceExport1_NCL_CruiseRetrieveAgent_InterfaceHttp_Service" targetNamespace="http://NCL_WESB_Shared_Library/NCL_CruiseRetrieveAgent_Interface/Binding" xmlns:Port_0="http://NCL_WESB_Shared_Library/NCL_CruiseRetrieveAgent_Interface" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:this="http://NCL_WESB_Shared_Library/NCL_CruiseRetrieveAgent_Interface/Binding" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:import location="NCL_CruiseRetrieveAgent_Interface.wsdl" namespace="http://NCL_WESB_Shared_Library/NCL_CruiseRetrieveAgent_Interface"/>
  <wsdl:binding name="NCL_CruiseRetrieveAgent_InterfaceExport1_NCL_CruiseRetrieveAgent_InterfaceHttpBinding" type="Port_0:NCL_CruiseRetrieveAgent_Interface">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="Perform_NCL_CruiseRetrieveAgent">
      <soap:operation soapAction=""/>
      <wsdl:input name="Perform_NCL_CruiseRetrieveAgentRequest">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="Perform_NCL_CruiseRetrieveAgentResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="NCL_CruiseRetrieveAgent_InterfaceExport1_NCL_CruiseRetrieveAgent_InterfaceHttpService">
    <wsdl:port binding="this:NCL_CruiseRetrieveAgent_InterfaceExport1_NCL_CruiseRetrieveAgent_InterfaceHttpBinding" name="NCL_CruiseRetrieveAgent_InterfaceExport1_NCL_CruiseRetrieveAgent_InterfaceHttpPort">
      <soap:address location="http://localhost:9080/NCL_CruiseRetrieveAgent_ModuleWeb/sca/NCL_CruiseRetrieveAgent_InterfaceExport1"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>