<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions name="NCL_CruiseRegisterWebAccess_Interface" targetNamespace="http://NCL_WESB_Shared_Library/NCL_CruiseRegisterWebAccess_Interface" xmlns:bons1="http://nclapi/schemas" xmlns:tns="http://NCL_WESB_Shared_Library/NCL_CruiseRegisterWebAccess_Interface" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <wsdl:types>
    <xsd:schema targetNamespace="http://NCL_WESB_Shared_Library/NCL_CruiseRegisterWebAccess_Interface">
      <xsd:import namespace="http://nclapi/schemas" schemaLocation="NCL_CruiseRegisterWebAccessRS.xsd"/>
      <xsd:import namespace="http://nclapi/schemas" schemaLocation="NCL_CruiseRegisterWebAccessRQ.xsd"/>
      <xsd:element name="Perform_NCL_CruiseRegisterWebAccess">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element ref="bons1:NCL_CruiseRegisterWebAccessRQ"/>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
      <xsd:element name="Perform_NCL_CruiseRegisterWebAccessResponse">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element ref="bons1:NCL_CruiseRegisterWebAccessRS"/>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
    </xsd:schema>
  </wsdl:types>
    <wsdl:message name="Perform_NCL_CruiseRegisterWebAccessRequestMsg">
    <wsdl:part element="tns:Perform_NCL_CruiseRegisterWebAccess" name="Perform_NCL_CruiseRegisterWebAccessParameters"/>
  </wsdl:message>
    <wsdl:message name="Perform_NCL_CruiseRegisterWebAccessResponseMsg">
    <wsdl:part element="tns:Perform_NCL_CruiseRegisterWebAccessResponse" name="Perform_NCL_CruiseRegisterWebAccessResult"/>
  </wsdl:message>
    <wsdl:portType name="NCL_CruiseRegisterWebAccess_Interface">
    <wsdl:operation name="Perform_NCL_CruiseRegisterWebAccess">
      <wsdl:input message="tns:Perform_NCL_CruiseRegisterWebAccessRequestMsg" name="Perform_NCL_CruiseRegisterWebAccessRequest"/>
      <wsdl:output message="tns:Perform_NCL_CruiseRegisterWebAccessResponseMsg" name="Perform_NCL_CruiseRegisterWebAccessResponse"/>
    </wsdl:operation>
  </wsdl:portType>
</wsdl:definitions>