<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions name="NCL_CruiseRetrieveAgency_InterfaceExport1_NCL_CruiseRetrieveAgency_InterfaceHttp_Service" targetNamespace="http://NCL_WESB_Shared_Library/NCL_CruiseRetrieveAgency_Interface/Binding" xmlns:Port_0="http://NCL_WESB_Shared_Library/NCL_CruiseRetrieveAgency_Interface" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:this="http://NCL_WESB_Shared_Library/NCL_CruiseRetrieveAgency_Interface/Binding" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:import location="NCL_CruiseRetrieveAgency_Interface.wsdl" namespace="http://NCL_WESB_Shared_Library/NCL_CruiseRetrieveAgency_Interface"/>
  <wsdl:binding name="NCL_CruiseRetrieveAgency_InterfaceExport1_NCL_CruiseRetrieveAgency_InterfaceHttpBinding" type="Port_0:NCL_CruiseRetrieveAgency_Interface">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="Perform_NCL_CruiseRetrieveAgency">
      <soap:operation soapAction=""/>
      <wsdl:input name="Perform_NCL_CruiseRetrieveAgencyRequest">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="Perform_NCL_CruiseRetrieveAgencyResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="NCL_CruiseRetrieveAgency_InterfaceExport1_NCL_CruiseRetrieveAgency_InterfaceHttpService">
    <wsdl:port binding="this:NCL_CruiseRetrieveAgency_InterfaceExport1_NCL_CruiseRetrieveAgency_InterfaceHttpBinding" name="NCL_CruiseRetrieveAgency_InterfaceExport1_NCL_CruiseRetrieveAgency_InterfaceHttpPort">
      <soap:address location="http://localhost:9080/NCL_CruiseRetrieveAgency_ModuleWeb/sca/NCL_CruiseRetrieveAgency_InterfaceExport1"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>