<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions name="NCL_CruiseRegisterWebAccess_InterfaceExport1_NCL_CruiseRegisterWebAccess_InterfaceHttp_Service" targetNamespace="http://NCL_WESB_Shared_Library/NCL_CruiseRegisterWebAccess_Interface/Binding" xmlns:Port_0="http://NCL_WESB_Shared_Library/NCL_CruiseRegisterWebAccess_Interface" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:this="http://NCL_WESB_Shared_Library/NCL_CruiseRegisterWebAccess_Interface/Binding" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:import location="NCL_CruiseRegisterWebAccess_Interface.wsdl" namespace="http://NCL_WESB_Shared_Library/NCL_CruiseRegisterWebAccess_Interface"/>
  <wsdl:binding name="NCL_CruiseRegisterWebAccess_InterfaceExport1_NCL_CruiseRegisterWebAccess_InterfaceHttpBinding" type="Port_0:NCL_CruiseRegisterWebAccess_Interface">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="Perform_NCL_CruiseRegisterWebAccess">
      <soap:operation soapAction=""/>
      <wsdl:input name="Perform_NCL_CruiseRegisterWebAccessRequest">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="Perform_NCL_CruiseRegisterWebAccessResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="NCL_CruiseRegisterWebAccess_InterfaceExport1_NCL_CruiseRegisterWebAccess_InterfaceHttpService">
    <wsdl:port binding="this:NCL_CruiseRegisterWebAccess_InterfaceExport1_NCL_CruiseRegisterWebAccess_InterfaceHttpBinding" name="NCL_CruiseRegisterWebAccess_InterfaceExport1_NCL_CruiseRegisterWebAccess_InterfaceHttpPort">
      <soap:address location="http://localhost:9080/NCL_CruiseRegisterWebAccess_ModuleWeb/sca/NCL_CruiseRegisterWebAccess_InterfaceExport1"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>