<?xml version="1.0" encoding="UTF-8"?>
<!-- @generated mapFile="xslt/XSLTransformation1_req_2.map" md5sum="472ee5c7459c1cdaaa3c783bea7de64d" version="7.6.100" -->
<!--
*****************************************************************************
*   This file has been generated by the IBM XML Mapping Editor.
*
*   Mapping file:		XSLTransformation1_req_2.map
*   Map declaration(s):	XSLTransformation1_req_2
*   Input file(s):		smo://smo/name%3Dwsdl-primary/correlationContext%3D%257Bhttp%253A%252F%252FE-Mail_Generic%257Dsever/message%3D%257Bhttp%253A%252F%252FE-Mail_Generic%252FE-Mail_Interface%257DSend_Email1RequestMsg/xpath%3D%252F/smo.xsd
*   Output file(s):		smo://smo/name%3Dwsdl-primary/correlationContext%3D%257Bhttp%253A%252F%252FE-Mail_Generic%257Dsever/message%3D%257Bhttp%253A%252F%252FE-Mail_Generic%252FE-Mail_Interface%257DSend_Email1RequestMsg/xpath%3D%252F/smo.xsd
*
*   Note: Do not modify the contents of this file as it is overwritten
*         each time the mapping model is updated.
*****************************************************************************
-->
<xsl:stylesheet
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xalan="http://xml.apache.org/xslt"
    xmlns:str="http://exslt.org/strings"
    xmlns:set="http://exslt.org/sets"
    xmlns:math="http://exslt.org/math"
    xmlns:fn="http://www.w3.org/2005/xpath-functions"
    xmlns:regexp="http://exslt.org/regular-expressions"
    xmlns:dyn="http://exslt.org/dynamic"
    xmlns:dp="http://www.datapower.com/extensions"
    xmlns:exsl="http://exslt.org/common"
    xmlns:date="http://exslt.org/dates-and-times"
    xmlns:io="http://www.w3.org/2003/05/soap-envelope"
    xmlns:io3="http://www.ibm.com/xmlns/prod/websphere/mq/sca/6.0.0"
    xmlns:io2="http://www.ibm.com/websphere/sibx/smo/v6.0.1"
    xmlns:io4="http://schemas.xmlsoap.org/ws/2004/08/addressing"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:io5="http://www.ibm.com/xmlns/prod/websphere/http/sca/6.1.0"
    xmlns:io7="wsdl.http://E-Mail_Generic/E-Mail_Interface"
    xmlns:io6="http://E-Mail_Generic"
    xmlns:xs4xs="http://www.w3.org/2001/XMLSchema"
    xmlns:io8="http://www.w3.org/2005/08/addressing"
    xmlns:io9="http://E-Mail_Generic/E-Mail_Interface"
    xmlns:map="http://E-Mail_Generic/xslt/XSLTransformation1_req_2"
    xmlns:msl="http://www.ibm.com/xmlmap"
    exclude-result-prefixes="str set math fn regexp dyn dp exsl date map xalan msl"
    version="1.0">
  <xsl:output method="xml" encoding="UTF-8" indent="no"/>

  <!-- root wrapper template  -->
  <xsl:template match="/">
    <xsl:choose>
      <xsl:when test="msl:datamap">
        <msl:datamap>
          <xsl:element name="dataObject">
            <xsl:attribute name="xsi:type">
              <xsl:value-of select="'io2:ServiceMessageObject'"/>
            </xsl:attribute>
            <xsl:call-template name="map:XSLTransformation1_req_22">
              <xsl:with-param name="smo" select="msl:datamap/dataObject[1]"/>
            </xsl:call-template>
          </xsl:element>
        </msl:datamap>
      </xsl:when>
      <xsl:otherwise>
        <xsl:apply-templates select="io2:smo" mode="map:XSLTransformation1_req_2"/>
      </xsl:otherwise>
    </xsl:choose>
  </xsl:template>

  <!-- This rule represents an element mapping: "io2:smo" to "io2:smo".  -->
  <xsl:template match="io2:smo"  mode="map:XSLTransformation1_req_2">
    <io2:smo>
      <!-- a structural mapping: "context"(<Anonymous>) to "context"(<Anonymous>) -->
      <xsl:copy-of select="context"/>
      <body>
        <xsl:attribute name="xsi:type">
          <xsl:value-of select="'io7:Send_Email1RequestMsg'"/>
        </xsl:attribute>
        <io9:Send_Email1>
          <!-- a simple mapping with no associated source:  to "To"(string) -->
          <xsl:element name="To">
            <xsl:text>lrohr@ncl.com</xsl:text>
          </xsl:element>
          <!-- a simple data mapping: "context/correlation/location"(string) to "Subject"(string) -->
          <xsl:element name="Subject">
            <xsl:value-of select="context/correlation/location"/>
          </xsl:element>
          <!-- a simple data mapping: "body/io9:Send_Email1/Content"(string) to "Content"(string) -->
          <xsl:choose>
            <xsl:when test="normalize-space(body/io9:Send_Email1/Content)">
              <xsl:element name="Content">
                <xsl:value-of select="body/io9:Send_Email1/Content"/>
              </xsl:element>
            </xsl:when>
            <xsl:otherwise>
              <Content xsi:nil="true"/>
            </xsl:otherwise>
          </xsl:choose>
          <!-- a simple data mapping: "body/io9:Send_Email1/Severity"(string) to "Severity"(string) -->
          <xsl:choose>
            <xsl:when test="normalize-space(body/io9:Send_Email1/Severity)">
              <xsl:element name="Severity">
                <xsl:value-of select="body/io9:Send_Email1/Severity"/>
              </xsl:element>
            </xsl:when>
            <xsl:otherwise>
              <Severity xsi:nil="true"/>
            </xsl:otherwise>
          </xsl:choose>
        </io9:Send_Email1>
      </body>
    </io2:smo>
  </xsl:template>

  <!-- This rule represents a type mapping: "io2:smo" to "io2:smo".  -->
  <xsl:template name="map:XSLTransformation1_req_22">
    <xsl:param name="smo"/>
    <!-- a structural mapping: "$smo/context"(<Anonymous>) to "context"(<Anonymous>) -->
    <xsl:copy-of select="$smo/context"/>
    <body>
      <xsl:attribute name="xsi:type">
        <xsl:value-of select="'io7:Send_Email1RequestMsg'"/>
      </xsl:attribute>
      <io9:Send_Email1>
        <!-- a simple mapping with no associated source:  to "To"(string) -->
        <xsl:element name="To">
          <xsl:text>lrohr@ncl.com</xsl:text>
        </xsl:element>
        <!-- a simple data mapping: "$smo/context/correlation/location"(string) to "Subject"(string) -->
        <xsl:element name="Subject">
          <xsl:value-of select="$smo/context/correlation/location"/>
        </xsl:element>
        <!-- a simple data mapping: "$smo/body/io9:Send_Email1/Content"(string) to "Content"(string) -->
        <xsl:choose>
          <xsl:when test="normalize-space($smo/body/io9:Send_Email1/Content)">
            <xsl:element name="Content">
              <xsl:value-of select="$smo/body/io9:Send_Email1/Content"/>
            </xsl:element>
          </xsl:when>
          <xsl:otherwise>
            <Content xsi:nil="true"/>
          </xsl:otherwise>
        </xsl:choose>
        <!-- a simple data mapping: "$smo/body/io9:Send_Email1/Severity"(string) to "Severity"(string) -->
        <xsl:choose>
          <xsl:when test="normalize-space($smo/body/io9:Send_Email1/Severity)">
            <xsl:element name="Severity">
              <xsl:value-of select="$smo/body/io9:Send_Email1/Severity"/>
            </xsl:element>
          </xsl:when>
          <xsl:otherwise>
            <Severity xsi:nil="true"/>
          </xsl:otherwise>
        </xsl:choose>
      </io9:Send_Email1>
    </body>
  </xsl:template>

  <!-- *****************    Utility Templates    ******************  -->
  <!-- copy the namespace declarations from the source to the target -->
  <xsl:template name="copyNamespaceDeclarations">
    <xsl:param name="root"/>
    <xsl:for-each select="$root/namespace::*[not(name() = '')]">
      <xsl:copy/>
    </xsl:for-each>
  </xsl:template>
</xsl:stylesheet>
