<?xml version="1.0" encoding="UTF-8"?>
<!-- @generated mapFile="xslt/Request_To_UPDATE_map.map" md5sum="8629983826454685b97b8b27b73b4f25" version="7.5.100" -->
<!--
*****************************************************************************
*   This file has been generated by the IBM XML Mapping Editor.
*
*   Mapping file:		Request_To_UPDATE_map.map
*   Map declaration(s):	Request_To_UPDATE_map
*   Input file(s):		smo://smo/name%3Dwsdl-primary/message%3D%257Bhttp%253A%252F%252FTP_Logger%252FTP_Interface%257DTP_InsertUpdateRequestMsg/xpath%3D%252F/smo.xsd
*   Output file(s):		smo://smo/name%3Dwsdl-primary/message%3D%257Bhttp%253A%252F%252FTP_Logger%252FJDBCOutboundInterface%257DexecuteNclseaNcl_Esb_Update_Tp_LogBGRequestMsg/xpath%3D%252F/smo.xsd
*
*   Note: Do not modify the contents of this file as it is overwritten
*         each time the mapping model is updated.
*****************************************************************************
-->
<xsl:stylesheet
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xalan="http://xml.apache.org/xslt"
    xmlns:str="http://exslt.org/strings"
    xmlns:set="http://exslt.org/sets"
    xmlns:math="http://exslt.org/math"
    xmlns:fn="http://www.w3.org/2005/xpath-functions"
    xmlns:regexp="http://exslt.org/regular-expressions"
    xmlns:dyn="http://exslt.org/dynamic"
    xmlns:dp="http://www.datapower.com/extensions"
    xmlns:exsl="http://exslt.org/common"
    xmlns:date="http://exslt.org/dates-and-times"
    xmlns:in="http://TP_Logger/TP_Interface"
    xmlns:in2="wsdl.http://TP_Logger/TP_Interface"
    xmlns:out="http://TP_Logger/JDBCOutboundInterface"
    xmlns:io="http://www.w3.org/2003/05/soap-envelope"
    xmlns:io2="http://www.ibm.com/websphere/sibx/smo/v6.0.1"
    xmlns:out2="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/nclseancl_esb_update_tp_logbg"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:out3="wsdl.http://TP_Logger/JDBCOutboundInterface"
    xmlns:out4="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/nclseancl_esb_insert_tp_log"
    xmlns:io3="http://www.ibm.com/xmlns/prod/websphere/mq/sca/6.0.0"
    xmlns:out5="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/nclseancl_esb_insert_tp_logbg"
    xmlns:io4="http://schemas.xmlsoap.org/ws/2004/08/addressing"
    xmlns:io5="http://www.ibm.com/xmlns/prod/websphere/http/sca/6.1.0"
    xmlns:out6="http://www.ibm.com/xmlns/prod/websphere/bo/6.0.0"
    xmlns:xs4xs="http://www.w3.org/2001/XMLSchema"
    xmlns:io6="http://www.w3.org/2005/08/addressing"
    xmlns:out7="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/nclseancl_esb_update_tp_log"
    xmlns:map="http://TP_Logger/xslt/Request_To_UPDATE_map"
    xmlns:msl="http://www.ibm.com/xmlmap"
    exclude-result-prefixes="in in2 str set math fn regexp dyn dp exsl date map xalan msl"
    version="1.0">
  <xsl:output method="xml" encoding="UTF-8" indent="no"/>

  <!-- root wrapper template  -->
  <xsl:template match="/">
    <xsl:choose>
      <xsl:when test="msl:datamap">
        <msl:datamap>
          <xsl:element name="dataObject">
            <xsl:attribute name="xsi:type">
              <xsl:value-of select="'io2:ServiceMessageObject'"/>
            </xsl:attribute>
            <xsl:call-template name="map:Request_To_UPDATE_map2">
              <xsl:with-param name="smo" select="msl:datamap/dataObject[1]"/>
            </xsl:call-template>
          </xsl:element>
        </msl:datamap>
      </xsl:when>
      <xsl:otherwise>
        <xsl:apply-templates select="io2:smo" mode="map:Request_To_UPDATE_map"/>
      </xsl:otherwise>
    </xsl:choose>
  </xsl:template>

  <!-- This rule represents an element mapping: "io2:smo" to "io2:smo".  -->
  <xsl:template match="io2:smo"  mode="map:Request_To_UPDATE_map">
    <io2:smo>
      <body>
        <xsl:attribute name="xsi:type">
          <xsl:value-of select="'out3:executeNclseaNcl_Esb_Update_Tp_LogBGRequestMsg'"/>
        </xsl:attribute>
        <out:executeNclseaNcl_Esb_Update_Tp_LogBG>
          <out:executeNclseaNcl_Esb_Update_Tp_LogBGInput>
            <NclseaNcl_Esb_Update_Tp_Log>
              <!-- a simple data mapping: "body/in:TP_InsertUpdate/RESPONSE_TS"(Date_Format) to "response_ts"(string) -->
              <xsl:if test="body/in:TP_InsertUpdate/RESPONSE_TS">
                <xsl:choose>
                  <xsl:when test="normalize-space(body/in:TP_InsertUpdate/RESPONSE_TS)">
                    <xsl:element name="response_ts">
                      <xsl:value-of select="body/in:TP_InsertUpdate/RESPONSE_TS"/>
                    </xsl:element>
                  </xsl:when>
                  <xsl:otherwise>
                    <response_ts xsi:nil="true"/>
                  </xsl:otherwise>
                </xsl:choose>
              </xsl:if>
              <!-- a simple data mapping: "body/in:TP_InsertUpdate/RESPONSE_TYPE_CD"(string) to "response_type"(string) -->
              <xsl:if test="body/in:TP_InsertUpdate/RESPONSE_TYPE_CD">
                <xsl:choose>
                  <xsl:when test="normalize-space(body/in:TP_InsertUpdate/RESPONSE_TYPE_CD)">
                    <xsl:element name="response_type">
                      <xsl:value-of select="body/in:TP_InsertUpdate/RESPONSE_TYPE_CD"/>
                    </xsl:element>
                  </xsl:when>
                  <xsl:otherwise>
                    <response_type xsi:nil="true"/>
                  </xsl:otherwise>
                </xsl:choose>
              </xsl:if>
              <!-- a simple data mapping: "body/in:TP_InsertUpdate/XML"(string) to "response_msg"(string) -->
              <xsl:if test="body/in:TP_InsertUpdate/XML">
                <xsl:choose>
                  <xsl:when test="normalize-space(body/in:TP_InsertUpdate/XML)">
                    <xsl:element name="response_msg">
                      <xsl:value-of select="body/in:TP_InsertUpdate/XML"/>
                    </xsl:element>
                  </xsl:when>
                  <xsl:otherwise>
                    <response_msg xsi:nil="true"/>
                  </xsl:otherwise>
                </xsl:choose>
              </xsl:if>
              <!-- a simple data mapping: "body/in:TP_InsertUpdate/RECORD_ID"(string) to "record_id"(string) -->
              <xsl:if test="body/in:TP_InsertUpdate/RECORD_ID">
                <xsl:choose>
                  <xsl:when test="normalize-space(body/in:TP_InsertUpdate/RECORD_ID)">
                    <xsl:element name="record_id">
                      <xsl:value-of select="body/in:TP_InsertUpdate/RECORD_ID"/>
                    </xsl:element>
                  </xsl:when>
                  <xsl:otherwise>
                    <record_id xsi:nil="true"/>
                  </xsl:otherwise>
                </xsl:choose>
              </xsl:if>
            </NclseaNcl_Esb_Update_Tp_Log>
          </out:executeNclseaNcl_Esb_Update_Tp_LogBGInput>
        </out:executeNclseaNcl_Esb_Update_Tp_LogBG>
      </body>
    </io2:smo>
  </xsl:template>

  <!-- This rule represents a type mapping: "io2:smo" to "io2:smo".  -->
  <xsl:template name="map:Request_To_UPDATE_map2">
    <xsl:param name="smo"/>
    <body>
      <xsl:attribute name="xsi:type">
        <xsl:value-of select="'out3:executeNclseaNcl_Esb_Update_Tp_LogBGRequestMsg'"/>
      </xsl:attribute>
      <out:executeNclseaNcl_Esb_Update_Tp_LogBG>
        <out:executeNclseaNcl_Esb_Update_Tp_LogBGInput>
          <NclseaNcl_Esb_Update_Tp_Log>
            <!-- a simple data mapping: "$smo/body/in:TP_InsertUpdate/RESPONSE_TS"(Date_Format) to "response_ts"(string) -->
            <xsl:if test="$smo/body/in:TP_InsertUpdate/RESPONSE_TS">
              <xsl:choose>
                <xsl:when test="normalize-space($smo/body/in:TP_InsertUpdate/RESPONSE_TS)">
                  <xsl:element name="response_ts">
                    <xsl:value-of select="$smo/body/in:TP_InsertUpdate/RESPONSE_TS"/>
                  </xsl:element>
                </xsl:when>
                <xsl:otherwise>
                  <response_ts xsi:nil="true"/>
                </xsl:otherwise>
              </xsl:choose>
            </xsl:if>
            <!-- a simple data mapping: "$smo/body/in:TP_InsertUpdate/RESPONSE_TYPE_CD"(string) to "response_type"(string) -->
            <xsl:if test="$smo/body/in:TP_InsertUpdate/RESPONSE_TYPE_CD">
              <xsl:choose>
                <xsl:when test="normalize-space($smo/body/in:TP_InsertUpdate/RESPONSE_TYPE_CD)">
                  <xsl:element name="response_type">
                    <xsl:value-of select="$smo/body/in:TP_InsertUpdate/RESPONSE_TYPE_CD"/>
                  </xsl:element>
                </xsl:when>
                <xsl:otherwise>
                  <response_type xsi:nil="true"/>
                </xsl:otherwise>
              </xsl:choose>
            </xsl:if>
            <!-- a simple data mapping: "$smo/body/in:TP_InsertUpdate/XML"(string) to "response_msg"(string) -->
            <xsl:if test="$smo/body/in:TP_InsertUpdate/XML">
              <xsl:choose>
                <xsl:when test="normalize-space($smo/body/in:TP_InsertUpdate/XML)">
                  <xsl:element name="response_msg">
                    <xsl:value-of select="$smo/body/in:TP_InsertUpdate/XML"/>
                  </xsl:element>
                </xsl:when>
                <xsl:otherwise>
                  <response_msg xsi:nil="true"/>
                </xsl:otherwise>
              </xsl:choose>
            </xsl:if>
            <!-- a simple data mapping: "$smo/body/in:TP_InsertUpdate/RECORD_ID"(string) to "record_id"(string) -->
            <xsl:if test="$smo/body/in:TP_InsertUpdate/RECORD_ID">
              <xsl:choose>
                <xsl:when test="normalize-space($smo/body/in:TP_InsertUpdate/RECORD_ID)">
                  <xsl:element name="record_id">
                    <xsl:value-of select="$smo/body/in:TP_InsertUpdate/RECORD_ID"/>
                  </xsl:element>
                </xsl:when>
                <xsl:otherwise>
                  <record_id xsi:nil="true"/>
                </xsl:otherwise>
              </xsl:choose>
            </xsl:if>
          </NclseaNcl_Esb_Update_Tp_Log>
        </out:executeNclseaNcl_Esb_Update_Tp_LogBGInput>
      </out:executeNclseaNcl_Esb_Update_Tp_LogBG>
    </body>
  </xsl:template>

  <!-- *****************    Utility Templates    ******************  -->
  <!-- copy the namespace declarations from the source to the target -->
  <xsl:template name="copyNamespaceDeclarations">
    <xsl:param name="root"/>
    <xsl:for-each select="$root/namespace::*[not(name() = '')]">
      <xsl:copy/>
    </xsl:for-each>
  </xsl:template>
</xsl:stylesheet>
