<?xml version="1.0" encoding="UTF-8"?>
<!-- @generated mapFile="xslt/xsltLoadDecrypt.map" md5sum="1ff6cc1e9ef1cf2616b8a58b59f4f36e" version="7.6.100" -->
<!--
*****************************************************************************
*   This file has been generated by the IBM XML Mapping Editor.
*
*   Mapping file:		xsltLoadDecrypt.map
*   Map declaration(s):	xsltLoadDecrypt
*   Input file(s):		smo://smo/name%3Dwsdl-primary/correlationContext%3D%257Bhttp%253A%252F%252FNCL_CruiseRetrieveAgent_Module%257DappContext/message%3D%257Bhttp%253A%252F%252FNCL_WESB_Shared_Library%252FNCL_CruiseRetrieveAgent_Interface%257DPerform_NCL_CruiseRetrieveAgentResponseMsg/xpath%3D%252F/smo.xsd
*   Output file(s):		smo://smo/name%3Dwsdl-primary/correlationContext%3D%257Bhttp%253A%252F%252FNCL_CruiseRetrieveAgent_Module%257DappContext/message%3D%257Bhttp%253A%252F%252FNCL_WESB_Shared_Library%252FEncrypt_Decrypt_Interface%257DprocessEncryptDecryptRequest/xpath%3D%252F/smo.xsd
*
*   Note: Do not modify the contents of this file as it is overwritten
*         each time the mapping model is updated.
*****************************************************************************
-->
<xsl:stylesheet
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xalan="http://xml.apache.org/xslt"
    xmlns:str="http://exslt.org/strings"
    xmlns:set="http://exslt.org/sets"
    xmlns:math="http://exslt.org/math"
    xmlns:fn="http://www.w3.org/2005/xpath-functions"
    xmlns:regexp="http://exslt.org/regular-expressions"
    xmlns:dyn="http://exslt.org/dynamic"
    xmlns:dp="http://www.datapower.com/extensions"
    xmlns:exsl="http://exslt.org/common"
    xmlns:date="http://exslt.org/dates-and-times"
    xmlns:in="http://NCL_WESB_Shared_Library/NCL_CruiseRetrieveAgent_Interface"
    xmlns:in2="wsdl.http://NCL_WESB_Shared_Library/NCL_CruiseRetrieveAgent_Interface"
    xmlns:out="wsdl.http://NCL_WESB_Shared_Library/Encrypt_Decrypt_Interface"
    xmlns:io="http://NCL_CruiseRetrieveAgent_Module"
    xmlns:io2="http://www.w3.org/2003/05/soap-envelope"
    xmlns:io4="http://www.ibm.com/xmlns/prod/websphere/mq/sca/6.0.0"
    xmlns:io3="http://www.ibm.com/websphere/sibx/smo/v6.0.1"
    xmlns:io5="http://schemas.xmlsoap.org/ws/2004/08/addressing"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:out2="http://NCL_WESB_Shared_Library/Encrypt_Decrypt_Interface"
    xmlns:io7="http://www.ibm.com/xmlns/prod/websphere/http/sca/6.1.0"
    xmlns:io6="http://nclapi/schemas"
    xmlns:xs4xs="http://www.w3.org/2001/XMLSchema"
    xmlns:io8="http://www.w3.org/2005/08/addressing"
    xmlns:map="http://NCL_CruiseRetrieveAgent_Module/xslt/xsltLoadDecrypt"
    xmlns:msl="http://www.ibm.com/xmlmap"
    exclude-result-prefixes="in in2 str set math fn regexp dyn dp exsl date map xalan msl"
    version="1.0">
  <xsl:output method="xml" encoding="UTF-8" indent="no"/>

  <!-- root wrapper template  -->
  <xsl:template match="/">
    <xsl:choose>
      <xsl:when test="msl:datamap">
        <msl:datamap>
          <xsl:element name="dataObject">
            <xsl:attribute name="xsi:type">
              <xsl:value-of select="'io3:ServiceMessageObject'"/>
            </xsl:attribute>
            <xsl:call-template name="map:xsltLoadDecrypt2">
              <xsl:with-param name="smo" select="msl:datamap/dataObject[1]"/>
            </xsl:call-template>
          </xsl:element>
        </msl:datamap>
      </xsl:when>
      <xsl:otherwise>
        <xsl:apply-templates select="io3:smo" mode="map:xsltLoadDecrypt"/>
      </xsl:otherwise>
    </xsl:choose>
  </xsl:template>

  <!-- This rule represents an element mapping: "io3:smo" to "io3:smo".  -->
  <xsl:template match="io3:smo"  mode="map:xsltLoadDecrypt">
    <io3:smo>
      <context>
        <correlation>
          <xsl:attribute name="xsi:type">
            <xsl:value-of select="'io:appContext'"/>
          </xsl:attribute>
          <!-- a simple data mapping: "context/correlation/logId"(string) to "logId"(string) -->
          <xsl:if test="context/correlation/logId">
            <xsl:element name="logId">
              <xsl:value-of select="context/correlation/logId"/>
            </xsl:element>
          </xsl:if>
          <!-- a structural mapping: "context/correlation/io6:NCL_CruiseRetrieveAgentRQ"(<Anonymous>) to "io6:NCL_CruiseRetrieveAgentRQ"(<Anonymous>) -->
          <xsl:if test="context/correlation/io6:NCL_CruiseRetrieveAgentRQ">
            <xsl:copy-of select="context/correlation/io6:NCL_CruiseRetrieveAgentRQ"/>
          </xsl:if>
          <!-- a structural mapping: "context/correlation/Agent_work_agency"(<Anonymous>) to "Agent_work_agency"(<Anonymous>) -->
          <xsl:if test="context/correlation/Agent_work_agency">
            <xsl:copy-of select="context/correlation/Agent_work_agency"/>
          </xsl:if>
          <!-- a structural mapping: "context/correlation/agent_work_getAgent"(<Anonymous>) to "agent_work_getAgent"(<Anonymous>) -->
          <xsl:if test="context/correlation/agent_work_getAgent">
            <xsl:copy-of select="context/correlation/agent_work_getAgent"/>
          </xsl:if>
        </correlation>
      </context>
      <xsl:element name="body">
        <xsl:attribute name="xsi:type">
          <xsl:value-of select="'out:processEncryptDecryptRequest'"/>
        </xsl:attribute>
        <xsl:element name="out2:processEncryptDecryptRequest">
          <xsl:element name="Encrypt_Decrypt">
            <!-- a simple mapping with no associated source:  to "Action"(string) -->
            <xsl:element name="Action">
              <xsl:text>DECRYPT</xsl:text>
            </xsl:element>
            <!-- a simple data mapping: "context/correlation/agent_work_getAgent/spGetAgentInfo[1]/P_CURSOR[1]/WEB_PASSWORD"(string) to "EncryptString"(string) -->
            <xsl:if test="context/correlation/agent_work_getAgent/spGetAgentInfo[1]/P_CURSOR[1]/WEB_PASSWORD">
              <xsl:element name="EncryptString">
                <xsl:value-of select="context/correlation/agent_work_getAgent/spGetAgentInfo[1]/P_CURSOR[1]/WEB_PASSWORD"/>
              </xsl:element>
            </xsl:if>
          </xsl:element>
        </xsl:element>
      </xsl:element>
    </io3:smo>
  </xsl:template>

  <!-- This rule represents a type mapping: "io3:smo" to "io3:smo".  -->
  <xsl:template name="map:xsltLoadDecrypt2">
    <xsl:param name="smo"/>
    <context>
      <correlation>
        <xsl:attribute name="xsi:type">
          <xsl:value-of select="'io:appContext'"/>
        </xsl:attribute>
        <!-- a simple data mapping: "$smo/context/correlation/logId"(string) to "logId"(string) -->
        <xsl:if test="$smo/context/correlation/logId">
          <xsl:element name="logId">
            <xsl:value-of select="$smo/context/correlation/logId"/>
          </xsl:element>
        </xsl:if>
        <!-- a structural mapping: "$smo/context/correlation/io6:NCL_CruiseRetrieveAgentRQ"(<Anonymous>) to "io6:NCL_CruiseRetrieveAgentRQ"(<Anonymous>) -->
        <xsl:if test="$smo/context/correlation/io6:NCL_CruiseRetrieveAgentRQ">
          <xsl:copy-of select="$smo/context/correlation/io6:NCL_CruiseRetrieveAgentRQ"/>
        </xsl:if>
        <!-- a structural mapping: "$smo/context/correlation/Agent_work_agency"(<Anonymous>) to "Agent_work_agency"(<Anonymous>) -->
        <xsl:if test="$smo/context/correlation/Agent_work_agency">
          <xsl:copy-of select="$smo/context/correlation/Agent_work_agency"/>
        </xsl:if>
        <!-- a structural mapping: "$smo/context/correlation/agent_work_getAgent"(<Anonymous>) to "agent_work_getAgent"(<Anonymous>) -->
        <xsl:if test="$smo/context/correlation/agent_work_getAgent">
          <xsl:copy-of select="$smo/context/correlation/agent_work_getAgent"/>
        </xsl:if>
      </correlation>
    </context>
    <xsl:element name="body">
      <xsl:attribute name="xsi:type">
        <xsl:value-of select="'out:processEncryptDecryptRequest'"/>
      </xsl:attribute>
      <xsl:element name="out2:processEncryptDecryptRequest">
        <xsl:element name="Encrypt_Decrypt">
          <!-- a simple mapping with no associated source:  to "Action"(string) -->
          <xsl:element name="Action">
            <xsl:text>DECRYPT</xsl:text>
          </xsl:element>
          <!-- a simple data mapping: "$smo/context/correlation/agent_work_getAgent/spGetAgentInfo[1]/P_CURSOR[1]/WEB_PASSWORD"(string) to "EncryptString"(string) -->
          <xsl:if test="$smo/context/correlation/agent_work_getAgent/spGetAgentInfo[1]/P_CURSOR[1]/WEB_PASSWORD">
            <xsl:element name="EncryptString">
              <xsl:value-of select="$smo/context/correlation/agent_work_getAgent/spGetAgentInfo[1]/P_CURSOR[1]/WEB_PASSWORD"/>
            </xsl:element>
          </xsl:if>
        </xsl:element>
      </xsl:element>
    </xsl:element>
  </xsl:template>

  <!-- *****************    Utility Templates    ******************  -->
  <!-- copy the namespace declarations from the source to the target -->
  <xsl:template name="copyNamespaceDeclarations">
    <xsl:param name="root"/>
    <xsl:for-each select="$root/namespace::*[not(name() = '')]">
      <xsl:copy/>
    </xsl:for-each>
  </xsl:template>
</xsl:stylesheet>
