<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions name="FlatFileExport1" targetNamespace="http://Ps_Maps/FlatFileExport1" xmlns:tns="http://Ps_Maps/FlatFileExport1" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <wsdl:types>
    <xsd:schema elementFormDefault="qualified" targetNamespace="http://Ps_Maps/FlatFileExport1">
      <xsd:import schemaLocation="PS_APPDATA1.xsd"/>
      <xsd:element name="emit">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element ref="NCL_PS_APPDATA1"/>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="emitRequestMsg">
    <wsdl:part element="tns:emit" name="emitParameters"/>
  </wsdl:message>
  <wsdl:portType name="FlatFileExport1">
    <wsdl:operation name="emit">
      <wsdl:input message="tns:emitRequestMsg" name="emitRequest"/>
    </wsdl:operation>
  </wsdl:portType>
</wsdl:definitions>