<?xml version="1.0" encoding="UTF-8"?>
<!-- @generated mapFile="xslt/UpdateRequesMsgLog_req_1.map" md5sum="5722d86e0d5873f688c82a079490527d" version="7.6.100" -->
<!--
*****************************************************************************
*   This file has been generated by the IBM XML Mapping Editor.
*
*   Mapping file:		UpdateRequesMsgLog_req_1.map
*   Map declaration(s):	UpdateRequesMsgLog_req_1
*   Input file(s):		smo://smo/name%3Dwsdl-primary/transientContext%3D%257Bhttp%253A%252F%252FNCLFuseBoxMediation%257DFuseBoxMediationSharedCtx/message%3D%257Bhttp%253A%252F%252FFuseBoxLib%252FFuseBoxCredCardProvider%257DprocessCardInfoRequestMsg/xpath%3D%252F/smo.xsd
*   Output file(s):		smo://smo/name%3Dwsdl-primary/transientContext%3D%257Bhttp%253A%252F%252FNCLFuseBoxMediation%257DFuseBoxMediationSharedCtx/message%3D%257Bhttp%253A%252F%252FNCLFuseBoxMediation%252FUpdateRequestMsgSQL%257DexecuteUpdateRequestMsgSQLBGRequestMsg/xpath%3D%252F/smo.xsd
*   XSLT import(s):   	UpdateRequesMsgLog_req_1_custom.xsl
*
*   Note: Do not modify the contents of this file as it is overwritten
*         each time the mapping model is updated.
*****************************************************************************
-->
<xsl:stylesheet
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xalan="http://xml.apache.org/xslt"
    xmlns:str="http://exslt.org/strings"
    xmlns:set="http://exslt.org/sets"
    xmlns:math="http://exslt.org/math"
    xmlns:fn="http://www.w3.org/2005/xpath-functions"
    xmlns:regexp="http://exslt.org/regular-expressions"
    xmlns:dyn="http://exslt.org/dynamic"
    xmlns:dp="http://www.datapower.com/extensions"
    xmlns:exsl="http://exslt.org/common"
    xmlns:date="http://exslt.org/dates-and-times"
    xmlns:in="http://FuseBoxLib/FuseBoxCredCardProvider"
    xmlns:in2="wsdl.http://FuseBoxLib/FuseBoxCredCardProvider"
    xmlns:out="wsdl.http://NCLFuseBoxMediation/UpdateRequestMsgSQL"
    xmlns:io="http://www.w3.org/2003/05/soap-envelope"
    xmlns:io2="http://www.ibm.com/websphere/sibx/smo/v6.0.1"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:out2="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/updaterequestmsgsql"
    xmlns:out3="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/updaterequestmsgsqlbg"
    xmlns:io3="http://www.ibm.com/xmlns/prod/websphere/mq/sca/6.0.0"
    xmlns:io4="http://NCLFuseBoxMediation"
    xmlns:io5="http://schemas.xmlsoap.org/ws/2004/08/addressing"
    xmlns:out4="http://NCLFuseBoxMediation/UpdateRequestMsgSQL"
    xmlns:io6="http://www.ibm.com/xmlns/prod/websphere/http/sca/6.1.0"
    xmlns:out5="http://www.ibm.com/xmlns/prod/websphere/bo/6.0.0"
    xmlns:xs4xs="http://www.w3.org/2001/XMLSchema"
    xmlns:io7="http://www.w3.org/2005/08/addressing"
    xmlns:map="http://NCLFuseBoxMediation/xslt/UpdateRequesMsgLog_req_1"
    xmlns:msl="http://www.ibm.com/xmlmap"
    exclude-result-prefixes="in in2 str set math fn regexp dyn dp exsl date map xalan msl"
    version="1.0">

  <!-- imports  -->
  <xsl:import href="UpdateRequesMsgLog_req_1_custom.xsl"/>
  <xsl:output method="xml" encoding="UTF-8" indent="no"/>

  <!-- root wrapper template  -->
  <xsl:template match="/">
    <xsl:choose>
      <xsl:when test="msl:datamap">
        <msl:datamap>
          <xsl:element name="dataObject">
            <xsl:attribute name="xsi:type">
              <xsl:value-of select="'io2:ServiceMessageObject'"/>
            </xsl:attribute>
            <xsl:call-template name="map:UpdateRequesMsgLog_req_12">
              <xsl:with-param name="smo" select="msl:datamap/dataObject[1]"/>
            </xsl:call-template>
          </xsl:element>
        </msl:datamap>
      </xsl:when>
      <xsl:otherwise>
        <xsl:apply-templates select="io2:smo" mode="map:UpdateRequesMsgLog_req_1"/>
      </xsl:otherwise>
    </xsl:choose>
  </xsl:template>

  <!-- This rule represents an element mapping: "io2:smo" to "io2:smo".  -->
  <xsl:template match="io2:smo"  mode="map:UpdateRequesMsgLog_req_1">
    <io2:smo>
      <body>
        <xsl:attribute name="xsi:type">
          <xsl:value-of select="'out:executeUpdateRequestMsgSQLBGRequestMsg'"/>
        </xsl:attribute>
        <out4:executeUpdateRequestMsgSQLBG>
          <out4:executeUpdateRequestMsgSQLBGInput>
            <!-- a simple mapping with no associated source:  to "verb"(<string>) -->
            <xsl:element name="verb">
              <xsl:text>Update</xsl:text>
            </xsl:element>
            <xsl:element name="UpdateRequestMsgSQL">
              <!-- a simple data mapping: "body/in:processCardInfo/Request"(<Anonymous>) to "statement1parameter1"(string) -->
              <xsl:if test="body/in:processCardInfo/Request">
                <xsl:element name="statement1parameter1">
                  <!-- variables for custom code -->
                  <xsl:variable name="Request" select="body/in:processCardInfo/Request"/>
                  <xsl:call-template name="RequestToStatement1parameter1">
                    <xsl:with-param name="Request" select="$Request"/>
                  </xsl:call-template>
                </xsl:element>
              </xsl:if>
              <!-- a simple data mapping: "context/transient/UNIQUE_VAL_ID"(string) to "statement1parameter2"(string) -->
              <xsl:if test="context/transient/UNIQUE_VAL_ID">
                <xsl:element name="statement1parameter2">
                  <xsl:value-of select="context/transient/UNIQUE_VAL_ID"/>
                </xsl:element>
              </xsl:if>
            </xsl:element>
          </out4:executeUpdateRequestMsgSQLBGInput>
        </out4:executeUpdateRequestMsgSQLBG>
      </body>
    </io2:smo>
  </xsl:template>

  <!-- This rule represents a type mapping: "io2:smo" to "io2:smo".  -->
  <xsl:template name="map:UpdateRequesMsgLog_req_12">
    <xsl:param name="smo"/>
    <body>
      <xsl:attribute name="xsi:type">
        <xsl:value-of select="'out:executeUpdateRequestMsgSQLBGRequestMsg'"/>
      </xsl:attribute>
      <out4:executeUpdateRequestMsgSQLBG>
        <out4:executeUpdateRequestMsgSQLBGInput>
          <!-- a simple mapping with no associated source:  to "verb"(<string>) -->
          <xsl:element name="verb">
            <xsl:text>Update</xsl:text>
          </xsl:element>
          <xsl:element name="UpdateRequestMsgSQL">
            <!-- a simple data mapping: "$smo/body/in:processCardInfo/Request"(<Anonymous>) to "statement1parameter1"(string) -->
            <xsl:if test="$smo/body/in:processCardInfo/Request">
              <xsl:element name="statement1parameter1">
                <!-- variables for custom code -->
                <xsl:variable name="Request" select="$smo/body/in:processCardInfo/Request"/>
                <xsl:call-template name="RequestToStatement1parameter1">
                  <xsl:with-param name="Request" select="$Request"/>
                </xsl:call-template>
              </xsl:element>
            </xsl:if>
            <!-- a simple data mapping: "$smo/context/transient/UNIQUE_VAL_ID"(string) to "statement1parameter2"(string) -->
            <xsl:if test="$smo/context/transient/UNIQUE_VAL_ID">
              <xsl:element name="statement1parameter2">
                <xsl:value-of select="$smo/context/transient/UNIQUE_VAL_ID"/>
              </xsl:element>
            </xsl:if>
          </xsl:element>
        </out4:executeUpdateRequestMsgSQLBGInput>
      </out4:executeUpdateRequestMsgSQLBG>
    </body>
  </xsl:template>

  <!-- *****************    Utility Templates    ******************  -->
  <!-- copy the namespace declarations from the source to the target -->
  <xsl:template name="copyNamespaceDeclarations">
    <xsl:param name="root"/>
    <xsl:for-each select="$root/namespace::*[not(name() = '')]">
      <xsl:copy/>
    </xsl:for-each>
  </xsl:template>
</xsl:stylesheet>
