<?xml version="1.0" encoding="UTF-8"?>
<!-- @generated mapFile="xslt/XSLTransformation2_req_1.map" md5sum="8c5dd89f005e3431ae32cd9f27dd9254" version="7.6.100" -->
<!--
*****************************************************************************
*   This file has been generated by the IBM XML Mapping Editor.
*
*   Mapping file:		XSLTransformation2_req_1.map
*   Map declaration(s):	XSLTransformation2_req_1
*   Input file(s):		smo://smo/name%3Dwsdl-primary/correlationContext%3D%257Bhttp%253A%252F%252FNCL_CruiseRtrvNameList_Module%257DApp_Context/message%3D%257Bhttp%253A%252F%252FTP_Logger%252FTP_Interface%257DTP_InsertUpdateRequestMsg/xpath%3D%252F/smo.xsd
*   Output file(s):		smo://smo/name%3Dwsdl-primary/correlationContext%3D%257Bhttp%253A%252F%252FNCL_CruiseRtrvNameList_Module%257DApp_Context/message%3D%257Bhttp%253A%252F%252FNCL_CruiseRtrvNameList_Module%252FDB_LOOKUP%257DexecuteNclseaNcl_Wesb_Retrieve_Name_ListBGRequestMsg/xpath%3D%252F/smo.xsd
*
*   Note: Do not modify the contents of this file as it is overwritten
*         each time the mapping model is updated.
*****************************************************************************
-->
<xsl:stylesheet
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xalan="http://xml.apache.org/xslt"
    xmlns:str="http://exslt.org/strings"
    xmlns:set="http://exslt.org/sets"
    xmlns:math="http://exslt.org/math"
    xmlns:fn="http://www.w3.org/2005/xpath-functions"
    xmlns:regexp="http://exslt.org/regular-expressions"
    xmlns:dyn="http://exslt.org/dynamic"
    xmlns:dp="http://www.datapower.com/extensions"
    xmlns:exsl="http://exslt.org/common"
    xmlns:date="http://exslt.org/dates-and-times"
    xmlns:in="http://TP_Logger/TP_Interface"
    xmlns:in2="wsdl.http://TP_Logger/TP_Interface"
    xmlns:io5="http://www.w3.org/2003/05/soap-envelope"
    xmlns:io6="http://www.ibm.com/websphere/sibx/smo/v6.0.1"
    xmlns:out2="wsdl.http://NCL_CruiseRtrvNameList_Module/DB_LOOKUP"
    xmlns:out3="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/nclseancl_wesb_retrieve_name_list"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:out5="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/nclseancl_wesb_retrieve_name_listp_cursor"
    xmlns:out4="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/nclseancl_wesb_retrieve_name_listbg"
    xmlns:io="http://NCL_CruiseRtrvNameList_Module"
    xmlns:out6="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/nclseancl_wesb_get_consumer_nam_list"
    xmlns:out8="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/nclseancl_wesb_get_consumer_nam_listbg"
    xmlns:out7="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/nclseancl_wesb_get_consumer_nam_listp_cursor"
    xmlns:io2="http://www.ibm.com/xmlns/prod/websphere/mq/sca/6.0.0"
    xmlns:io3="http://schemas.xmlsoap.org/ws/2004/08/addressing"
    xmlns:io7="http://www.ibm.com/xmlns/prod/websphere/http/sca/6.1.0"
    xmlns:io4="http://nclapi/schemas"
    xmlns:out="http://NCL_CruiseRtrvNameList_Module/DB_LOOKUP"
    xmlns:out9="http://www.ibm.com/xmlns/prod/websphere/bo/6.0.0"
    xmlns:xs4xs="http://www.w3.org/2001/XMLSchema"
    xmlns:io8="http://www.w3.org/2005/08/addressing"
    xmlns:map="http://NCL_CruiseRtrvNameList_Module/xslt/XSLTransformation2_req_1"
    xmlns:msl="http://www.ibm.com/xmlmap"
    exclude-result-prefixes="in in2 str set math fn regexp dyn dp exsl date map xalan msl"
    version="1.0">
  <xsl:output method="xml" encoding="UTF-8" indent="no"/>

  <!-- root wrapper template  -->
  <xsl:template match="/">
    <xsl:choose>
      <xsl:when test="msl:datamap">
        <msl:datamap>
          <xsl:element name="dataObject">
            <xsl:attribute name="xsi:type">
              <xsl:value-of select="'io6:ServiceMessageObject'"/>
            </xsl:attribute>
            <xsl:call-template name="map:XSLTransformation2_req_12">
              <xsl:with-param name="smo" select="msl:datamap/dataObject[1]"/>
            </xsl:call-template>
          </xsl:element>
        </msl:datamap>
      </xsl:when>
      <xsl:otherwise>
        <xsl:apply-templates select="io6:smo" mode="map:XSLTransformation2_req_1"/>
      </xsl:otherwise>
    </xsl:choose>
  </xsl:template>

  <!-- This rule represents an element mapping: "io6:smo" to "io6:smo".  -->
  <xsl:template match="io6:smo"  mode="map:XSLTransformation2_req_1">
    <io6:smo>
      <context>
        <correlation>
          <xsl:attribute name="xsi:type">
            <xsl:value-of select="'io:App_Context'"/>
          </xsl:attribute>
          <!-- a structural mapping: "context/correlation/io4:NCL_CruiseRtrvNameListRQ"(<Anonymous>) to "io4:NCL_CruiseRtrvNameListRQ"(<Anonymous>) -->
          <xsl:if test="context/correlation/io4:NCL_CruiseRtrvNameListRQ">
            <xsl:copy-of select="context/correlation/io4:NCL_CruiseRtrvNameListRQ"/>
          </xsl:if>
          <!-- a simple data mapping: "context/correlation/LogID"(string) to "LogID"(string) -->
          <xsl:if test="context/correlation/LogID">
            <xsl:element name="LogID">
              <xsl:value-of select="context/correlation/LogID"/>
            </xsl:element>
          </xsl:if>
        </correlation>
      </context>
      <xsl:element name="body">
        <xsl:attribute name="xsi:type">
          <xsl:value-of select="'out2:executeNclseaNcl_Wesb_Retrieve_Name_ListBGRequestMsg'"/>
        </xsl:attribute>
        <xsl:element name="out:executeNclseaNcl_Wesb_Retrieve_Name_ListBG">
          <xsl:element name="out:executeNclseaNcl_Wesb_Retrieve_Name_ListBGInput">
            <xsl:element name="NclseaNcl_Wesb_Retrieve_Name_List">
              <!-- a simple data mapping: "context/correlation/io4:NCL_CruiseRtrvNameListRQ/io4:POS/io4:Source[1]/io4:RequestorID/@ID"(StringLength1to32) to "p_agencyid"(int) -->
              <xsl:if test="context/correlation/io4:NCL_CruiseRtrvNameListRQ/io4:POS/io4:Source[1]/io4:RequestorID/@ID">
                <xsl:element name="p_agencyid">
                  <xsl:value-of select="context/correlation/io4:NCL_CruiseRtrvNameListRQ/io4:POS/io4:Source[1]/io4:RequestorID/@ID"/>
                </xsl:element>
              </xsl:if>
              <!-- a simple data mapping: "context/correlation/io4:NCL_CruiseRtrvNameListRQ/io4:POS/io4:Source[1]/io4:BookingChannel/io4:CompanyName/@Code"(StringLength1to16) to "p_gds"(string) -->
              <xsl:if test="context/correlation/io4:NCL_CruiseRtrvNameListRQ/io4:POS/io4:Source[1]/io4:BookingChannel/io4:CompanyName/@Code">
                <xsl:element name="p_gds">
                  <xsl:value-of select="context/correlation/io4:NCL_CruiseRtrvNameListRQ/io4:POS/io4:Source[1]/io4:BookingChannel/io4:CompanyName/@Code"/>
                </xsl:element>
              </xsl:if>
              <!-- a simple data mapping: "context/correlation/io4:NCL_CruiseRtrvNameListRQ/io4:POS/io4:Source[1]/@AgentSine"(StringLength1to16) to "p_agentid"(int) -->
              <xsl:if test="context/correlation/io4:NCL_CruiseRtrvNameListRQ/io4:POS/io4:Source[1]/@AgentSine">
                <xsl:element name="p_agentid">
                  <xsl:value-of select="context/correlation/io4:NCL_CruiseRtrvNameListRQ/io4:POS/io4:Source[1]/@AgentSine"/>
                </xsl:element>
              </xsl:if>
              <!-- a simple data mapping: "context/correlation/io4:NCL_CruiseRtrvNameListRQ/io4:GuestInfo/io4:LoyaltyInfo/@MembershipID"(StringLength1to32) to "p_clientid"(int) -->
              <xsl:if test="context/correlation/io4:NCL_CruiseRtrvNameListRQ/io4:GuestInfo/io4:LoyaltyInfo/@MembershipID">
                <xsl:element name="p_clientid">
                  <xsl:value-of select="context/correlation/io4:NCL_CruiseRtrvNameListRQ/io4:GuestInfo/io4:LoyaltyInfo/@MembershipID"/>
                </xsl:element>
              </xsl:if>
              <!-- a simple data mapping: "context/correlation/io4:NCL_CruiseRtrvNameListRQ/io4:GuestInfo/io4:Surname"(StringLength1to64) to "p_lastname"(string) -->
              <xsl:if test="context/correlation/io4:NCL_CruiseRtrvNameListRQ/io4:GuestInfo/io4:Surname">
                <xsl:element name="p_lastname">
                  <xsl:value-of select="context/correlation/io4:NCL_CruiseRtrvNameListRQ/io4:GuestInfo/io4:Surname"/>
                </xsl:element>
              </xsl:if>
              <!-- a simple data mapping: "context/correlation/io4:NCL_CruiseRtrvNameListRQ/io4:GuestInfo/io4:GivenName[1]"(StringLength1to64) to "p_firstname"(string) -->
              <xsl:if test="context/correlation/io4:NCL_CruiseRtrvNameListRQ/io4:GuestInfo/io4:GivenName[1]">
                <xsl:element name="p_firstname">
                  <xsl:value-of select="context/correlation/io4:NCL_CruiseRtrvNameListRQ/io4:GuestInfo/io4:GivenName[1]"/>
                </xsl:element>
              </xsl:if>
              <!-- a simple data mapping: "context/correlation/io4:NCL_CruiseRtrvNameListRQ/io4:SelectedSailing/@ShipCode"(StringLength1to16) to "p_shipcode"(string) -->
              <xsl:if test="context/correlation/io4:NCL_CruiseRtrvNameListRQ/io4:SelectedSailing/@ShipCode">
                <xsl:element name="p_shipcode">
                  <xsl:value-of select="context/correlation/io4:NCL_CruiseRtrvNameListRQ/io4:SelectedSailing/@ShipCode"/>
                </xsl:element>
              </xsl:if>
              <!-- a simple data mapping: "context/correlation/io4:NCL_CruiseRtrvNameListRQ/io4:SelectedSailing/@Start"(DateOrTimeOrDateTimeType) to "p_sailingdate"(string) -->
              <xsl:if test="context/correlation/io4:NCL_CruiseRtrvNameListRQ/io4:SelectedSailing/@Start">
                <xsl:element name="p_sailingdate">
                  <xsl:value-of select="context/correlation/io4:NCL_CruiseRtrvNameListRQ/io4:SelectedSailing/@Start"/>
                </xsl:element>
              </xsl:if>
              <!-- a simple data mapping: "context/correlation/io4:NCL_CruiseRtrvNameListRQ/io4:SelectedSailing/@End"(DateOrTimeOrDateTimeType) to "p_sailingenddate"(string) -->
              <xsl:if test="context/correlation/io4:NCL_CruiseRtrvNameListRQ/io4:SelectedSailing/@End">
                <xsl:element name="p_sailingenddate">
                  <xsl:value-of select="context/correlation/io4:NCL_CruiseRtrvNameListRQ/io4:SelectedSailing/@End"/>
                </xsl:element>
              </xsl:if>
              <!-- a simple data mapping: "context/correlation/io4:NCL_CruiseRtrvNameListRQ/io4:GuestInfo/io4:GroupInfo/@GroupCode"(StringLength1to16) to "p_groupid"(string) -->
              <xsl:if test="context/correlation/io4:NCL_CruiseRtrvNameListRQ/io4:GuestInfo/io4:GroupInfo/@GroupCode">
                <xsl:element name="p_groupid">
                  <xsl:value-of select="context/correlation/io4:NCL_CruiseRtrvNameListRQ/io4:GuestInfo/io4:GroupInfo/@GroupCode"/>
                </xsl:element>
              </xsl:if>
              <!-- a simple mapping with no associated source:  to "p_lastresidreturned"(int) -->
              <xsl:element name="p_lastresidreturned">
                <xsl:text>0</xsl:text>
              </xsl:element>
              <!-- a simple mapping with no associated source:  to "p_maxrecordsoutput"(int) -->
              <xsl:element name="p_maxrecordsoutput">
                <xsl:text>9999</xsl:text>
              </xsl:element>
            </xsl:element>
          </xsl:element>
        </xsl:element>
      </xsl:element>
    </io6:smo>
  </xsl:template>

  <!-- This rule represents a type mapping: "io6:smo" to "io6:smo".  -->
  <xsl:template name="map:XSLTransformation2_req_12">
    <xsl:param name="smo"/>
    <context>
      <correlation>
        <xsl:attribute name="xsi:type">
          <xsl:value-of select="'io:App_Context'"/>
        </xsl:attribute>
        <!-- a structural mapping: "$smo/context/correlation/io4:NCL_CruiseRtrvNameListRQ"(<Anonymous>) to "io4:NCL_CruiseRtrvNameListRQ"(<Anonymous>) -->
        <xsl:if test="$smo/context/correlation/io4:NCL_CruiseRtrvNameListRQ">
          <xsl:copy-of select="$smo/context/correlation/io4:NCL_CruiseRtrvNameListRQ"/>
        </xsl:if>
        <!-- a simple data mapping: "$smo/context/correlation/LogID"(string) to "LogID"(string) -->
        <xsl:if test="$smo/context/correlation/LogID">
          <xsl:element name="LogID">
            <xsl:value-of select="$smo/context/correlation/LogID"/>
          </xsl:element>
        </xsl:if>
      </correlation>
    </context>
    <xsl:element name="body">
      <xsl:attribute name="xsi:type">
        <xsl:value-of select="'out2:executeNclseaNcl_Wesb_Retrieve_Name_ListBGRequestMsg'"/>
      </xsl:attribute>
      <xsl:element name="out:executeNclseaNcl_Wesb_Retrieve_Name_ListBG">
        <xsl:element name="out:executeNclseaNcl_Wesb_Retrieve_Name_ListBGInput">
          <xsl:element name="NclseaNcl_Wesb_Retrieve_Name_List">
            <!-- a simple data mapping: "$smo/context/correlation/io4:NCL_CruiseRtrvNameListRQ/io4:POS/io4:Source[1]/io4:RequestorID/@ID"(StringLength1to32) to "p_agencyid"(int) -->
            <xsl:if test="$smo/context/correlation/io4:NCL_CruiseRtrvNameListRQ/io4:POS/io4:Source[1]/io4:RequestorID/@ID">
              <xsl:element name="p_agencyid">
                <xsl:value-of select="$smo/context/correlation/io4:NCL_CruiseRtrvNameListRQ/io4:POS/io4:Source[1]/io4:RequestorID/@ID"/>
              </xsl:element>
            </xsl:if>
            <!-- a simple data mapping: "$smo/context/correlation/io4:NCL_CruiseRtrvNameListRQ/io4:POS/io4:Source[1]/io4:BookingChannel/io4:CompanyName/@Code"(StringLength1to16) to "p_gds"(string) -->
            <xsl:if test="$smo/context/correlation/io4:NCL_CruiseRtrvNameListRQ/io4:POS/io4:Source[1]/io4:BookingChannel/io4:CompanyName/@Code">
              <xsl:element name="p_gds">
                <xsl:value-of select="$smo/context/correlation/io4:NCL_CruiseRtrvNameListRQ/io4:POS/io4:Source[1]/io4:BookingChannel/io4:CompanyName/@Code"/>
              </xsl:element>
            </xsl:if>
            <!-- a simple data mapping: "$smo/context/correlation/io4:NCL_CruiseRtrvNameListRQ/io4:POS/io4:Source[1]/@AgentSine"(StringLength1to16) to "p_agentid"(int) -->
            <xsl:if test="$smo/context/correlation/io4:NCL_CruiseRtrvNameListRQ/io4:POS/io4:Source[1]/@AgentSine">
              <xsl:element name="p_agentid">
                <xsl:value-of select="$smo/context/correlation/io4:NCL_CruiseRtrvNameListRQ/io4:POS/io4:Source[1]/@AgentSine"/>
              </xsl:element>
            </xsl:if>
            <!-- a simple data mapping: "$smo/context/correlation/io4:NCL_CruiseRtrvNameListRQ/io4:GuestInfo/io4:LoyaltyInfo/@MembershipID"(StringLength1to32) to "p_clientid"(int) -->
            <xsl:if test="$smo/context/correlation/io4:NCL_CruiseRtrvNameListRQ/io4:GuestInfo/io4:LoyaltyInfo/@MembershipID">
              <xsl:element name="p_clientid">
                <xsl:value-of select="$smo/context/correlation/io4:NCL_CruiseRtrvNameListRQ/io4:GuestInfo/io4:LoyaltyInfo/@MembershipID"/>
              </xsl:element>
            </xsl:if>
            <!-- a simple data mapping: "$smo/context/correlation/io4:NCL_CruiseRtrvNameListRQ/io4:GuestInfo/io4:Surname"(StringLength1to64) to "p_lastname"(string) -->
            <xsl:if test="$smo/context/correlation/io4:NCL_CruiseRtrvNameListRQ/io4:GuestInfo/io4:Surname">
              <xsl:element name="p_lastname">
                <xsl:value-of select="$smo/context/correlation/io4:NCL_CruiseRtrvNameListRQ/io4:GuestInfo/io4:Surname"/>
              </xsl:element>
            </xsl:if>
            <!-- a simple data mapping: "$smo/context/correlation/io4:NCL_CruiseRtrvNameListRQ/io4:GuestInfo/io4:GivenName[1]"(StringLength1to64) to "p_firstname"(string) -->
            <xsl:if test="$smo/context/correlation/io4:NCL_CruiseRtrvNameListRQ/io4:GuestInfo/io4:GivenName[1]">
              <xsl:element name="p_firstname">
                <xsl:value-of select="$smo/context/correlation/io4:NCL_CruiseRtrvNameListRQ/io4:GuestInfo/io4:GivenName[1]"/>
              </xsl:element>
            </xsl:if>
            <!-- a simple data mapping: "$smo/context/correlation/io4:NCL_CruiseRtrvNameListRQ/io4:SelectedSailing/@ShipCode"(StringLength1to16) to "p_shipcode"(string) -->
            <xsl:if test="$smo/context/correlation/io4:NCL_CruiseRtrvNameListRQ/io4:SelectedSailing/@ShipCode">
              <xsl:element name="p_shipcode">
                <xsl:value-of select="$smo/context/correlation/io4:NCL_CruiseRtrvNameListRQ/io4:SelectedSailing/@ShipCode"/>
              </xsl:element>
            </xsl:if>
            <!-- a simple data mapping: "$smo/context/correlation/io4:NCL_CruiseRtrvNameListRQ/io4:SelectedSailing/@Start"(DateOrTimeOrDateTimeType) to "p_sailingdate"(string) -->
            <xsl:if test="$smo/context/correlation/io4:NCL_CruiseRtrvNameListRQ/io4:SelectedSailing/@Start">
              <xsl:element name="p_sailingdate">
                <xsl:value-of select="$smo/context/correlation/io4:NCL_CruiseRtrvNameListRQ/io4:SelectedSailing/@Start"/>
              </xsl:element>
            </xsl:if>
            <!-- a simple data mapping: "$smo/context/correlation/io4:NCL_CruiseRtrvNameListRQ/io4:SelectedSailing/@End"(DateOrTimeOrDateTimeType) to "p_sailingenddate"(string) -->
            <xsl:if test="$smo/context/correlation/io4:NCL_CruiseRtrvNameListRQ/io4:SelectedSailing/@End">
              <xsl:element name="p_sailingenddate">
                <xsl:value-of select="$smo/context/correlation/io4:NCL_CruiseRtrvNameListRQ/io4:SelectedSailing/@End"/>
              </xsl:element>
            </xsl:if>
            <!-- a simple data mapping: "$smo/context/correlation/io4:NCL_CruiseRtrvNameListRQ/io4:GuestInfo/io4:GroupInfo/@GroupCode"(StringLength1to16) to "p_groupid"(string) -->
            <xsl:if test="$smo/context/correlation/io4:NCL_CruiseRtrvNameListRQ/io4:GuestInfo/io4:GroupInfo/@GroupCode">
              <xsl:element name="p_groupid">
                <xsl:value-of select="$smo/context/correlation/io4:NCL_CruiseRtrvNameListRQ/io4:GuestInfo/io4:GroupInfo/@GroupCode"/>
              </xsl:element>
            </xsl:if>
            <!-- a simple mapping with no associated source:  to "p_lastresidreturned"(int) -->
            <xsl:element name="p_lastresidreturned">
              <xsl:text>0</xsl:text>
            </xsl:element>
            <!-- a simple mapping with no associated source:  to "p_maxrecordsoutput"(int) -->
            <xsl:element name="p_maxrecordsoutput">
              <xsl:text>9999</xsl:text>
            </xsl:element>
          </xsl:element>
        </xsl:element>
      </xsl:element>
    </xsl:element>
  </xsl:template>

  <!-- *****************    Utility Templates    ******************  -->
  <!-- copy the namespace declarations from the source to the target -->
  <xsl:template name="copyNamespaceDeclarations">
    <xsl:param name="root"/>
    <xsl:for-each select="$root/namespace::*[not(name() = '')]">
      <xsl:copy/>
    </xsl:for-each>
  </xsl:template>
</xsl:stylesheet>
