<?xml version="1.0" encoding="UTF-8"?>
<!-- @generated mapFile="xslt/XSLTransformation1_req_4.map" md5sum="cb0b9b04e8adeec5341de510d820eefd" version="7.6.100" -->
<!--
*****************************************************************************
*   This file has been generated by the IBM XML Mapping Editor.
*
*   Mapping file:		XSLTransformation1_req_4.map
*   Map declaration(s):	XSLTransformation1_req_4
*   Input file(s):		smo://smo/name%3Dwsdl-primary/correlationContext%3D%257Bhttp%253A%252F%252FPs_Maps%257DAppContext/message%3D%257Bhttp%253A%252F%252Ftempuri.org%252FNCLCaseTools%252FNCLTools%257DPeopleSoft_TO_MAPSSoapIn/xpath%3D%252F/smo.xsd
*   Output file(s):		smo://smo/name%3Dwsdl-primary/correlationContext%3D%257Bhttp%253A%252F%252FPs_Maps%257DAppContext/message%3D%257Bhttp%253A%252F%252FPs_Maps%252FEmailServiceImport%257DsendSimpleAlertEmailRequestMsg/xpath%3D%252F/smo.xsd
*
*   Note: Do not modify the contents of this file as it is overwritten
*         each time the mapping model is updated.
*****************************************************************************
-->
<xsl:stylesheet
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xalan="http://xml.apache.org/xslt"
    xmlns:str="http://exslt.org/strings"
    xmlns:set="http://exslt.org/sets"
    xmlns:math="http://exslt.org/math"
    xmlns:fn="http://www.w3.org/2005/xpath-functions"
    xmlns:regexp="http://exslt.org/regular-expressions"
    xmlns:dyn="http://exslt.org/dynamic"
    xmlns:dp="http://www.datapower.com/extensions"
    xmlns:exsl="http://exslt.org/common"
    xmlns:date="http://exslt.org/dates-and-times"
    xmlns:in2="http://tempuri.org/NCLCaseTools/NCLTools"
    xmlns:in="wsdl.http://tempuri.org/NCLCaseTools/NCLTools"
    xmlns:io="http://Ps_Maps"
    xmlns:io2="http://www.w3.org/2003/05/soap-envelope"
    xmlns:out="wsdl.http://Ps_Maps/EmailServiceImport"
    xmlns:io3="http://www.ibm.com/websphere/sibx/smo/v6.0.1"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:out2="http://Ps_Maps/EmailServiceImport"
    xmlns:out3="http://www.ibm.com/xmlns/prod/websphere/j2ca/email/simplealertemail"
    xmlns:io4="http://www.ibm.com/xmlns/prod/websphere/mq/sca/6.0.0"
    xmlns:io5="http://schemas.xmlsoap.org/ws/2004/08/addressing"
    xmlns:io6="http://www.ibm.com/xmlns/prod/websphere/http/sca/6.1.0"
    xmlns:xs4xs="http://www.w3.org/2001/XMLSchema"
    xmlns:io7="http://tempuri.org/NewPerson.xsd"
    xmlns:io8="http://www.w3.org/2005/08/addressing"
    xmlns:map="http://Ps_Maps/xslt/XSLTransformation1_req_4"
    xmlns:msl="http://www.ibm.com/xmlmap"
    exclude-result-prefixes="in2 in str set math fn regexp dyn dp exsl date map xalan msl"
    version="1.0">
  <xsl:output method="xml" encoding="UTF-8" indent="no"/>

  <!-- root wrapper template  -->
  <xsl:template match="/">
    <xsl:choose>
      <xsl:when test="msl:datamap">
        <msl:datamap>
          <xsl:element name="dataObject">
            <xsl:attribute name="xsi:type">
              <xsl:value-of select="'io3:ServiceMessageObject'"/>
            </xsl:attribute>
            <xsl:call-template name="map:XSLTransformation1_req_42">
              <xsl:with-param name="smo" select="msl:datamap/dataObject[1]"/>
            </xsl:call-template>
          </xsl:element>
        </msl:datamap>
      </xsl:when>
      <xsl:otherwise>
        <xsl:apply-templates select="io3:smo" mode="map:XSLTransformation1_req_4"/>
      </xsl:otherwise>
    </xsl:choose>
  </xsl:template>

  <!-- This rule represents an element mapping: "io3:smo" to "io3:smo".  -->
  <xsl:template match="io3:smo"  mode="map:XSLTransformation1_req_4">
    <io3:smo>
      <context>
        <!-- a structural mapping: "context/correlation"(AppContext) to "correlation"(AppContext) -->
        <xsl:if test="context/correlation">
          <xsl:copy-of select="context/correlation"/>
        </xsl:if>
      </context>
      <xsl:element name="body">
        <xsl:attribute name="xsi:type">
          <xsl:value-of select="'out:sendSimpleAlertEmailRequestMsg'"/>
        </xsl:attribute>
        <xsl:element name="out2:sendSimpleAlertEmail">
          <xsl:element name="out2:sendSimpleAlertEmailInput">
            <!-- a simple mapping with no associated source:  to "To"(string) -->
            <xsl:element name="To">
              <xsl:text>lrohr@ncl.com</xsl:text>
            </xsl:element>
            <!-- a simple mapping with no associated source:  to "From"(string) -->
            <xsl:element name="From">
              <xsl:text>esbmon@ncl.com</xsl:text>
            </xsl:element>
            <!-- a simple mapping with no associated source:  to "Subject"(string) -->
            <xsl:element name="Subject">
              <xsl:text>MAPS - Timeout</xsl:text>
            </xsl:element>
            <!-- a simple data mapping: "context/correlation/NewPerson_str"(string) to "mailContent"(string) -->
            <xsl:if test="context/correlation/NewPerson_str">
              <xsl:element name="mailContent">
                <xsl:value-of select="context/correlation/NewPerson_str"/>
              </xsl:element>
            </xsl:if>
          </xsl:element>
        </xsl:element>
      </xsl:element>
    </io3:smo>
  </xsl:template>

  <!-- This rule represents a type mapping: "io3:smo" to "io3:smo".  -->
  <xsl:template name="map:XSLTransformation1_req_42">
    <xsl:param name="smo"/>
    <context>
      <!-- a structural mapping: "$smo/context/correlation"(AppContext) to "correlation"(AppContext) -->
      <xsl:if test="$smo/context/correlation">
        <xsl:copy-of select="$smo/context/correlation"/>
      </xsl:if>
    </context>
    <xsl:element name="body">
      <xsl:attribute name="xsi:type">
        <xsl:value-of select="'out:sendSimpleAlertEmailRequestMsg'"/>
      </xsl:attribute>
      <xsl:element name="out2:sendSimpleAlertEmail">
        <xsl:element name="out2:sendSimpleAlertEmailInput">
          <!-- a simple mapping with no associated source:  to "To"(string) -->
          <xsl:element name="To">
            <xsl:text>lrohr@ncl.com</xsl:text>
          </xsl:element>
          <!-- a simple mapping with no associated source:  to "From"(string) -->
          <xsl:element name="From">
            <xsl:text>esbmon@ncl.com</xsl:text>
          </xsl:element>
          <!-- a simple mapping with no associated source:  to "Subject"(string) -->
          <xsl:element name="Subject">
            <xsl:text>MAPS - Timeout</xsl:text>
          </xsl:element>
          <!-- a simple data mapping: "$smo/context/correlation/NewPerson_str"(string) to "mailContent"(string) -->
          <xsl:if test="$smo/context/correlation/NewPerson_str">
            <xsl:element name="mailContent">
              <xsl:value-of select="$smo/context/correlation/NewPerson_str"/>
            </xsl:element>
          </xsl:if>
        </xsl:element>
      </xsl:element>
    </xsl:element>
  </xsl:template>

  <!-- *****************    Utility Templates    ******************  -->
  <!-- copy the namespace declarations from the source to the target -->
  <xsl:template name="copyNamespaceDeclarations">
    <xsl:param name="root"/>
    <xsl:for-each select="$root/namespace::*[not(name() = '')]">
      <xsl:copy/>
    </xsl:for-each>
  </xsl:template>
</xsl:stylesheet>
