<?xml version="1.0" encoding="UTF-8"?>
<!-- @generated mapFile="xslt/XSLT_toencrypt_req_1.map" md5sum="1f011c140536f63f0c81b99f235e5115" version="7.6.100" -->
<!--
*****************************************************************************
*   This file has been generated by the IBM XML Mapping Editor.
*
*   Mapping file:		XSLT_toencrypt_req_1.map
*   Map declaration(s):	XSLT_toencrypt_req_1
*   Input file(s):		smo://smo/name%3Dwsdl-primary/correlationContext%3D%257Bhttp%253A%252F%252FNCL_CruiseRetrieveClient_Module%257DApp_Context/message%3D%257Bhttp%253A%252F%252FNCL_CruiseRetrieveClient_Module%252FJDBCImport2%257DexecuteNclseaNcl_Wesb_Get_Client_Prof_V1ResponseMsg/xpath%3D%252F/smo.xsd
*   Output file(s):		smo://smo/name%3Dwsdl-primary/correlationContext%3D%257Bhttp%253A%252F%252FNCL_CruiseRetrieveClient_Module%257DApp_Context/message%3D%257Bhttp%253A%252F%252Fversonix.com%252Fapi%252Fdefinitions%257DprocessEncryptDecryptRequest/xpath%3D%252F/smo.xsd
*   XSLT import(s):   	XSLT_toencrypt_req_1_sex.xsl
*
*   Note: Do not modify the contents of this file as it is overwritten
*         each time the mapping model is updated.
*****************************************************************************
-->
<xsl:stylesheet
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xalan="http://xml.apache.org/xslt"
    xmlns:str="http://exslt.org/strings"
    xmlns:set="http://exslt.org/sets"
    xmlns:math="http://exslt.org/math"
    xmlns:fn="http://www.w3.org/2005/xpath-functions"
    xmlns:regexp="http://exslt.org/regular-expressions"
    xmlns:dyn="http://exslt.org/dynamic"
    xmlns:dp="http://www.datapower.com/extensions"
    xmlns:exsl="http://exslt.org/common"
    xmlns:date="http://exslt.org/dates-and-times"
    xmlns:in="wsdl.http://NCL_CruiseRetrieveClient_Module/JDBCImport2"
    xmlns:in2="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/nclseancl_wesb_get_client_prof_v1"
    xmlns:in3="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/nclseancl_wesb_get_client_prof_v1p_cursor"
    xmlns:in4="http://com/ibm/j2ca/fault"
    xmlns:in5="http://NCL_CruiseRetrieveClient_Module/JDBCImport2"
    xmlns:in6="http://com/ibm/j2ca/fault/afcfault"
    xmlns:out="http://versonix.com/api/schemas"
    xmlns:io="http://www.w3.org/2003/05/soap-envelope"
    xmlns:io3="http://www.ibm.com/xmlns/prod/websphere/mq/sca/6.0.0"
    xmlns:io2="http://www.ibm.com/websphere/sibx/smo/v6.0.1"
    xmlns:out2="wsdl.http://versonix.com/api/definitions"
    xmlns:io4="http://NCL_CruiseRetrieveClient_Module"
    xmlns:io5="http://schemas.xmlsoap.org/ws/2004/08/addressing"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:io7="http://www.ibm.com/xmlns/prod/websphere/http/sca/6.1.0"
    xmlns:io6="http://nclapi/schemas"
    xmlns:xs4xs="http://www.w3.org/2001/XMLSchema"
    xmlns:io8="http://www.w3.org/2005/08/addressing"
    xmlns:map="http://NCL_CruiseRetrieveClient_Module/xslt/XSLT_toencrypt_req_1"
    xmlns:msl="http://www.ibm.com/xmlmap"
    exclude-result-prefixes="in in2 in3 in4 in5 in6 str set math fn regexp dyn dp exsl date map xalan msl"
    version="1.0">

  <!-- imports  -->
  <xsl:import href="XSLT_toencrypt_req_1_sex.xsl"/>
  <xsl:output method="xml" encoding="UTF-8" indent="no"/>

  <!-- root wrapper template  -->
  <xsl:template match="/">
    <xsl:choose>
      <xsl:when test="msl:datamap">
        <msl:datamap>
          <xsl:element name="dataObject">
            <xsl:attribute name="xsi:type">
              <xsl:value-of select="'io2:ServiceMessageObject'"/>
            </xsl:attribute>
            <xsl:call-template name="map:XSLT_toencrypt_req_12">
              <xsl:with-param name="smo" select="msl:datamap/dataObject[1]"/>
            </xsl:call-template>
          </xsl:element>
        </msl:datamap>
      </xsl:when>
      <xsl:otherwise>
        <xsl:apply-templates select="io2:smo" mode="map:XSLT_toencrypt_req_1"/>
      </xsl:otherwise>
    </xsl:choose>
  </xsl:template>

  <!-- This rule represents an element mapping: "io2:smo" to "io2:smo".  -->
  <xsl:template match="io2:smo"  mode="map:XSLT_toencrypt_req_1">
    <io2:smo>
      <context>
        <correlation>
          <xsl:attribute name="xsi:type">
            <xsl:value-of select="'io4:App_Context'"/>
          </xsl:attribute>
          <!-- a structural mapping: "context/correlation/io6:NCL_CruiseRetrieveClientRQ"(<Anonymous>) to "io6:NCL_CruiseRetrieveClientRQ"(<Anonymous>) -->
          <xsl:if test="context/correlation/io6:NCL_CruiseRetrieveClientRQ">
            <xsl:copy-of select="context/correlation/io6:NCL_CruiseRetrieveClientRQ"/>
          </xsl:if>
          <!-- a simple data mapping: "context/correlation/LogID"(string) to "LogID"(string) -->
          <xsl:if test="context/correlation/LogID">
            <xsl:element name="LogID">
              <xsl:value-of select="context/correlation/LogID"/>
            </xsl:element>
          </xsl:if>
          <xsl:element name="io6:NCL_CruiseRetrieveClientRS">
            <xsl:element name="io6:ClientInfo">
              <!-- a simple data mapping: "body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/birthday"(string) to "BirthDate"(StringLength1to16) -->
              <xsl:if test="body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/birthday">
                <xsl:attribute name="BirthDate">
                  <xsl:value-of select="body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/birthday"/>
                </xsl:attribute>
              </xsl:if>
              <!-- a simple data mapping: "body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/sex"(string) to "Gender"(<NMTOKEN>) -->
              <xsl:if test="body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/sex">
                <xsl:attribute name="Gender">
                  <!-- variables for custom code -->
                  <xsl:variable name="sex" select="body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/sex"/>
                  <xsl:call-template name="SexToGender">
                    <xsl:with-param name="sex" select="$sex"/>
                  </xsl:call-template>
                </xsl:attribute>
              </xsl:if>
              <!-- a simple data mapping: "body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/occupation"(string) to "GuestOccupation"(StringLength1to64) -->
              <xsl:if test="body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/occupation">
                <xsl:attribute name="GuestOccupation">
                  <xsl:value-of select="body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/occupation"/>
                </xsl:attribute>
              </xsl:if>
              <!-- a simple data mapping: "body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/client_id"(string) to "LoyaltyMembershipID"(StringLength1to32) -->
              <xsl:if test="body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/client_id">
                <xsl:attribute name="LoyaltyMembershipID">
                  <xsl:value-of select="body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/client_id"/>
                </xsl:attribute>
              </xsl:if>
              <!-- a simple data mapping: "body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/citizenship"(string) to "Nationality"(ISO3166) -->
              <xsl:if test="body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/citizenship">
                <xsl:attribute name="Nationality">
                  <xsl:value-of select="body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/citizenship"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:element name="io6:PersonName">
                <!-- a simple data mapping: "body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/title"(string) to "io6:NamePrefix"(StringLength1to16) -->
                <xsl:if test="body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/title">
                  <xsl:element name="io6:NamePrefix">
                    <xsl:value-of select="body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/title"/>
                  </xsl:element>
                </xsl:if>
                <!-- a simple data mapping: "body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/first_name"(string) to "io6:GivenName"(StringLength1to64) -->
                <xsl:if test="body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/first_name">
                  <xsl:element name="io6:GivenName">
                    <xsl:value-of select="body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/first_name"/>
                  </xsl:element>
                </xsl:if>
                <!-- a simple data mapping: "body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/middle_name"(string) to "io6:MiddleName"(StringLength1to64) -->
                <xsl:if test="body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/middle_name">
                  <xsl:element name="io6:MiddleName">
                    <xsl:value-of select="body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/middle_name"/>
                  </xsl:element>
                </xsl:if>
                <!-- a simple data mapping: "body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/last_name"(string) to "io6:Surname"(StringLength1to64) -->
                <xsl:element name="io6:Surname">
                  <xsl:value-of select="body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/last_name"/>
                </xsl:element>
              </xsl:element>
              <xsl:element name="io6:Telephone">
                <!-- a simple data mapping: "body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/phone_number"(string) to "PhoneNumber"(StringLength1to32) -->
                <xsl:attribute name="PhoneNumber">
                  <xsl:value-of select="body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/phone_number"/>
                </xsl:attribute>
                <!-- a simple data mapping: "body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/phone_type"(string) to "PhoneTechType"(OTA_CodeType) -->
                <xsl:if test="body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/phone_type">
                  <xsl:attribute name="PhoneTechType">
                    <xsl:value-of select="body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/phone_type"/>
                  </xsl:attribute>
                </xsl:if>
              </xsl:element>
              <xsl:element name="io6:Address">
                <!-- a simple data mapping: "body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/address_type"(string) to "Type"(OTA_CodeType) -->
                <xsl:if test="body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/address_type">
                  <xsl:attribute name="Type">
                    <xsl:value-of select="body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/address_type"/>
                  </xsl:attribute>
                </xsl:if>
                <!-- a simple data mapping: "body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/address_line1"(string) to "io6:AddressLine"(StringLength1to255) -->
                <xsl:if test="body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/address_line1">
                  <xsl:element name="io6:AddressLine">
                    <xsl:value-of select="body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/address_line1"/>
                  </xsl:element>
                </xsl:if>
                <!-- a simple data mapping: "body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/address_line2"(string) to "io6:AddressLine"(StringLength1to255) -->
                <xsl:if test="body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/address_line2">
                  <xsl:element name="io6:AddressLine">
                    <xsl:value-of select="body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/address_line2"/>
                  </xsl:element>
                </xsl:if>
                <!-- a simple data mapping: "body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/address_city"(string) to "io6:CityName"(StringLength1to64) -->
                <xsl:if test="body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/address_city">
                  <xsl:element name="io6:CityName">
                    <xsl:value-of select="body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/address_city"/>
                  </xsl:element>
                </xsl:if>
                <!-- a simple data mapping: "body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/zip"(string) to "io6:PostalCode"(StringLength1to16) -->
                <xsl:if test="body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/zip">
                  <xsl:element name="io6:PostalCode">
                    <xsl:value-of select="body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/zip"/>
                  </xsl:element>
                </xsl:if>
                <xsl:element name="io6:StateProv">
                  <!-- a simple data mapping: "body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/state_code"(string) to "StateCode"(StateProvCodeType) -->
                  <xsl:if test="body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/state_code">
                    <xsl:attribute name="StateCode">
                      <xsl:value-of select="body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/state_code"/>
                    </xsl:attribute>
                  </xsl:if>
                  <!-- a simple content mapping -->
                  <xsl:value-of select="body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/state_code"/>
                </xsl:element>
                <xsl:element name="io6:CountryName">
                  <!-- a simple data mapping: "body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/country_code"(string) to "Code"(ISO3166) -->
                  <xsl:if test="body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/country_code">
                    <xsl:attribute name="Code">
                      <xsl:value-of select="body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/country_code"/>
                    </xsl:attribute>
                  </xsl:if>
                </xsl:element>
              </xsl:element>
              <xsl:element name="io6:Email">
                <!-- a simple content mapping -->
                <xsl:value-of select="body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/email"/>
              </xsl:element>
            </xsl:element>
            <xsl:element name="io6:LoyaltyInfo">
              <!-- a simple data mapping: "body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/client_type"(string) to "LoyalLevel"(StringLength1to16) -->
              <xsl:if test="body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/client_type">
                <xsl:attribute name="LoyalLevel">
                  <xsl:value-of select="body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/client_type"/>
                </xsl:attribute>
              </xsl:if>
              <!-- a simple data mapping: "body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/client_id"(string) to "MembershipID"(StringLength1to32) -->
              <xsl:if test="body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/client_id">
                <xsl:attribute name="MembershipID">
                  <xsl:value-of select="body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/client_id"/>
                </xsl:attribute>
              </xsl:if>
              <!-- a simple data mapping: "body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/client_type"(string) to "ProgramID"(StringLength1to16) -->
              <xsl:if test="body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/client_type">
                <xsl:attribute name="ProgramID">
                  <xsl:value-of select="body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/client_type"/>
                </xsl:attribute>
              </xsl:if>
            </xsl:element>
            <xsl:element name="io6:UserLogin">
              <!-- a simple data mapping: "body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/web_password"(string) to "Password"(StringLength1to64) -->
              <xsl:if test="body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/web_password">
                <xsl:attribute name="Password">
                  <xsl:value-of select="body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/web_password"/>
                </xsl:attribute>
              </xsl:if>
              <!-- a simple data mapping: "body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/web_login_name"(string) to "UserLoginName"(StringLength1to64) -->
              <xsl:attribute name="UserLoginName">
                <xsl:value-of select="body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/web_login_name"/>
              </xsl:attribute>
              <!-- a simple mapping with no associated source:  to "UserType"(StringLength1to16) -->
              <xsl:attribute name="UserType">
                <xsl:value-of select="'CONSUMER'"/>
              </xsl:attribute>
            </xsl:element>
          </xsl:element>
          <!-- a simple data mapping: "context/correlation/ClientID"(string) to "ClientID"(string) -->
          <xsl:if test="context/correlation/ClientID">
            <xsl:element name="ClientID">
              <xsl:value-of select="context/correlation/ClientID"/>
            </xsl:element>
          </xsl:if>
        </correlation>
      </context>
      <xsl:element name="body">
        <xsl:attribute name="xsi:type">
          <xsl:value-of select="'out2:processEncryptDecryptRequest'"/>
        </xsl:attribute>
        <xsl:element name="out:processEncryptDecryptRequest">
          <xsl:element name="out:Encrypt_Decrypt">
            <!-- a simple mapping with no associated source:  to "out:Action"(string) -->
            <xsl:element name="out:Action">
              <xsl:text>DECRYPT</xsl:text>
            </xsl:element>
            <!-- a simple data mapping: "body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/web_password"(string) to "out:EncryptString"(string) -->
            <xsl:if test="body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/web_password">
              <xsl:element name="out:EncryptString">
                <xsl:value-of select="body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/web_password"/>
              </xsl:element>
            </xsl:if>
          </xsl:element>
        </xsl:element>
      </xsl:element>
    </io2:smo>
  </xsl:template>

  <!-- This rule represents a type mapping: "io2:smo" to "io2:smo".  -->
  <xsl:template name="map:XSLT_toencrypt_req_12">
    <xsl:param name="smo"/>
    <context>
      <correlation>
        <xsl:attribute name="xsi:type">
          <xsl:value-of select="'io4:App_Context'"/>
        </xsl:attribute>
        <!-- a structural mapping: "$smo/context/correlation/io6:NCL_CruiseRetrieveClientRQ"(<Anonymous>) to "io6:NCL_CruiseRetrieveClientRQ"(<Anonymous>) -->
        <xsl:if test="$smo/context/correlation/io6:NCL_CruiseRetrieveClientRQ">
          <xsl:copy-of select="$smo/context/correlation/io6:NCL_CruiseRetrieveClientRQ"/>
        </xsl:if>
        <!-- a simple data mapping: "$smo/context/correlation/LogID"(string) to "LogID"(string) -->
        <xsl:if test="$smo/context/correlation/LogID">
          <xsl:element name="LogID">
            <xsl:value-of select="$smo/context/correlation/LogID"/>
          </xsl:element>
        </xsl:if>
        <xsl:element name="io6:NCL_CruiseRetrieveClientRS">
          <xsl:element name="io6:ClientInfo">
            <!-- a simple data mapping: "$smo/body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/birthday"(string) to "BirthDate"(StringLength1to16) -->
            <xsl:if test="$smo/body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/birthday">
              <xsl:attribute name="BirthDate">
                <xsl:value-of select="$smo/body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/birthday"/>
              </xsl:attribute>
            </xsl:if>
            <!-- a simple data mapping: "$smo/body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/sex"(string) to "Gender"(<NMTOKEN>) -->
            <xsl:if test="$smo/body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/sex">
              <xsl:attribute name="Gender">
                <!-- variables for custom code -->
                <xsl:variable name="sex" select="$smo/body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/sex"/>
                <xsl:call-template name="SexToGender">
                  <xsl:with-param name="sex" select="$sex"/>
                </xsl:call-template>
              </xsl:attribute>
            </xsl:if>
            <!-- a simple data mapping: "$smo/body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/occupation"(string) to "GuestOccupation"(StringLength1to64) -->
            <xsl:if test="$smo/body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/occupation">
              <xsl:attribute name="GuestOccupation">
                <xsl:value-of select="$smo/body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/occupation"/>
              </xsl:attribute>
            </xsl:if>
            <!-- a simple data mapping: "$smo/body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/client_id"(string) to "LoyaltyMembershipID"(StringLength1to32) -->
            <xsl:if test="$smo/body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/client_id">
              <xsl:attribute name="LoyaltyMembershipID">
                <xsl:value-of select="$smo/body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/client_id"/>
              </xsl:attribute>
            </xsl:if>
            <!-- a simple data mapping: "$smo/body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/citizenship"(string) to "Nationality"(ISO3166) -->
            <xsl:if test="$smo/body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/citizenship">
              <xsl:attribute name="Nationality">
                <xsl:value-of select="$smo/body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/citizenship"/>
              </xsl:attribute>
            </xsl:if>
            <xsl:element name="io6:PersonName">
              <!-- a simple data mapping: "$smo/body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/title"(string) to "io6:NamePrefix"(StringLength1to16) -->
              <xsl:if test="$smo/body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/title">
                <xsl:element name="io6:NamePrefix">
                  <xsl:value-of select="$smo/body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/title"/>
                </xsl:element>
              </xsl:if>
              <!-- a simple data mapping: "$smo/body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/first_name"(string) to "io6:GivenName"(StringLength1to64) -->
              <xsl:if test="$smo/body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/first_name">
                <xsl:element name="io6:GivenName">
                  <xsl:value-of select="$smo/body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/first_name"/>
                </xsl:element>
              </xsl:if>
              <!-- a simple data mapping: "$smo/body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/middle_name"(string) to "io6:MiddleName"(StringLength1to64) -->
              <xsl:if test="$smo/body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/middle_name">
                <xsl:element name="io6:MiddleName">
                  <xsl:value-of select="$smo/body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/middle_name"/>
                </xsl:element>
              </xsl:if>
              <!-- a simple data mapping: "$smo/body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/last_name"(string) to "io6:Surname"(StringLength1to64) -->
              <xsl:element name="io6:Surname">
                <xsl:value-of select="$smo/body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/last_name"/>
              </xsl:element>
            </xsl:element>
            <xsl:element name="io6:Telephone">
              <!-- a simple data mapping: "$smo/body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/phone_number"(string) to "PhoneNumber"(StringLength1to32) -->
              <xsl:attribute name="PhoneNumber">
                <xsl:value-of select="$smo/body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/phone_number"/>
              </xsl:attribute>
              <!-- a simple data mapping: "$smo/body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/phone_type"(string) to "PhoneTechType"(OTA_CodeType) -->
              <xsl:if test="$smo/body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/phone_type">
                <xsl:attribute name="PhoneTechType">
                  <xsl:value-of select="$smo/body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/phone_type"/>
                </xsl:attribute>
              </xsl:if>
            </xsl:element>
            <xsl:element name="io6:Address">
              <!-- a simple data mapping: "$smo/body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/address_type"(string) to "Type"(OTA_CodeType) -->
              <xsl:if test="$smo/body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/address_type">
                <xsl:attribute name="Type">
                  <xsl:value-of select="$smo/body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/address_type"/>
                </xsl:attribute>
              </xsl:if>
              <!-- a simple data mapping: "$smo/body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/address_line1"(string) to "io6:AddressLine"(StringLength1to255) -->
              <xsl:if test="$smo/body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/address_line1">
                <xsl:element name="io6:AddressLine">
                  <xsl:value-of select="$smo/body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/address_line1"/>
                </xsl:element>
              </xsl:if>
              <!-- a simple data mapping: "$smo/body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/address_line2"(string) to "io6:AddressLine"(StringLength1to255) -->
              <xsl:if test="$smo/body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/address_line2">
                <xsl:element name="io6:AddressLine">
                  <xsl:value-of select="$smo/body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/address_line2"/>
                </xsl:element>
              </xsl:if>
              <!-- a simple data mapping: "$smo/body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/address_city"(string) to "io6:CityName"(StringLength1to64) -->
              <xsl:if test="$smo/body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/address_city">
                <xsl:element name="io6:CityName">
                  <xsl:value-of select="$smo/body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/address_city"/>
                </xsl:element>
              </xsl:if>
              <!-- a simple data mapping: "$smo/body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/zip"(string) to "io6:PostalCode"(StringLength1to16) -->
              <xsl:if test="$smo/body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/zip">
                <xsl:element name="io6:PostalCode">
                  <xsl:value-of select="$smo/body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/zip"/>
                </xsl:element>
              </xsl:if>
              <xsl:element name="io6:StateProv">
                <!-- a simple data mapping: "$smo/body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/state_code"(string) to "StateCode"(StateProvCodeType) -->
                <xsl:if test="$smo/body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/state_code">
                  <xsl:attribute name="StateCode">
                    <xsl:value-of select="$smo/body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/state_code"/>
                  </xsl:attribute>
                </xsl:if>
                <!-- a simple content mapping -->
                <xsl:value-of select="$smo/body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/state_code"/>
              </xsl:element>
              <xsl:element name="io6:CountryName">
                <!-- a simple data mapping: "$smo/body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/country_code"(string) to "Code"(ISO3166) -->
                <xsl:if test="$smo/body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/country_code">
                  <xsl:attribute name="Code">
                    <xsl:value-of select="$smo/body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/country_code"/>
                  </xsl:attribute>
                </xsl:if>
              </xsl:element>
            </xsl:element>
            <xsl:element name="io6:Email">
              <!-- a simple content mapping -->
              <xsl:value-of select="$smo/body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/email"/>
            </xsl:element>
          </xsl:element>
          <xsl:element name="io6:LoyaltyInfo">
            <!-- a simple data mapping: "$smo/body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/client_type"(string) to "LoyalLevel"(StringLength1to16) -->
            <xsl:if test="$smo/body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/client_type">
              <xsl:attribute name="LoyalLevel">
                <xsl:value-of select="$smo/body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/client_type"/>
              </xsl:attribute>
            </xsl:if>
            <!-- a simple data mapping: "$smo/body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/client_id"(string) to "MembershipID"(StringLength1to32) -->
            <xsl:if test="$smo/body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/client_id">
              <xsl:attribute name="MembershipID">
                <xsl:value-of select="$smo/body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/client_id"/>
              </xsl:attribute>
            </xsl:if>
            <!-- a simple data mapping: "$smo/body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/client_type"(string) to "ProgramID"(StringLength1to16) -->
            <xsl:if test="$smo/body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/client_type">
              <xsl:attribute name="ProgramID">
                <xsl:value-of select="$smo/body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/client_type"/>
              </xsl:attribute>
            </xsl:if>
          </xsl:element>
          <xsl:element name="io6:UserLogin">
            <!-- a simple data mapping: "$smo/body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/web_password"(string) to "Password"(StringLength1to64) -->
            <xsl:if test="$smo/body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/web_password">
              <xsl:attribute name="Password">
                <xsl:value-of select="$smo/body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/web_password"/>
              </xsl:attribute>
            </xsl:if>
            <!-- a simple data mapping: "$smo/body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/web_login_name"(string) to "UserLoginName"(StringLength1to64) -->
            <xsl:attribute name="UserLoginName">
              <xsl:value-of select="$smo/body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/web_login_name"/>
            </xsl:attribute>
            <!-- a simple mapping with no associated source:  to "UserType"(StringLength1to16) -->
            <xsl:attribute name="UserType">
              <xsl:value-of select="'CONSUMER'"/>
            </xsl:attribute>
          </xsl:element>
        </xsl:element>
        <!-- a simple data mapping: "$smo/context/correlation/ClientID"(string) to "ClientID"(string) -->
        <xsl:if test="$smo/context/correlation/ClientID">
          <xsl:element name="ClientID">
            <xsl:value-of select="$smo/context/correlation/ClientID"/>
          </xsl:element>
        </xsl:if>
      </correlation>
    </context>
    <xsl:element name="body">
      <xsl:attribute name="xsi:type">
        <xsl:value-of select="'out2:processEncryptDecryptRequest'"/>
      </xsl:attribute>
      <xsl:element name="out:processEncryptDecryptRequest">
        <xsl:element name="out:Encrypt_Decrypt">
          <!-- a simple mapping with no associated source:  to "out:Action"(string) -->
          <xsl:element name="out:Action">
            <xsl:text>DECRYPT</xsl:text>
          </xsl:element>
          <!-- a simple data mapping: "$smo/body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/web_password"(string) to "out:EncryptString"(string) -->
          <xsl:if test="$smo/body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/web_password">
            <xsl:element name="out:EncryptString">
              <xsl:value-of select="$smo/body/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Response/in5:executeNclseaNcl_Wesb_Get_Client_Prof_V1Output/p_cursor[1]/web_password"/>
            </xsl:element>
          </xsl:if>
        </xsl:element>
      </xsl:element>
    </xsl:element>
  </xsl:template>

  <!-- *****************    Utility Templates    ******************  -->
  <!-- copy the namespace declarations from the source to the target -->
  <xsl:template name="copyNamespaceDeclarations">
    <xsl:param name="root"/>
    <xsl:for-each select="$root/namespace::*[not(name() = '')]">
      <xsl:copy/>
    </xsl:for-each>
  </xsl:template>
</xsl:stylesheet>
