<?xml version="1.0" encoding="UTF-8"?>
<!-- @generated mapFile="xslt/XSLTransformation3_req_1.map" md5sum="931b91b10f051fdc0f32965f90107e50" version="7.6.100" -->
<!--
*****************************************************************************
*   This file has been generated by the IBM XML Mapping Editor.
*
*   Mapping file:		XSLTransformation3_req_1.map
*   Map declaration(s):	XSLTransformation3_req_1
*   Input file(s):		smo://smo/name%3Dwsdl-primary/correlationContext%3D%257Bhttp%253A%252F%252FNCL_CruiseRetrieveClient_Module%257DApp_Context/message%3D%257Bhttp%253A%252F%252FNCL_CruiseRetrieveClient_Module%252FDB_Lookup%257DexecuteNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponseMsg/xpath%3D%252F/smo.xsd
*   Output file(s):		smo://smo/name%3Dwsdl-primary/correlationContext%3D%257Bhttp%253A%252F%252FNCL_CruiseRetrieveClient_Module%257DApp_Context/message%3D%257Bhttp%253A%252F%252FNCL_WESB_Shared_Library%252FNCL_CruiseRetrieveClient_Interface%257DPerform_NCL_CruiseRetrieveClientResponseMsg/xpath%3D%252F/smo.xsd
*
*   Note: Do not modify the contents of this file as it is overwritten
*         each time the mapping model is updated.
*****************************************************************************
-->
<xsl:stylesheet
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xalan="http://xml.apache.org/xslt"
    xmlns:str="http://exslt.org/strings"
    xmlns:set="http://exslt.org/sets"
    xmlns:math="http://exslt.org/math"
    xmlns:fn="http://www.w3.org/2005/xpath-functions"
    xmlns:regexp="http://exslt.org/regular-expressions"
    xmlns:dyn="http://exslt.org/dynamic"
    xmlns:dp="http://www.datapower.com/extensions"
    xmlns:exsl="http://exslt.org/common"
    xmlns:date="http://exslt.org/dates-and-times"
    xmlns:in="http://NCL_CruiseRetrieveClient_Module/DB_Lookup"
    xmlns:in2="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/nclseancl_wesb_get_client_programs"
    xmlns:in3="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/nclseancl_wesb_get_client_programsp_cursor"
    xmlns:in4="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/nclseancl_wesb_get_client_programsbg"
    xmlns:in5="wsdl.http://NCL_CruiseRetrieveClient_Module/DB_Lookup"
    xmlns:in9="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/nclseancl_wesb_get_client_vacat_pref"
    xmlns:in10="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/nclseancl_wesb_get_client_vacat_prefbg"
    xmlns:in6="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/nclseancl_wesb_get_client_profile"
    xmlns:in8="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/nclseancl_wesb_get_client_profilebg"
    xmlns:in7="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/nclseancl_wesb_get_client_profilep_cursor"
    xmlns:in11="http://www.ibm.com/xmlns/prod/websphere/bo/6.0.0"
    xmlns:in12="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/nclseancl_wesb_get_client_vacat_prefp_prev_crus_cur"
    xmlns:in13="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/nclseancl_wesb_get_client_vacat_prefp_dest_cur"
    xmlns:io="http://www.w3.org/2003/05/soap-envelope"
    xmlns:io3="http://www.ibm.com/xmlns/prod/websphere/mq/sca/6.0.0"
    xmlns:io2="http://www.ibm.com/websphere/sibx/smo/v6.0.1"
    xmlns:out="http://NCL_WESB_Shared_Library/NCL_CruiseRetrieveClient_Interface"
    xmlns:io4="http://NCL_CruiseRetrieveClient_Module"
    xmlns:io5="http://schemas.xmlsoap.org/ws/2004/08/addressing"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:io7="http://www.ibm.com/xmlns/prod/websphere/http/sca/6.1.0"
    xmlns:io6="http://nclapi/schemas"
    xmlns:out2="wsdl.http://NCL_WESB_Shared_Library/NCL_CruiseRetrieveClient_Interface"
    xmlns:xs4xs="http://www.w3.org/2001/XMLSchema"
    xmlns:io8="http://www.w3.org/2005/08/addressing"
    xmlns:map="http://NCL_CruiseRetrieveClient_Module/xslt/XSLTransformation3_req_1"
    xmlns:msl="http://www.ibm.com/xmlmap"
    exclude-result-prefixes="in in2 in3 in4 in5 in9 in10 in6 in8 in7 in11 in12 in13 str set math fn regexp dyn dp exsl date map xalan msl"
    version="1.0">
  <xsl:output method="xml" encoding="UTF-8" indent="no"/>

  <!-- root wrapper template  -->
  <xsl:template match="/">
    <xsl:choose>
      <xsl:when test="msl:datamap">
        <msl:datamap>
          <xsl:element name="dataObject">
            <xsl:attribute name="xsi:type">
              <xsl:value-of select="'io2:ServiceMessageObject'"/>
            </xsl:attribute>
            <xsl:call-template name="map:XSLTransformation3_req_12">
              <xsl:with-param name="smo" select="msl:datamap/dataObject[1]"/>
            </xsl:call-template>
          </xsl:element>
        </msl:datamap>
      </xsl:when>
      <xsl:otherwise>
        <xsl:apply-templates select="io2:smo" mode="map:XSLTransformation3_req_1"/>
      </xsl:otherwise>
    </xsl:choose>
  </xsl:template>

  <!-- This rule represents an element mapping: "io2:smo" to "io2:smo".  -->
  <xsl:template match="io2:smo"  mode="map:XSLTransformation3_req_1">
    <io2:smo>
      <context>
        <correlation>
          <xsl:attribute name="xsi:type">
            <xsl:value-of select="'io4:App_Context'"/>
          </xsl:attribute>
          <!-- a structural mapping: "context/correlation/io6:NCL_CruiseRetrieveClientRQ"(<Anonymous>) to "io6:NCL_CruiseRetrieveClientRQ"(<Anonymous>) -->
          <xsl:if test="context/correlation/io6:NCL_CruiseRetrieveClientRQ">
            <xsl:copy-of select="context/correlation/io6:NCL_CruiseRetrieveClientRQ"/>
          </xsl:if>
          <!-- a simple data mapping: "context/correlation/LogID"(string) to "LogID"(string) -->
          <xsl:if test="context/correlation/LogID">
            <xsl:element name="LogID">
              <xsl:value-of select="context/correlation/LogID"/>
            </xsl:element>
          </xsl:if>
          <xsl:element name="io6:NCL_CruiseRetrieveClientRS">
            <!-- a structural mapping: "context/correlation/io6:NCL_CruiseRetrieveClientRS/io6:ClientInfo"(<Anonymous>) to "io6:ClientInfo"(<Anonymous>) -->
            <xsl:if test="context/correlation/io6:NCL_CruiseRetrieveClientRS/io6:ClientInfo">
              <xsl:copy-of select="context/correlation/io6:NCL_CruiseRetrieveClientRS/io6:ClientInfo"/>
            </xsl:if>
            <!-- a structural mapping: "context/correlation/io6:NCL_CruiseRetrieveClientRS/io6:LoyaltyInfo"(<Anonymous>) to "io6:LoyaltyInfo"(<Anonymous>) -->
            <xsl:if test="context/correlation/io6:NCL_CruiseRetrieveClientRS/io6:LoyaltyInfo">
              <xsl:copy-of select="context/correlation/io6:NCL_CruiseRetrieveClientRS/io6:LoyaltyInfo"/>
            </xsl:if>
            <!-- a structural mapping: "context/correlation/io6:NCL_CruiseRetrieveClientRS/io6:UserLogin"(<Anonymous>) to "io6:UserLogin"(<Anonymous>) -->
            <xsl:if test="context/correlation/io6:NCL_CruiseRetrieveClientRS/io6:UserLogin">
              <xsl:copy-of select="context/correlation/io6:NCL_CruiseRetrieveClientRS/io6:UserLogin"/>
            </xsl:if>
            <xsl:element name="io6:VacationPreference">
              <!-- a simple data mapping: "body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_future_cruise_plan"(string) to "FutureCruisePlan"(StringLength0to128) -->
              <xsl:if test="body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_future_cruise_plan">
                <xsl:attribute name="FutureCruisePlan">
                  <xsl:value-of select="body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_future_cruise_plan"/>
                </xsl:attribute>
              </xsl:if>
              <!-- a simple data mapping: "body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_pref_booking_mode"(string) to "PreferredBookingMode"(StringLength0to128) -->
              <xsl:if test="body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_pref_booking_mode">
                <xsl:attribute name="PreferredBookingMode">
                  <xsl:value-of select="body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_pref_booking_mode"/>
                </xsl:attribute>
              </xsl:if>
              <!-- a simple data mapping: "body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_prefcruiselength"(string) to "PreferredCruiseLength"(StringLength0to128) -->
              <xsl:if test="body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_prefcruiselength">
                <xsl:attribute name="PreferredCruiseLength">
                  <xsl:value-of select="body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_prefcruiselength"/>
                </xsl:attribute>
              </xsl:if>
              <!-- a simple data mapping: "body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_pref_cruise_time"(string) to "PreferredCruiseTime"(StringLength0to128) -->
              <xsl:if test="body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_pref_cruise_time">
                <xsl:attribute name="PreferredCruiseTime">
                  <xsl:value-of select="body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_pref_cruise_time"/>
                </xsl:attribute>
              </xsl:if>
              <!-- a simple data mapping: "body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_previously_cruised"(string) to "PreviouslyCruised"(StringLength0to32) -->
              <xsl:if test="body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_previously_cruised">
                <xsl:attribute name="PreviouslyCruised">
                  <xsl:value-of select="body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_previously_cruised"/>
                </xsl:attribute>
              </xsl:if>
              <!-- a simple data mapping: "body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_previously_cruised_number"(string) to "PreviouslyCruisedNumber"(StringLength0to32) -->
              <xsl:if test="body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_previously_cruised_number">
                <xsl:attribute name="PreviouslyCruisedNumber">
                  <xsl:value-of select="body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_previously_cruised_number"/>
                </xsl:attribute>
              </xsl:if>
              <!-- a simple data mapping: "body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_dest_cur[1]/desired_destination"(string) to "io6:DesiredDestination"(StringLength0to128) -->
              <xsl:if test="body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_dest_cur[1]/desired_destination">
                <xsl:element name="io6:DesiredDestination">
                  <xsl:value-of select="body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_dest_cur[1]/desired_destination"/>
                </xsl:element>
              </xsl:if>
              <!-- a simple data mapping: "body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_dest_cur[2]/desired_destination"(string) to "io6:DesiredDestination"(StringLength0to128) -->
              <xsl:if test="body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_dest_cur[2]/desired_destination">
                <xsl:element name="io6:DesiredDestination">
                  <xsl:value-of select="body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_dest_cur[2]/desired_destination"/>
                </xsl:element>
              </xsl:if>
              <!-- a simple data mapping: "body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_dest_cur[3]/desired_destination"(string) to "io6:DesiredDestination"(StringLength0to128) -->
              <xsl:if test="body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_dest_cur[3]/desired_destination">
                <xsl:element name="io6:DesiredDestination">
                  <xsl:value-of select="body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_dest_cur[3]/desired_destination"/>
                </xsl:element>
              </xsl:if>
              <!-- a simple data mapping: "body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_dest_cur[4]/desired_destination"(string) to "io6:DesiredDestination"(StringLength0to128) -->
              <xsl:if test="body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_dest_cur[4]/desired_destination">
                <xsl:element name="io6:DesiredDestination">
                  <xsl:value-of select="body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_dest_cur[4]/desired_destination"/>
                </xsl:element>
              </xsl:if>
              <!-- a simple data mapping: "body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_dest_cur[5]/desired_destination"(string) to "io6:DesiredDestination"(StringLength0to128) -->
              <xsl:if test="body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_dest_cur[5]/desired_destination">
                <xsl:element name="io6:DesiredDestination">
                  <xsl:value-of select="body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_dest_cur[5]/desired_destination"/>
                </xsl:element>
              </xsl:if>
              <!-- a simple data mapping: "body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_dest_cur[6]/desired_destination"(string) to "io6:DesiredDestination"(StringLength0to128) -->
              <xsl:if test="body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_dest_cur[6]/desired_destination">
                <xsl:element name="io6:DesiredDestination">
                  <xsl:value-of select="body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_dest_cur[6]/desired_destination"/>
                </xsl:element>
              </xsl:if>
              <!-- a simple data mapping: "body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_dest_cur[7]/desired_destination"(string) to "io6:DesiredDestination"(StringLength0to128) -->
              <xsl:if test="body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_dest_cur[7]/desired_destination">
                <xsl:element name="io6:DesiredDestination">
                  <xsl:value-of select="body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_dest_cur[7]/desired_destination"/>
                </xsl:element>
              </xsl:if>
              <!-- a simple data mapping: "body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_dest_cur[8]/desired_destination"(string) to "io6:DesiredDestination"(StringLength0to128) -->
              <xsl:if test="body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_dest_cur[8]/desired_destination">
                <xsl:element name="io6:DesiredDestination">
                  <xsl:value-of select="body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_dest_cur[8]/desired_destination"/>
                </xsl:element>
              </xsl:if>
              <!-- a simple data mapping: "body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_dest_cur[9]/desired_destination"(string) to "io6:DesiredDestination"(StringLength0to128) -->
              <xsl:if test="body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_dest_cur[9]/desired_destination">
                <xsl:element name="io6:DesiredDestination">
                  <xsl:value-of select="body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_dest_cur[9]/desired_destination"/>
                </xsl:element>
              </xsl:if>
              <!-- a simple data mapping: "body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_dest_cur[10]/desired_destination"(string) to "io6:DesiredDestination"(StringLength0to128) -->
              <xsl:if test="body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_dest_cur[10]/desired_destination">
                <xsl:element name="io6:DesiredDestination">
                  <xsl:value-of select="body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_dest_cur[10]/desired_destination"/>
                </xsl:element>
              </xsl:if>
              <!-- a simple data mapping: "body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_prev_crus_cur[1]/previous_cruise_line"(string) to "io6:PreviousCruiseLines"(StringLength0to128) -->
              <xsl:if test="body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_prev_crus_cur[1]/previous_cruise_line">
                <xsl:element name="io6:PreviousCruiseLines">
                  <xsl:value-of select="body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_prev_crus_cur[1]/previous_cruise_line"/>
                </xsl:element>
              </xsl:if>
              <!-- a simple data mapping: "body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_prev_crus_cur[2]/previous_cruise_line"(string) to "io6:PreviousCruiseLines"(StringLength0to128) -->
              <xsl:if test="body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_prev_crus_cur[2]/previous_cruise_line">
                <xsl:element name="io6:PreviousCruiseLines">
                  <xsl:value-of select="body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_prev_crus_cur[2]/previous_cruise_line"/>
                </xsl:element>
              </xsl:if>
              <!-- a simple data mapping: "body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_prev_crus_cur[3]/previous_cruise_line"(string) to "io6:PreviousCruiseLines"(StringLength0to128) -->
              <xsl:if test="body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_prev_crus_cur[3]/previous_cruise_line">
                <xsl:element name="io6:PreviousCruiseLines">
                  <xsl:value-of select="body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_prev_crus_cur[3]/previous_cruise_line"/>
                </xsl:element>
              </xsl:if>
              <!-- a simple data mapping: "body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_prev_crus_cur[4]/previous_cruise_line"(string) to "io6:PreviousCruiseLines"(StringLength0to128) -->
              <xsl:if test="body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_prev_crus_cur[4]/previous_cruise_line">
                <xsl:element name="io6:PreviousCruiseLines">
                  <xsl:value-of select="body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_prev_crus_cur[4]/previous_cruise_line"/>
                </xsl:element>
              </xsl:if>
              <!-- a simple data mapping: "body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_prev_crus_cur[5]/previous_cruise_line"(string) to "io6:PreviousCruiseLines"(StringLength0to128) -->
              <xsl:if test="body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_prev_crus_cur[5]/previous_cruise_line">
                <xsl:element name="io6:PreviousCruiseLines">
                  <xsl:value-of select="body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_prev_crus_cur[5]/previous_cruise_line"/>
                </xsl:element>
              </xsl:if>
              <!-- a simple data mapping: "body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_prev_crus_cur[6]/previous_cruise_line"(string) to "io6:PreviousCruiseLines"(StringLength0to128) -->
              <xsl:if test="body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_prev_crus_cur[6]/previous_cruise_line">
                <xsl:element name="io6:PreviousCruiseLines">
                  <xsl:value-of select="body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_prev_crus_cur[6]/previous_cruise_line"/>
                </xsl:element>
              </xsl:if>
              <!-- a simple data mapping: "body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_prev_crus_cur[7]/previous_cruise_line"(string) to "io6:PreviousCruiseLines"(StringLength0to128) -->
              <xsl:if test="body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_prev_crus_cur[7]/previous_cruise_line">
                <xsl:element name="io6:PreviousCruiseLines">
                  <xsl:value-of select="body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_prev_crus_cur[7]/previous_cruise_line"/>
                </xsl:element>
              </xsl:if>
              <!-- a simple data mapping: "body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_prev_crus_cur[8]/previous_cruise_line"(string) to "io6:PreviousCruiseLines"(StringLength0to128) -->
              <xsl:if test="body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_prev_crus_cur[8]/previous_cruise_line">
                <xsl:element name="io6:PreviousCruiseLines">
                  <xsl:value-of select="body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_prev_crus_cur[8]/previous_cruise_line"/>
                </xsl:element>
              </xsl:if>
              <!-- a simple data mapping: "body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_prev_crus_cur[9]/previous_cruise_line"(string) to "io6:PreviousCruiseLines"(StringLength0to128) -->
              <xsl:if test="body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_prev_crus_cur[9]/previous_cruise_line">
                <xsl:element name="io6:PreviousCruiseLines">
                  <xsl:value-of select="body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_prev_crus_cur[9]/previous_cruise_line"/>
                </xsl:element>
              </xsl:if>
              <!-- a simple data mapping: "body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_prev_crus_cur[10]/previous_cruise_line"(string) to "io6:PreviousCruiseLines"(StringLength0to128) -->
              <xsl:if test="body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_prev_crus_cur[10]/previous_cruise_line">
                <xsl:element name="io6:PreviousCruiseLines">
                  <xsl:value-of select="body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_prev_crus_cur[10]/previous_cruise_line"/>
                </xsl:element>
              </xsl:if>
            </xsl:element>
          </xsl:element>
          <!-- a simple data mapping: "context/correlation/ClientID"(string) to "ClientID"(string) -->
          <xsl:if test="context/correlation/ClientID">
            <xsl:element name="ClientID">
              <xsl:value-of select="context/correlation/ClientID"/>
            </xsl:element>
          </xsl:if>
        </correlation>
      </context>
    </io2:smo>
  </xsl:template>

  <!-- This rule represents a type mapping: "io2:smo" to "io2:smo".  -->
  <xsl:template name="map:XSLTransformation3_req_12">
    <xsl:param name="smo"/>
    <context>
      <correlation>
        <xsl:attribute name="xsi:type">
          <xsl:value-of select="'io4:App_Context'"/>
        </xsl:attribute>
        <!-- a structural mapping: "$smo/context/correlation/io6:NCL_CruiseRetrieveClientRQ"(<Anonymous>) to "io6:NCL_CruiseRetrieveClientRQ"(<Anonymous>) -->
        <xsl:if test="$smo/context/correlation/io6:NCL_CruiseRetrieveClientRQ">
          <xsl:copy-of select="$smo/context/correlation/io6:NCL_CruiseRetrieveClientRQ"/>
        </xsl:if>
        <!-- a simple data mapping: "$smo/context/correlation/LogID"(string) to "LogID"(string) -->
        <xsl:if test="$smo/context/correlation/LogID">
          <xsl:element name="LogID">
            <xsl:value-of select="$smo/context/correlation/LogID"/>
          </xsl:element>
        </xsl:if>
        <xsl:element name="io6:NCL_CruiseRetrieveClientRS">
          <!-- a structural mapping: "$smo/context/correlation/io6:NCL_CruiseRetrieveClientRS/io6:ClientInfo"(<Anonymous>) to "io6:ClientInfo"(<Anonymous>) -->
          <xsl:if test="$smo/context/correlation/io6:NCL_CruiseRetrieveClientRS/io6:ClientInfo">
            <xsl:copy-of select="$smo/context/correlation/io6:NCL_CruiseRetrieveClientRS/io6:ClientInfo"/>
          </xsl:if>
          <!-- a structural mapping: "$smo/context/correlation/io6:NCL_CruiseRetrieveClientRS/io6:LoyaltyInfo"(<Anonymous>) to "io6:LoyaltyInfo"(<Anonymous>) -->
          <xsl:if test="$smo/context/correlation/io6:NCL_CruiseRetrieveClientRS/io6:LoyaltyInfo">
            <xsl:copy-of select="$smo/context/correlation/io6:NCL_CruiseRetrieveClientRS/io6:LoyaltyInfo"/>
          </xsl:if>
          <!-- a structural mapping: "$smo/context/correlation/io6:NCL_CruiseRetrieveClientRS/io6:UserLogin"(<Anonymous>) to "io6:UserLogin"(<Anonymous>) -->
          <xsl:if test="$smo/context/correlation/io6:NCL_CruiseRetrieveClientRS/io6:UserLogin">
            <xsl:copy-of select="$smo/context/correlation/io6:NCL_CruiseRetrieveClientRS/io6:UserLogin"/>
          </xsl:if>
          <xsl:element name="io6:VacationPreference">
            <!-- a simple data mapping: "$smo/body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_future_cruise_plan"(string) to "FutureCruisePlan"(StringLength0to128) -->
            <xsl:if test="$smo/body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_future_cruise_plan">
              <xsl:attribute name="FutureCruisePlan">
                <xsl:value-of select="$smo/body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_future_cruise_plan"/>
              </xsl:attribute>
            </xsl:if>
            <!-- a simple data mapping: "$smo/body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_pref_booking_mode"(string) to "PreferredBookingMode"(StringLength0to128) -->
            <xsl:if test="$smo/body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_pref_booking_mode">
              <xsl:attribute name="PreferredBookingMode">
                <xsl:value-of select="$smo/body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_pref_booking_mode"/>
              </xsl:attribute>
            </xsl:if>
            <!-- a simple data mapping: "$smo/body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_prefcruiselength"(string) to "PreferredCruiseLength"(StringLength0to128) -->
            <xsl:if test="$smo/body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_prefcruiselength">
              <xsl:attribute name="PreferredCruiseLength">
                <xsl:value-of select="$smo/body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_prefcruiselength"/>
              </xsl:attribute>
            </xsl:if>
            <!-- a simple data mapping: "$smo/body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_pref_cruise_time"(string) to "PreferredCruiseTime"(StringLength0to128) -->
            <xsl:if test="$smo/body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_pref_cruise_time">
              <xsl:attribute name="PreferredCruiseTime">
                <xsl:value-of select="$smo/body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_pref_cruise_time"/>
              </xsl:attribute>
            </xsl:if>
            <!-- a simple data mapping: "$smo/body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_previously_cruised"(string) to "PreviouslyCruised"(StringLength0to32) -->
            <xsl:if test="$smo/body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_previously_cruised">
              <xsl:attribute name="PreviouslyCruised">
                <xsl:value-of select="$smo/body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_previously_cruised"/>
              </xsl:attribute>
            </xsl:if>
            <!-- a simple data mapping: "$smo/body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_previously_cruised_number"(string) to "PreviouslyCruisedNumber"(StringLength0to32) -->
            <xsl:if test="$smo/body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_previously_cruised_number">
              <xsl:attribute name="PreviouslyCruisedNumber">
                <xsl:value-of select="$smo/body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_previously_cruised_number"/>
              </xsl:attribute>
            </xsl:if>
            <!-- a simple data mapping: "$smo/body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_dest_cur[1]/desired_destination"(string) to "io6:DesiredDestination"(StringLength0to128) -->
            <xsl:if test="$smo/body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_dest_cur[1]/desired_destination">
              <xsl:element name="io6:DesiredDestination">
                <xsl:value-of select="$smo/body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_dest_cur[1]/desired_destination"/>
              </xsl:element>
            </xsl:if>
            <!-- a simple data mapping: "$smo/body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_dest_cur[2]/desired_destination"(string) to "io6:DesiredDestination"(StringLength0to128) -->
            <xsl:if test="$smo/body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_dest_cur[2]/desired_destination">
              <xsl:element name="io6:DesiredDestination">
                <xsl:value-of select="$smo/body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_dest_cur[2]/desired_destination"/>
              </xsl:element>
            </xsl:if>
            <!-- a simple data mapping: "$smo/body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_dest_cur[3]/desired_destination"(string) to "io6:DesiredDestination"(StringLength0to128) -->
            <xsl:if test="$smo/body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_dest_cur[3]/desired_destination">
              <xsl:element name="io6:DesiredDestination">
                <xsl:value-of select="$smo/body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_dest_cur[3]/desired_destination"/>
              </xsl:element>
            </xsl:if>
            <!-- a simple data mapping: "$smo/body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_dest_cur[4]/desired_destination"(string) to "io6:DesiredDestination"(StringLength0to128) -->
            <xsl:if test="$smo/body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_dest_cur[4]/desired_destination">
              <xsl:element name="io6:DesiredDestination">
                <xsl:value-of select="$smo/body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_dest_cur[4]/desired_destination"/>
              </xsl:element>
            </xsl:if>
            <!-- a simple data mapping: "$smo/body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_dest_cur[5]/desired_destination"(string) to "io6:DesiredDestination"(StringLength0to128) -->
            <xsl:if test="$smo/body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_dest_cur[5]/desired_destination">
              <xsl:element name="io6:DesiredDestination">
                <xsl:value-of select="$smo/body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_dest_cur[5]/desired_destination"/>
              </xsl:element>
            </xsl:if>
            <!-- a simple data mapping: "$smo/body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_dest_cur[6]/desired_destination"(string) to "io6:DesiredDestination"(StringLength0to128) -->
            <xsl:if test="$smo/body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_dest_cur[6]/desired_destination">
              <xsl:element name="io6:DesiredDestination">
                <xsl:value-of select="$smo/body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_dest_cur[6]/desired_destination"/>
              </xsl:element>
            </xsl:if>
            <!-- a simple data mapping: "$smo/body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_dest_cur[7]/desired_destination"(string) to "io6:DesiredDestination"(StringLength0to128) -->
            <xsl:if test="$smo/body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_dest_cur[7]/desired_destination">
              <xsl:element name="io6:DesiredDestination">
                <xsl:value-of select="$smo/body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_dest_cur[7]/desired_destination"/>
              </xsl:element>
            </xsl:if>
            <!-- a simple data mapping: "$smo/body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_dest_cur[8]/desired_destination"(string) to "io6:DesiredDestination"(StringLength0to128) -->
            <xsl:if test="$smo/body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_dest_cur[8]/desired_destination">
              <xsl:element name="io6:DesiredDestination">
                <xsl:value-of select="$smo/body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_dest_cur[8]/desired_destination"/>
              </xsl:element>
            </xsl:if>
            <!-- a simple data mapping: "$smo/body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_dest_cur[9]/desired_destination"(string) to "io6:DesiredDestination"(StringLength0to128) -->
            <xsl:if test="$smo/body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_dest_cur[9]/desired_destination">
              <xsl:element name="io6:DesiredDestination">
                <xsl:value-of select="$smo/body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_dest_cur[9]/desired_destination"/>
              </xsl:element>
            </xsl:if>
            <!-- a simple data mapping: "$smo/body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_dest_cur[10]/desired_destination"(string) to "io6:DesiredDestination"(StringLength0to128) -->
            <xsl:if test="$smo/body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_dest_cur[10]/desired_destination">
              <xsl:element name="io6:DesiredDestination">
                <xsl:value-of select="$smo/body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_dest_cur[10]/desired_destination"/>
              </xsl:element>
            </xsl:if>
            <!-- a simple data mapping: "$smo/body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_prev_crus_cur[1]/previous_cruise_line"(string) to "io6:PreviousCruiseLines"(StringLength0to128) -->
            <xsl:if test="$smo/body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_prev_crus_cur[1]/previous_cruise_line">
              <xsl:element name="io6:PreviousCruiseLines">
                <xsl:value-of select="$smo/body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_prev_crus_cur[1]/previous_cruise_line"/>
              </xsl:element>
            </xsl:if>
            <!-- a simple data mapping: "$smo/body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_prev_crus_cur[2]/previous_cruise_line"(string) to "io6:PreviousCruiseLines"(StringLength0to128) -->
            <xsl:if test="$smo/body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_prev_crus_cur[2]/previous_cruise_line">
              <xsl:element name="io6:PreviousCruiseLines">
                <xsl:value-of select="$smo/body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_prev_crus_cur[2]/previous_cruise_line"/>
              </xsl:element>
            </xsl:if>
            <!-- a simple data mapping: "$smo/body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_prev_crus_cur[3]/previous_cruise_line"(string) to "io6:PreviousCruiseLines"(StringLength0to128) -->
            <xsl:if test="$smo/body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_prev_crus_cur[3]/previous_cruise_line">
              <xsl:element name="io6:PreviousCruiseLines">
                <xsl:value-of select="$smo/body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_prev_crus_cur[3]/previous_cruise_line"/>
              </xsl:element>
            </xsl:if>
            <!-- a simple data mapping: "$smo/body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_prev_crus_cur[4]/previous_cruise_line"(string) to "io6:PreviousCruiseLines"(StringLength0to128) -->
            <xsl:if test="$smo/body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_prev_crus_cur[4]/previous_cruise_line">
              <xsl:element name="io6:PreviousCruiseLines">
                <xsl:value-of select="$smo/body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_prev_crus_cur[4]/previous_cruise_line"/>
              </xsl:element>
            </xsl:if>
            <!-- a simple data mapping: "$smo/body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_prev_crus_cur[5]/previous_cruise_line"(string) to "io6:PreviousCruiseLines"(StringLength0to128) -->
            <xsl:if test="$smo/body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_prev_crus_cur[5]/previous_cruise_line">
              <xsl:element name="io6:PreviousCruiseLines">
                <xsl:value-of select="$smo/body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_prev_crus_cur[5]/previous_cruise_line"/>
              </xsl:element>
            </xsl:if>
            <!-- a simple data mapping: "$smo/body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_prev_crus_cur[6]/previous_cruise_line"(string) to "io6:PreviousCruiseLines"(StringLength0to128) -->
            <xsl:if test="$smo/body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_prev_crus_cur[6]/previous_cruise_line">
              <xsl:element name="io6:PreviousCruiseLines">
                <xsl:value-of select="$smo/body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_prev_crus_cur[6]/previous_cruise_line"/>
              </xsl:element>
            </xsl:if>
            <!-- a simple data mapping: "$smo/body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_prev_crus_cur[7]/previous_cruise_line"(string) to "io6:PreviousCruiseLines"(StringLength0to128) -->
            <xsl:if test="$smo/body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_prev_crus_cur[7]/previous_cruise_line">
              <xsl:element name="io6:PreviousCruiseLines">
                <xsl:value-of select="$smo/body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_prev_crus_cur[7]/previous_cruise_line"/>
              </xsl:element>
            </xsl:if>
            <!-- a simple data mapping: "$smo/body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_prev_crus_cur[8]/previous_cruise_line"(string) to "io6:PreviousCruiseLines"(StringLength0to128) -->
            <xsl:if test="$smo/body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_prev_crus_cur[8]/previous_cruise_line">
              <xsl:element name="io6:PreviousCruiseLines">
                <xsl:value-of select="$smo/body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_prev_crus_cur[8]/previous_cruise_line"/>
              </xsl:element>
            </xsl:if>
            <!-- a simple data mapping: "$smo/body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_prev_crus_cur[9]/previous_cruise_line"(string) to "io6:PreviousCruiseLines"(StringLength0to128) -->
            <xsl:if test="$smo/body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_prev_crus_cur[9]/previous_cruise_line">
              <xsl:element name="io6:PreviousCruiseLines">
                <xsl:value-of select="$smo/body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_prev_crus_cur[9]/previous_cruise_line"/>
              </xsl:element>
            </xsl:if>
            <!-- a simple data mapping: "$smo/body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_prev_crus_cur[10]/previous_cruise_line"(string) to "io6:PreviousCruiseLines"(StringLength0to128) -->
            <xsl:if test="$smo/body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_prev_crus_cur[10]/previous_cruise_line">
              <xsl:element name="io6:PreviousCruiseLines">
                <xsl:value-of select="$smo/body/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGResponse/in:executeNclseaNcl_Wesb_Get_Client_Vacat_PrefBGOutput/NclseaNcl_Wesb_Get_Client_Vacat_Pref/p_prev_crus_cur[10]/previous_cruise_line"/>
              </xsl:element>
            </xsl:if>
          </xsl:element>
        </xsl:element>
        <!-- a simple data mapping: "$smo/context/correlation/ClientID"(string) to "ClientID"(string) -->
        <xsl:if test="$smo/context/correlation/ClientID">
          <xsl:element name="ClientID">
            <xsl:value-of select="$smo/context/correlation/ClientID"/>
          </xsl:element>
        </xsl:if>
      </correlation>
    </context>
  </xsl:template>

  <!-- *****************    Utility Templates    ******************  -->
  <!-- copy the namespace declarations from the source to the target -->
  <xsl:template name="copyNamespaceDeclarations">
    <xsl:param name="root"/>
    <xsl:for-each select="$root/namespace::*[not(name() = '')]">
      <xsl:copy/>
    </xsl:for-each>
  </xsl:template>
</xsl:stylesheet>
