<?xml version="1.0" encoding="UTF-8"?>
<!-- @generated mapFile="xslt/XSLTransformation4_req_1.map" md5sum="f2cd10536ad0df8bd8ccdd63c9374c4b" version="7.6.100" -->
<!--
*****************************************************************************
*   This file has been generated by the IBM XML Mapping Editor.
*
*   Mapping file:		XSLTransformation4_req_1.map
*   Map declaration(s):	XSLTransformation4_req_1
*   Input file(s):		smo://smo/name%3Dwsdl-primary/correlationContext%3D%257Bhttp%253A%252F%252FNCL_CruiseRetrieveClient_Module%257DApp_Context/message%3D%257Bhttp%253A%252F%252FNCL_CruiseRetrieveClient_Module%252FDB_Lookup%257DexecuteNclseaNcl_Wesb_Get_Client_ProgramsBGResponseMsg/xpath%3D%252F/smo.xsd
*   Output file(s):		smo://smo/name%3Dwsdl-primary/correlationContext%3D%257Bhttp%253A%252F%252FNCL_CruiseRetrieveClient_Module%257DApp_Context/message%3D%257Bhttp%253A%252F%252FNCL_WESB_Shared_Library%252FNCL_CruiseRetrieveClient_Interface%257DPerform_NCL_CruiseRetrieveClientResponseMsg/xpath%3D%252F/smo.xsd
*   XSLT import(s):   	XSLTransformation4_req_1_custom.xsl
*
*   Note: Do not modify the contents of this file as it is overwritten
*         each time the mapping model is updated.
*****************************************************************************
-->
<xsl:stylesheet
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xalan="http://xml.apache.org/xslt"
    xmlns:str="http://exslt.org/strings"
    xmlns:set="http://exslt.org/sets"
    xmlns:math="http://exslt.org/math"
    xmlns:fn="http://www.w3.org/2005/xpath-functions"
    xmlns:regexp="http://exslt.org/regular-expressions"
    xmlns:dyn="http://exslt.org/dynamic"
    xmlns:dp="http://www.datapower.com/extensions"
    xmlns:exsl="http://exslt.org/common"
    xmlns:date="http://exslt.org/dates-and-times"
    xmlns:in="http://NCL_CruiseRetrieveClient_Module/DB_Lookup"
    xmlns:in2="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/nclseancl_wesb_get_client_programs"
    xmlns:in3="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/nclseancl_wesb_get_client_programsbg"
    xmlns:in4="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/nclseancl_wesb_get_client_programsp_cursor"
    xmlns:in5="wsdl.http://NCL_CruiseRetrieveClient_Module/DB_Lookup"
    xmlns:in9="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/nclseancl_wesb_get_client_vacat_pref"
    xmlns:in10="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/nclseancl_wesb_get_client_vacat_prefbg"
    xmlns:in6="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/nclseancl_wesb_get_client_profile"
    xmlns:in8="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/nclseancl_wesb_get_client_profilebg"
    xmlns:in7="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/nclseancl_wesb_get_client_profilep_cursor"
    xmlns:in11="http://www.ibm.com/xmlns/prod/websphere/bo/6.0.0"
    xmlns:in12="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/nclseancl_wesb_get_client_vacat_prefp_prev_crus_cur"
    xmlns:in13="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/nclseancl_wesb_get_client_vacat_prefp_dest_cur"
    xmlns:io="http://www.w3.org/2003/05/soap-envelope"
    xmlns:io3="http://www.ibm.com/xmlns/prod/websphere/mq/sca/6.0.0"
    xmlns:io2="http://www.ibm.com/websphere/sibx/smo/v6.0.1"
    xmlns:out="http://NCL_WESB_Shared_Library/NCL_CruiseRetrieveClient_Interface"
    xmlns:io4="http://NCL_CruiseRetrieveClient_Module"
    xmlns:io5="http://schemas.xmlsoap.org/ws/2004/08/addressing"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:io7="http://www.ibm.com/xmlns/prod/websphere/http/sca/6.1.0"
    xmlns:io6="http://nclapi/schemas"
    xmlns:out2="wsdl.http://NCL_WESB_Shared_Library/NCL_CruiseRetrieveClient_Interface"
    xmlns:xs4xs="http://www.w3.org/2001/XMLSchema"
    xmlns:io8="http://www.w3.org/2005/08/addressing"
    xmlns:map="http://NCL_CruiseRetrieveClient_Module/xslt/XSLTransformation4_req_1"
    xmlns:msl="http://www.ibm.com/xmlmap"
    exclude-result-prefixes="in in2 in3 in4 in5 in9 in10 in6 in8 in7 in11 in12 in13 str set math fn regexp dyn dp exsl date map xalan msl"
    version="1.0">

  <!-- imports  -->
  <xsl:import href="XSLTransformation4_req_1_custom.xsl"/>
  <xsl:output method="xml" encoding="UTF-8" indent="no"/>

  <!-- root wrapper template  -->
  <xsl:template match="/">
    <xsl:choose>
      <xsl:when test="msl:datamap">
        <msl:datamap>
          <xsl:element name="dataObject">
            <xsl:attribute name="xsi:type">
              <xsl:value-of select="'io2:ServiceMessageObject'"/>
            </xsl:attribute>
            <xsl:call-template name="map:XSLTransformation4_req_12">
              <xsl:with-param name="smo" select="msl:datamap/dataObject[1]"/>
            </xsl:call-template>
          </xsl:element>
        </msl:datamap>
      </xsl:when>
      <xsl:otherwise>
        <xsl:apply-templates select="io2:smo" mode="map:XSLTransformation4_req_1"/>
      </xsl:otherwise>
    </xsl:choose>
  </xsl:template>

  <!-- This rule represents an element mapping: "io2:smo" to "io2:smo".  -->
  <xsl:template match="io2:smo"  mode="map:XSLTransformation4_req_1">
    <io2:smo>
      <context>
        <correlation>
          <xsl:attribute name="xsi:type">
            <xsl:value-of select="'io4:App_Context'"/>
          </xsl:attribute>
          <!-- a structural mapping: "context/correlation/io6:NCL_CruiseRetrieveClientRQ"(<Anonymous>) to "io6:NCL_CruiseRetrieveClientRQ"(<Anonymous>) -->
          <xsl:if test="context/correlation/io6:NCL_CruiseRetrieveClientRQ">
            <xsl:copy-of select="context/correlation/io6:NCL_CruiseRetrieveClientRQ"/>
          </xsl:if>
          <!-- a simple data mapping: "context/correlation/LogID"(string) to "LogID"(string) -->
          <xsl:if test="context/correlation/LogID">
            <xsl:element name="LogID">
              <xsl:value-of select="context/correlation/LogID"/>
            </xsl:element>
          </xsl:if>
          <xsl:element name="io6:NCL_CruiseRetrieveClientRS">
            <!-- a simple data mapping: "context/correlation/io6:NCL_CruiseRetrieveClientRQ/@TransactionIdentifier"(StringLength1to32) to "TransactionIdentifier"(StringLength1to32) -->
            <xsl:if test="context/correlation/io6:NCL_CruiseRetrieveClientRQ/@TransactionIdentifier">
              <xsl:attribute name="TransactionIdentifier">
                <xsl:value-of select="context/correlation/io6:NCL_CruiseRetrieveClientRQ/@TransactionIdentifier"/>
              </xsl:attribute>
            </xsl:if>
            <!-- a simple data mapping: "context/correlation/io6:NCL_CruiseRetrieveClientRQ/@Version"(decimal) to "Version"(decimal) -->
            <xsl:attribute name="Version">
              <xsl:value-of select="context/correlation/io6:NCL_CruiseRetrieveClientRQ/@Version"/>
            </xsl:attribute>
            <!-- a structural mapping: "context/correlation/io6:NCL_CruiseRetrieveClientRQ/@TransactionIdentifier"(StringLength1to32) to "io6:Success"(SuccessType) -->
            <xsl:if test="context/correlation/io6:NCL_CruiseRetrieveClientRQ/@TransactionIdentifier">
              <xsl:element name="io6:Success">
                <!-- variables for custom code -->
                <xsl:variable name="TransactionIdentifier" select="context/correlation/io6:NCL_CruiseRetrieveClientRQ/@TransactionIdentifier"/>
                <xsl:call-template name="TransactionIdentifierToSuccess">
                  <xsl:with-param name="TransactionIdentifier" select="$TransactionIdentifier"/>
                </xsl:call-template>
              </xsl:element>
            </xsl:if>
            <!-- a structural mapping: "context/correlation/io6:NCL_CruiseRetrieveClientRS/io6:ClientInfo"(<Anonymous>) to "io6:ClientInfo"(<Anonymous>) -->
            <xsl:if test="context/correlation/io6:NCL_CruiseRetrieveClientRS/io6:ClientInfo">
              <xsl:copy-of select="context/correlation/io6:NCL_CruiseRetrieveClientRS/io6:ClientInfo"/>
            </xsl:if>
            <!-- a structural mapping: "context/correlation/io6:NCL_CruiseRetrieveClientRS/io6:LoyaltyInfo"(<Anonymous>) to "io6:LoyaltyInfo"(<Anonymous>) -->
            <xsl:if test="context/correlation/io6:NCL_CruiseRetrieveClientRS/io6:LoyaltyInfo">
              <xsl:copy-of select="context/correlation/io6:NCL_CruiseRetrieveClientRS/io6:LoyaltyInfo"/>
            </xsl:if>
            <!-- a structural mapping: "context/correlation/io6:NCL_CruiseRetrieveClientRS/io6:UserLogin"(<Anonymous>) to "io6:UserLogin"(<Anonymous>) -->
            <xsl:if test="context/correlation/io6:NCL_CruiseRetrieveClientRS/io6:UserLogin">
              <xsl:copy-of select="context/correlation/io6:NCL_CruiseRetrieveClientRS/io6:UserLogin"/>
            </xsl:if>
            <!-- a structural mapping: "context/correlation/io6:NCL_CruiseRetrieveClientRS/io6:VacationPreference"(<Anonymous>) to "io6:VacationPreference"(<Anonymous>) -->
            <xsl:if test="context/correlation/io6:NCL_CruiseRetrieveClientRS/io6:VacationPreference">
              <xsl:copy-of select="context/correlation/io6:NCL_CruiseRetrieveClientRS/io6:VacationPreference"/>
            </xsl:if>
            <xsl:element name="io6:LoyaltyPrograms">
              <!-- a for-each transform: "p_cursor"(NclseaNcl_Wesb_Get_Client_ProgramsP_Cursor) to "io6:LoyaltyInfo"(<Anonymous>) -->
              <xsl:apply-templates select="body/in:executeNclseaNcl_Wesb_Get_Client_ProgramsBGResponse/in:executeNclseaNcl_Wesb_Get_Client_ProgramsBGOutput/NclseaNcl_Wesb_Get_Client_Programs/p_cursor" mode="localP_cursorToLoyaltyInfo_1478389973"/>
            </xsl:element>
          </xsl:element>
        </correlation>
      </context>
    </io2:smo>
  </xsl:template>

  <!-- This rule represents a type mapping: "io2:smo" to "io2:smo".  -->
  <xsl:template name="map:XSLTransformation4_req_12">
    <xsl:param name="smo"/>
    <context>
      <correlation>
        <xsl:attribute name="xsi:type">
          <xsl:value-of select="'io4:App_Context'"/>
        </xsl:attribute>
        <!-- a structural mapping: "$smo/context/correlation/io6:NCL_CruiseRetrieveClientRQ"(<Anonymous>) to "io6:NCL_CruiseRetrieveClientRQ"(<Anonymous>) -->
        <xsl:if test="$smo/context/correlation/io6:NCL_CruiseRetrieveClientRQ">
          <xsl:copy-of select="$smo/context/correlation/io6:NCL_CruiseRetrieveClientRQ"/>
        </xsl:if>
        <!-- a simple data mapping: "$smo/context/correlation/LogID"(string) to "LogID"(string) -->
        <xsl:if test="$smo/context/correlation/LogID">
          <xsl:element name="LogID">
            <xsl:value-of select="$smo/context/correlation/LogID"/>
          </xsl:element>
        </xsl:if>
        <xsl:element name="io6:NCL_CruiseRetrieveClientRS">
          <!-- a simple data mapping: "$smo/context/correlation/io6:NCL_CruiseRetrieveClientRQ/@TransactionIdentifier"(StringLength1to32) to "TransactionIdentifier"(StringLength1to32) -->
          <xsl:if test="$smo/context/correlation/io6:NCL_CruiseRetrieveClientRQ/@TransactionIdentifier">
            <xsl:attribute name="TransactionIdentifier">
              <xsl:value-of select="$smo/context/correlation/io6:NCL_CruiseRetrieveClientRQ/@TransactionIdentifier"/>
            </xsl:attribute>
          </xsl:if>
          <!-- a simple data mapping: "$smo/context/correlation/io6:NCL_CruiseRetrieveClientRQ/@Version"(decimal) to "Version"(decimal) -->
          <xsl:attribute name="Version">
            <xsl:value-of select="$smo/context/correlation/io6:NCL_CruiseRetrieveClientRQ/@Version"/>
          </xsl:attribute>
          <!-- a structural mapping: "$smo/context/correlation/io6:NCL_CruiseRetrieveClientRQ/@TransactionIdentifier"(StringLength1to32) to "io6:Success"(SuccessType) -->
          <xsl:if test="$smo/context/correlation/io6:NCL_CruiseRetrieveClientRQ/@TransactionIdentifier">
            <xsl:element name="io6:Success">
              <!-- variables for custom code -->
              <xsl:variable name="TransactionIdentifier" select="$smo/context/correlation/io6:NCL_CruiseRetrieveClientRQ/@TransactionIdentifier"/>
              <xsl:call-template name="TransactionIdentifierToSuccess">
                <xsl:with-param name="TransactionIdentifier" select="$TransactionIdentifier"/>
              </xsl:call-template>
            </xsl:element>
          </xsl:if>
          <!-- a structural mapping: "$smo/context/correlation/io6:NCL_CruiseRetrieveClientRS/io6:ClientInfo"(<Anonymous>) to "io6:ClientInfo"(<Anonymous>) -->
          <xsl:if test="$smo/context/correlation/io6:NCL_CruiseRetrieveClientRS/io6:ClientInfo">
            <xsl:copy-of select="$smo/context/correlation/io6:NCL_CruiseRetrieveClientRS/io6:ClientInfo"/>
          </xsl:if>
          <!-- a structural mapping: "$smo/context/correlation/io6:NCL_CruiseRetrieveClientRS/io6:LoyaltyInfo"(<Anonymous>) to "io6:LoyaltyInfo"(<Anonymous>) -->
          <xsl:if test="$smo/context/correlation/io6:NCL_CruiseRetrieveClientRS/io6:LoyaltyInfo">
            <xsl:copy-of select="$smo/context/correlation/io6:NCL_CruiseRetrieveClientRS/io6:LoyaltyInfo"/>
          </xsl:if>
          <!-- a structural mapping: "$smo/context/correlation/io6:NCL_CruiseRetrieveClientRS/io6:UserLogin"(<Anonymous>) to "io6:UserLogin"(<Anonymous>) -->
          <xsl:if test="$smo/context/correlation/io6:NCL_CruiseRetrieveClientRS/io6:UserLogin">
            <xsl:copy-of select="$smo/context/correlation/io6:NCL_CruiseRetrieveClientRS/io6:UserLogin"/>
          </xsl:if>
          <!-- a structural mapping: "$smo/context/correlation/io6:NCL_CruiseRetrieveClientRS/io6:VacationPreference"(<Anonymous>) to "io6:VacationPreference"(<Anonymous>) -->
          <xsl:if test="$smo/context/correlation/io6:NCL_CruiseRetrieveClientRS/io6:VacationPreference">
            <xsl:copy-of select="$smo/context/correlation/io6:NCL_CruiseRetrieveClientRS/io6:VacationPreference"/>
          </xsl:if>
          <xsl:element name="io6:LoyaltyPrograms">
            <!-- a for-each transform: "p_cursor"(NclseaNcl_Wesb_Get_Client_ProgramsP_Cursor) to "io6:LoyaltyInfo"(<Anonymous>) -->
            <xsl:apply-templates select="$smo/body/in:executeNclseaNcl_Wesb_Get_Client_ProgramsBGResponse/in:executeNclseaNcl_Wesb_Get_Client_ProgramsBGOutput/NclseaNcl_Wesb_Get_Client_Programs/p_cursor" mode="localP_cursorToLoyaltyInfo_1478389973"/>
          </xsl:element>
        </xsl:element>
      </correlation>
    </context>
  </xsl:template>

  <!-- This rule represents a for-each transform: "p_cursor" to "io6:LoyaltyInfo".  -->
  <xsl:template match="p_cursor"  mode="localP_cursorToLoyaltyInfo_1478389973">
    <io6:LoyaltyInfo>
      <!-- a simple data mapping: "frequent_pgm_account"(string) to "MembershipID"(string) -->
      <xsl:if test="frequent_pgm_account">
        <xsl:attribute name="MembershipID">
          <xsl:value-of select="frequent_pgm_account"/>
        </xsl:attribute>
      </xsl:if>
      <!-- a simple data mapping: "frequent_pgm_code"(string) to "ProgramID"(string) -->
      <xsl:if test="frequent_pgm_code">
        <xsl:attribute name="ProgramID">
          <xsl:value-of select="frequent_pgm_code"/>
        </xsl:attribute>
      </xsl:if>
    </io6:LoyaltyInfo>
  </xsl:template>

  <!-- *****************    Utility Templates    ******************  -->
  <!-- copy the namespace declarations from the source to the target -->
  <xsl:template name="copyNamespaceDeclarations">
    <xsl:param name="root"/>
    <xsl:for-each select="$root/namespace::*[not(name() = '')]">
      <xsl:copy/>
    </xsl:for-each>
  </xsl:template>
</xsl:stylesheet>
